Dockerfile, Makefile, config/test.exs, docker-compose.yml, docs/README.md, docs/dev-env.md
I'm introducing the use of Docker, Docker Compose, and Makefiles in our development process.
- **Docker** is a containerisation platform that allows us to package and run our applications in a portable and isolated environment. With Docker, we can ensure that our application runs consistently across different environments, reducing the risk of configuration errors and improving our ability to deploy our application quickly and efficiently.
- **Docker Compose** is a tool that allows us to define and run multi-container Docker applications. With Docker Compose, we can define our application's services, networks, and volumes in a single configuration file, making it easy to set up and run our application locally.
- **Makefiles** are a simple yet powerful tool for automating tasks in our …
=> Bootstrap Docker, DockerCompose and Makefile targets

lib/operately/kpis.ex, lib/operately/kpis/kpi.ex, lib/operately_web/controllers/kpi_controller.ex, lib/operately_web/controllers/kpi_html.ex, lib/operately_web/controllers/kpi_html/edit.html.heex, lib/operately_web/controllers/kpi_html/index.html.heex, lib/operately_web/controllers/kpi_html/new.html.heex, lib/operately_web/controllers/kpi_html/show.html.heex, lib/operately_web/router.ex, priv/repo/migrations/20230309131630_create_kpis.exs, test/features/groups_test.exs, test/features/kpis.feature, test/features/kpis_test.exs, test/features/okrs_test.exs, test/features/tenets_test.exs, test/operately/kpis_test.exs, test/operately_web/controllers/kpi_controller_test.exs, test/support/features/shared_steps/login.ex, test/support/features/shared_steps/simple_interactions.ex, test/support/fixtures/kpis_fixtures.ex
In this Pull Request, I'm introducing support for KPIs.
KPIs, or Key Performance Indicators, are specific measurements or metrics that are used to evaluate the performance of a business, project, team, or individual. KPIs are usually quantifiable and help to monitor progress towards achieving business goals and objectives.
KPIs can be financial or non-financial, and may vary depending on the industry or business function being measured. For example, in sales, KPIs might include monthly revenue, number of new customers acquired, or average sales per customer. In manufacturing, KPIs might include production output, defect rates, or inventory turnover.
By measuring KPIs, organizations can get a better understanding of how they're performing and identify areas for improvement. KPIs can also …
=> Introducing Key Performance Indicators

lib/operately/projects.ex, lib/operately/projects/project.ex, lib/operately_web/controllers/project_controller.ex, lib/operately_web/controllers/project_html.ex, lib/operately_web/controllers/project_html/edit.html.heex, lib/operately_web/controllers/project_html/index.html.heex, lib/operately_web/controllers/project_html/new.html.heex, lib/operately_web/controllers/project_html/show.html.heex, lib/operately_web/router.ex, priv/repo/migrations/20230309160755_create_projects.exs, test/features/projects.feature, test/features/projects_test.exs, test/features/tenets_test.exs, test/operately/projects_test.exs, test/operately_web/controllers/project_controller_test.exs, test/support/fixtures/projects_fixtures.ex
In this Pull Request, I'm introducing Projects.
Projects are a valuable tool in any organization's operational toolkit, as they provide structure and organization to the work being done. By defining a clear project scope, timeline and milestones, teams can work effectively.
Projects enable teams to allocate resources, track progress, and measure success. By having a clear understanding of what is required to complete a project and when it needs to be done, teams can prioritize their work and make informed decisions about where to focus their efforts.
Projects help to ensure that everyone on the team is on the same page for a given piece of work. This reduces miscommunication, prevents duplication of effort, and helps with collaboration.
Start from the test/features/projects.feature that …
=> Introducing Projects

.gitignore, .semaphore/semaphore.yml, Makefile, README.md, lib/operately/okrs.ex, lib/operately_web/controllers/objective_controller.ex, mix.exs, test/features/groups.feature, test/features/groups_test.exs, test/features/tenets.feature, test/operately_web/controllers/objective_controller_test.exs
In this PR I'm:
- Adding an automatic CI test suite that runs all of the tests in one CI job.
- Fixing tests, and making them all green. There were 5/96 tests that were failing.
- Adding A CI Badge.
=> Set up CI/CD on SemaphoreCI

lib/operately/alignments.ex, lib/operately/alignments/alignment.ex, lib/operately/okrs.ex, lib/operately/okrs/objective.ex, lib/operately_web/components/objective_tree.ex, lib/operately_web/controllers/objective_controller.ex, lib/operately_web/controllers/objective_html.ex, lib/operately_web/controllers/objective_html/index.html.heex, lib/operately_web/controllers/objective_html/new.html.heex, priv/repo/migrations/20230317152250_create_alignments.exs, test/operately/okrs_test.exs
Alignment is a logical connection between objectives and it encodes the connection that an Objective A is a sub-objective of Objective B. For example, the following objectives are considered aligned:
```
+-----------------------------------------------------------------------+
| COO Objective                                                         |
| Streamline internal processes to reduce costs and increase efficiency |
+-----------------------------------------------------------------------+
|
|  +------------------------------------------------------------------+ 
+--| Head of Infrastructure Objective                                 |
| Identify and automate 2 most time consuming manual processes     |
+------------------------------------------------------------------+
|
| …
```
=> Introduce Alignment between Objectives

assets/js/components/Button/index.tsx, assets/js/components/Editor/Footer.tsx, assets/js/components/Editor/MenuBar.tsx, assets/js/components/Editor/index.tsx, assets/js/components/Icon/index.tsx, assets/js/components/RichContent/index.tsx, assets/js/components/SideNavigation/Link.tsx, assets/js/i18n.js, assets/js/pages/ObjectivePage/Champion.tsx, assets/js/pages/ObjectivePage/Feed.tsx, assets/js/pages/ObjectivePage/PeopleSuggestions.tsx, assets/js/pages/ObjectivePage/PostAnUpdate.tsx, assets/js/pages/ObjectivePage/index.tsx, assets/tailwind.config.js, test/features/okrs_test.exs
- Active and non-active states for the editor
- Close editor on blue if there is no content
- Refactor and clean up codebase
https://user-images.githubusercontent.com/1779493/232779009-8c8a506b-9f1a-4c19-b59d-c8068b19ee47.mp4
=> Polish up the editor state

assets/js/components/Button/index.tsx, assets/js/graphql/Groups/index.tsx, assets/js/pages/GroupPage/AddMembersModal.tsx, assets/js/pages/GroupPage/Modal.tsx, assets/js/pages/GroupPage/index.tsx, assets/js/pages/ObjectivePage/Table.tsx, lib/operately/groups.ex, lib/operately_web/schema.ex, test/operately/groups_test.exs, test/support/fixtures/groups_fixtures.ex
In this pull request I'm starting to work on the Groups page. The first element that I'm introducing is a members list, with a modal for adding new members.
=> Groups — Add members

Makefile, assets/js/graphql/Groups/index.tsx, assets/js/pages/GroupListPage/index.tsx, assets/js/pages/GroupPage/GroupMission.tsx, assets/js/pages/GroupPage/index.tsx, lib/operately/groups.ex, lib/operately/groups/group.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230424111700_add_mission_to_groups.exs, test/features/groups.feature, test/features/groups_test.exs
In this pull-request, I'm adding support for expressing a group's mission. The mission is inline editable.
=> Add mission to groups

Makefile, assets/js/components/Form/index.tsx, assets/js/graphql/Groups/index.tsx, assets/js/pages/GroupPage/Modal.tsx, assets/js/pages/GroupPage/PointsOfContact.tsx, assets/js/pages/GroupPage/index.tsx, lib/operately/groups.ex, lib/operately/groups/contact.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230424144020_add_group_contacts_table.exs, test/features/groups.feature, test/features/groups_test.exs
In this pull request I'm introducing support for adding points of contact to a group. Supported actions currently are: listing and creating points of contact.
=> Adding points of contact to a group

assets/js/graphql/Objectives/index.tsx, assets/js/pages/GroupPage/Objectives.tsx, assets/js/pages/GroupPage/index.tsx, assets/js/pages/ObjectiveListPage/index.tsx, lib/operately/okrs.ex, lib/operately/okrs/objective.ex, lib/operately_web/graphql/mutations/groups.ex, lib/operately_web/graphql/mutations/objectives.ex, lib/operately_web/graphql/mutations/projects.ex, lib/operately_web/graphql/queries/objectives.ex, lib/operately_web/graphql/types/objectives.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230425161330_add_group_id_to_objectives.exs, test/features/groups.feature, test/features/groups_test.exs
In this pull-request I'm adding support for listing objectives that are associated with a group. During the introduction of this new feature, GraphQL queries for listing objectives where updated and extracted to a dedicated file.
=> List objectives on groups

Makefile, assets/js/graphql/Objectives/index.tsx, assets/js/pages/GroupPage/Objectives.tsx, assets/js/pages/ObjectivePage/KeyResults.tsx, lib/operately/okrs/key_result.ex, lib/operately_web/graphql/types/key_results.ex, lib/operately_web/graphql/types/objectives.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230426065811_add-steps-to-key-results.exs, test/operately/okrs_test.exs, test/support/fixtures/okrs_fixtures.ex
In this pull-request I'm introducing support for inline listing of key results on the groups page.
=> Show key results on the groups page

assets/js/pages/ObjectiveListPage/index.tsx, test/features/okrs.feature, test/features/okrs_test.exs
In this pull-request I'm adding support for going into an edit mode and start adding targets to existing goals on the company page.
=> Adding targets to existing goals

assets/js/graphql/Objectives/index.tsx, assets/js/pages/ObjectiveListPage/Champion.tsx, assets/js/pages/ObjectiveListPage/index.tsx, lib/operately/okrs.ex, lib/operately/okrs/key_result.ex, lib/operately_web/graphql/mutations/key_results.ex, lib/operately_web/graphql/queries/key_results.ex, lib/operately_web/graphql/types/key_results.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230501204731_add_owner_id_to_key_results.exs, test/features/company_page_test.exs
This pull-request is the continuation of the previously merged pull-request that allowed setting, unsetting, and creating people who are the champion of a given goal. In this pull-request I'm adding the same functionality to targets.
=> Set, change, and unassign Target owners on the Company page

assets/js/graphql/People/index.tsx, assets/js/pages/ProfilePage/index.tsx, assets/js/routes/index.tsx, lib/operately_web/graphql/queries/people.ex, lib/operately_web/schema.ex, test/features/company_page_test.exs, test/features/profile_page_test.exs
In this pull-request I'm bootstrapping a basic profile page for a person. This will be the page that the "Go to profile" button links to from the company page.
Closes https://github.com/operately/operately/issues/52.
=> Bootstrap a basic profile apge

lib/operately_email/templates/project_discussion_comment_submitted.html.eex, lib/operately_email/templates/project_discussion_submitted.html.eex, lib/operately_email/templates/project_review_commented.html.eex, lib/operately_email/templates/project_review_request_submitted.html.eex, lib/operately_email/templates/project_status_update_commented.html.eex, lib/operately_email/templates/project_status_update_submitted.html.eex, lib/operately_email/views/ui_components.ex, lib/prosemirror2html.ex, test/prosemirror2html_test.exs
If a blob (image, file, attachement) is present in the rich text content, convert it to a link in the emails.
=> Handle Blobs in Email

assets/js/layouts/DefaultLayout/index.tsx
Fixes: https://github.com/operately/operately/issues/433
=> Always show goals and people

assets/js/pages/AccountPage/page.tsx, assets/js/pages/GroupPage/page.tsx
**Objective**
- Remove unused cards in the Overview area of Spaces.
**Changes Implemented**
- Removed all cards that were not being used in the Spaces Overview area.
- Updated the layout to maintain visual consistency after the removal of the cards.
=> Update overview section

assets/js/gql/generated.tsx, assets/js/gql/queries/GetMe.graphql, assets/js/graphql/Me/index.tsx, assets/js/pages/AccountEditProfilePage/index.tsx, lib/operately/people/person.ex, lib/operately_web/graphql/mutations/people.ex, lib/operately_web/graphql/types/person.ex, priv/repo/migrations/20240522152329_add_timezone_to_people.exs, test/operately_web/graphql/mutations/people_test.exs
**This pull request includes the following changes to the project:**
- Table and GQL Updates:
- I edited the GQL files to modify the existing table.
- I added a new column to store the time zone.
- Front-End Changes:
**I updated the "Profile Information" form to include a field for selecting the time zone.**
- Test Files Modifications:
- I updated the test files to include cases for testing the time zone field.
=> Set user time zone

assets/js/components/Editor/Blob/AddBlobsEditorCommand.tsx, assets/js/components/Editor/Blob/FileUploader.tsx, assets/js/gql/generated.tsx, assets/js/graphql/Me/index.tsx, assets/js/pages/AccountEditProfilePage/index.tsx, lib/operately_web/graphql/mutations/people.ex, test/operately_web/graphql/mutations/people_test.exs, test/operately_web/graphql/queries/projects_test.exs
**Description:**
This Pull Request implements a feature that allows users to upload customizable avatars on their profile editing page. Previously, users had a static avatar image, but now they can choose and upload their own profile picture.
**Main Changes:**
- Added the FileInput component to handle the upload of image files for the avatar.
- Modified the ProfileForm component to include the functionality of uploading customizable avatars.
- Adjusted the state logic and file handling to ensure that the uploaded avatar is displayed correctly.
- Implemented form validation to ensure that all required fields are filled out before submission.
- Improved error handling to provide appropriate feedback to the user in case of upload or form submission failure.
- Corrected the name of the …
=> User custom avatar

assets/js/pages/AccountEditProfilePage/index.tsx
This pull request addresses a bug where the user's avatar was unintentionally changing when the user's timezone was updated. The issue was traced to a problem in the avatar updating logic, which was mistakenly tied to timezone changes.
**Changes:**
- Decoupled the avatar update logic from timezone updates.
- Refactored the avatar management functions to ensure that avatar changes only occur when explicitly requested by the user.
- Added unit tests to verify that changing the timezone does not affect the user's avatar.
- Updated existing tests to account for the new behavior and ensure no regression.
**Testing:**
- Manually tested the timezone change to ensure the avatar remains consistent.
- Ran the full test suite, with particular attention to the new unit tests, to confirm that no other …
=> Bug Fixed - User avatar change when timezone change

assets/js/api/index.tsx, lib/operately_web/api.ex, lib/operately_web/api/queries/get_activities.ex, lib/turbo_connect/ts_gen.ex, test/turbo_connect/ts_gen_test.exs
Continuation of https://github.com/operately/operately/pull/528.
Draft because I still need to figure out what is the best implementation for the hooks. Should we use a library, or just create a hook ourselves. 🤔
=> Generate hooks for queries

lib/operately/activities/activity.ex
It causes 500 when opening notifications
=> Mark project reviews as deprecated

assets/js/pages/AccountEditProfilePage/index.tsx
- Removed the title "Edit your profile information" from the `Paper.Body` component.
```jsx
<Paper.Root size="small">
<Paper.Navigation>
<Paper.NavItem linkTo="/account">Account</Paper.NavItem>
</Paper.Navigation>
<Paper.Body minHeight="300px">
<h1 className="text-2xl font-bold">Edit your profile information</h1>
<div className="mt-8 flex flex-col gap-8">
<ProfileForm me={me} />
</div>
</Paper.Body>
</Paper.Root>
```
```jsx
<Paper.Root size="small">
<Paper.Navigation>
<Paper.NavItem linkTo="/account">Account</Paper.NavItem>
</Paper.Navigation>
<Paper.Body minHeight="300px">
<div className="mt-8 flex flex-col gap-8">
<ProfileForm me={me} />
</div>
</Paper.Body>
</Paper.Root>
```
The title "Edit your profile information" was removed to streamline the interface and avoid redundancy, as the …
=> Remove "Edit your profile information" title

assets/js/pages/AccountEditProfilePage/index.tsx
Sure, here is the description for your Pull Request (PR) in English:
---
This Pull Request implements several improvements and fixes to the user profile form, aiming to enhance user experience and code quality.
1. **Update `ProfileForm` Component**
2. **Save Changes Button**
- Added a `FilledButton` to save changes, with form validation and loading feedback.
- Fixed bugs in the component state management.
- Improved organization and modularization of the code to facilitate maintenance and readability.
- Added error handling in file uploads.
- Simplified the logic for avatar rendering and state initialization.
This PR significantly enhances the usability of the profile form, adding new functionalities and ensuring a better user experience. The code organization has been improved to …
=> Fixing null avatar bug and Filled button to Save changes

lib/operately/activities/notifications/goal_check_in_commented.ex
=> Fix GoalCheckInCommented notification

lib/operately/activities/notifications/project_discussion_submitted.ex, lib/operately/activities/notifications/project_goal_disconnection.ex
=> Fix project notifications

assets/js/components/Editor/Blob/BlobView.tsx
**Added `node.attrs.src.url` to Missing Parts in Blob View**
**Summary of Changes:**
- **Context:** This PR addresses the issue of missing image URLs in the blob view components of the TipTap editor, ensuring that the correct URL is used in image and file views.
- **Affected Components:**
- `BlobView`: This component determines which specific component (`ImageView` or `FileView`) should be rendered based on the file type (`filetype`).
- `ImageView`: Updated to ensure that the image URL is correctly obtained from `node.attrs.src.url` and used in both the `src` attribute of the `img` tag and in the download and view links.
- `FileView`: No direct changes related to the addressed issue, but reviewed for consistency.
**Technical Details:**
- Added the reference `node.attrs.src.url` in the …
=> Discussion file attachment bug

lib/operately/blobs/update_src_data.ex, test/operately/blobs/update_src_data_test.exs
Changes any instances of src=[object] -> src=url, id=blob-id
=> Fix image refs in rich text documents

assets/js/api/index.tsx, assets/js/pages/DiscussionPage/loader.tsx, lib/operately/updates.ex, lib/operately/updates/update.ex, lib/operately_web/api/queries/get_discussion.ex, test/operately_web/api/queries/get_discussion_test.exs
https://github.com/operately/operately/issues/703
=> fix: Add specs for listing discussion comments in the api

lib/operately/access/filters.ex, lib/operately_web/api/helpers.ex, lib/operately_web/api/queries/get_discussion.ex, lib/operately_web/api/queries/get_discussions.ex, test/operately_web/api/queries/get_assignments_test.exs, test/operately_web/api/queries/get_discussion_test.exs, test/operately_web/api/queries/get_discussions_test.exs
- OperatelyWeb.Api.Queries.GetDiscussion
- OperatelyWeb.Api.Queries.GetDiscussions
=> feat: Add permissions filter to Discussion queries

assets/js/pages/ProjectPage/page.tsx, lib/operately_web/api/serializer.ex, test/support/features/project_check_in_steps.ex
fixes: https://github.com/operately/operately/issues/802
=> fix: Invalid scheduled for date in projects

assets/js/pages/ProjectAddPage/page.tsx, lib/operately/projects.ex, lib/operately_web/api/queries/search_project_contributor_candidates.ex, test/operately_web/api/queries/search_project_contributor_candidates_test.exs
fixes: https://github.com/operately/operately/issues/824
=> fix: Don't return suspended people as contributor candidates

lib/operately_web/api/queries/get_milestone.ex, test/operately_web/api/queries/get_milestone_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Queries.GetMilestone` query.
=> feat: Add permissions filter to GetMilestone query

lib/operately_web/api/queries/get_task.ex, lib/operately_web/api/queries/get_tasks.ex, test/features/project_tasks_test.exs, test/operately_web/api/queries/get_task_test.exs, test/operately_web/api/queries/get_tasks_test.exs
- OperatelyWeb.Api.Queries.GetTask
- OperatelyWeb.Api.Queries.GetTasks
=> feat: Add permissions filter to Taks queries

lib/operately_web/api/queries/get_space.ex, lib/operately_web/api/queries/get_spaces.ex, test/features/notifications_test.exs, test/features/spaces_test.exs, test/operately_web/api/queries/get_space_test.exs, test/operately_web/api/queries/get_spaces_test.exs, test/support/features/notifications_steps.ex, test/support/features/project_creation_steps.ex
- OperatelyWeb.Api.Queries.GetSpace
- OperatelyWeb.Api.Queries.GetSpaces
=> feat: Add permissions filter to Space queries

lib/operately_web/api/queries/get_person.ex, lib/operately_web/api/queries/search_people.ex, test/operately_web/api/queries/get_person_test.exs, test/operately_web/api/queries/search_people_test.exs
- OperatelyWeb.Api.Queries.SearchPeople
- OperatelyWeb.Api.Queries.GetPerson
=> feat: Add permissions filter to GetPerson and SearchPeople queries

rel/make-github-release.exs, rel/single-host/build.exs
Fixes https://github.com/operately/operately/issues/868
=> chore: Switch to using tar.gz instead of zip

docs/installation/single-host.md
fixes https://github.com/operately/operately/issues/869.
=> docs: Link to latest release; Don't point the user to /opt

assets/css/app.css
This warm, very light orange tone will add a welcoming feel. It's in a different color family from our blues, which will make them pop more.
Our current base color feels "green", thus cool as in cold, while this one has a little bit of "red", thus more warm and vivid.
before:
after:
=> feat: Change base color to light peach

lib/operately/access/filters.ex, lib/operately_web/api/mutations/archive_goal.ex, lib/operately_web/api/mutations/archive_project.ex, test/operately_web/api/mutations/archive_goal_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.ArchiveGoal` mutation.
=> feat: Add permissions filter to ArchiveGoal mutation

.semaphore/semaphore.yml, rel/single-host/build.exs
I had a typo in the release process, but it is hard to check if there are no safety guards in place. Adding the safety guard.
=> chore: Add tests for building releases

assets/js/components/SpaceCards/SpaceCard.tsx, assets/js/pages/SpaceListPage/page.tsx
=> feat: Change copy and give more space for descriptions on spaces list.

assets/js/pages/ProjectPage/Header.tsx, assets/js/pages/ProjectPage/NextMilestone.tsx, assets/js/pages/ProjectPage/page.tsx, test/features/project_milestones_test.exs, test/support/features/project_steps.ex
From "There is no X" to "Here's what you can do".
Backported from #882 except for the goal linking which is a new idea.
=> feat: Change zero-state microcopy on project page.

assets/js/pages/ProjectPage/Overview.tsx
fixes https://github.com/operately/operately/issues/804
=> fix: Don't show status and milestone info for closed projects

assets/js/pages/ProjectPage/Banner.tsx, test/support/features/project_steps.ex
fixes: https://github.com/operately/operately/issues/766
=> fix: Display the project paused banner when the project is paused

lib/operately/activities/content/goal_check_in_commented.ex, lib/operately/companies/short_id.ex, lib/operately_email/emails/goal_check_in_commented_email.ex, lib/operately_email/templates/goal_check_in_commented.html.eex, lib/operately_email/templates/goal_check_in_commented.text.eex, test/features/assignments_email_test.exs, test/features/goal_progress_update_test.exs, test/features/project_retrospectives_test.exs, test/operately/companies/short_id_test.exs, test/support/features/goal_progress_update_steps.ex, test/support/features/project_check_in_steps.ex, test/support/features/project_retrospective_steps.ex, test/support/features/ui.ex, test/support/features/ui/emails.ex
fixes: https://github.com/operately/operately/issues/849
=> fix: Goal check-in comment handling

assets/js/pages/DesignPage/Colors.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx
realated to https://github.com/operately/operately/issues/833
=> chore: Bootstrap a minimal design system

assets/js/features/Feed/index.tsx
fixes 
https://github.com/operately/operately/issues/682
Before:
After:
=> fix: Don't allow the content of the feed item to push around other elements in the feed

lib/operately/access/fetch.ex, lib/operately/access/filters.ex, lib/operately/groups.ex, lib/operately/groups/permissions.ex, lib/operately_web/api/mutations/join_space.ex, test/features/spaces_test.exs, test/operately_web/api/mutations/join_space_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.JoinSpace` mutation.
=> feat: Add permissions filter to JoinSpace mutation

assets/js/pages/SpacePage/page.tsx
fixes https://github.com/operately/operately/issues/823
=> fix: Remove min height from the space page to avoid white marks

assets/css/app.css, assets/js/pages/DesignPage/Buttons.tsx, assets/js/pages/DesignPage/Colors.tsx, assets/js/pages/DesignPage/index.tsx, assets/tailwind.config.js
This is an attempt to contribute a little to streamlining our UI elements.
These are basically buttons from Tailwind UI with primary skinned to our `accent-1`.
=> chore: Add buttons to design system.

lib/operately/projects.ex, lib/operately/projects/key_resource.ex, lib/operately/projects/permissions.ex, lib/operately_web/api/mutations/edit_key_resource.ex, test/operately_web/api/mutations/edit_key_resource_test.exs
I've added a permissions check to the `OperatelyWeb.Api.Mutations.EditKeyResource` mutation.
=> feat: Edit key resource security

assets/js/layouts/DefaultLayout/NewDropdown.tsx, assets/js/layouts/DefaultLayout/index.tsx
This button opens a drop down menu with all things you can create in Operately.
This immediately solves the issue of making inviting new people more obvious. But it just makes things easier overall.
---
I copy-pasted from `CompanyDropdown`. Not sure if there's room to DRY.
=> feat: New button in top navigation.

assets/js/components/Avatar/index.tsx
Extracted this from here: https://github.com/operately/operately/pull/957.
fixes https://github.com/operately/operately/issues/930
=> fix: Add border around avatars to avoid floating heads

assets/js/components/Link/index.tsx, assets/js/features/ProjectListItem/index.tsx, assets/js/pages/DesignPage/Buttons.tsx, assets/js/pages/DesignPage/Colors.tsx, assets/js/pages/DesignPage/Links.tsx, assets/js/pages/DesignPage/Menus.tsx, assets/js/pages/DesignPage/Section.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/PeopleOrgChartPage/page.tsx, assets/js/pages/PeoplePage/page.tsx
extracted from https://github.com/operately/operately/pull/957/files
=> chore: Add links to design + adjust link styles

assets/package-lock.json
For some reason this remained uncommitted in the Menu update PR.
=> chore: Update package.lock

lib/operately/projects/permissions.ex, lib/operately_web/api/mutations/move_project_to_space.ex, test/operately_web/api/mutations/move_project_to_space_test.exs
I've added a permissions check to the `OperatelyWeb.Api.Mutations.MoveProjectToSpace` mutation.
=> feat: Move project to space security

lib/operately/goals/permissions.ex, lib/operately_web/api/mutations/post_goal_progress_update.ex, test/operately_web/api/mutations/post_goal_progress_update_test.exs
I've added a permissions check to the `OperatelyWeb.Api.Mutations.PostGoalProgressUpdate` mutation.
=> feat: Post goal progress update security

README.md, assets/js/components/PaperContainer/PageOptions.tsx, assets/js/components/SpacePageNavigation/index.tsx, assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/activities/GoalDiscussionCreation/index.tsx, assets/js/features/goals/GoalPageHeader/index.tsx, assets/js/models/people/index.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, assets/js/pages/ProjectCheckInPage/page.tsx, assets/js/pages/ProjectMilestonePage/Options.tsx, assets/js/pages/ProjectPage/Options.tsx
extracted from https://github.com/operately/operately/pull/957
=> chore: Replace dataTestId with testId and introduce Testable interface

.semaphore/semaphore.yml, Makefile, docs/dev-env.md
fixes https://github.com/operately/operately/issues/970
=> chore: Simplify devenv rebuilds with make dev.build and make dev.server

.semaphore/semaphore.yml, Makefile, assets/js/components/Callouts/index.tsx, assets/js/pages/DesignPage/Callouts.tsx, scripts/prettier-check.sh
fixes https://github.com/operately/operately/issues/1014
Semaphore is ignoring and removing empty lines, but it is in a much better shape than it was:
=> chore: Less verbose fmt check

assets/css/app.css, assets/js/components/Callouts/index.tsx, assets/js/pages/DesignPage/Callouts.tsx, assets/js/pages/DesignPage/Colors.tsx, assets/tailwind.config.js
also removed some leftover unused color definitions.
=> chore: Success callout

assets/js/components/Callouts/index.tsx, assets/js/pages/DesignPage/Callouts.tsx
Applying the newly added `make js.fmt.fix` to the source code.
=> chore: Apply linter fixes

assets/js/models/people/index.tsx, assets/js/pages/CompanyAdminManagePeoplePage/index.tsx, test/features/invite_member_test.exs, test/support/features/invite_member_steps.ex
=> feat: Renew invitation token

assets/js/components/CopyToClipboard/index.tsx
fixes https://github.com/operately/operately/issues/837.
=> fix: Use non-trasparent color for copied message

assets/js/components/Link/index.tsx
=> chore: Differentiating hover colors for black and dimmed links

lib/operately/demo.ex, lib/operately/demo/cleanup.ex, lib/operately/demo/company.ex, lib/operately/demo/employees.ex, lib/operately/demo/goals.ex, lib/operately/demo/spaces.ex, test/operately/demo_test.exs
Run the code to a get a demo organization filled with people, projects and goals.
=> chore: Demo builder

assets/js/components/CopyToClipboard/index.tsx, assets/js/components/Menu/index.tsx, assets/js/components/Tooltip/index.tsx, assets/js/features/ProjectListItem/index.tsx, assets/js/pages/DesignPage/Tooltips.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/ProjectPage/Header.tsx, assets/package-lock.json, assets/package.json
A touchup on the existing tooltip component + adding it to the design system.
Based on Radix primitives: https://www.radix-ui.com/primitives/docs/components/tooltip.
=> chore: Add tooltips to the design system

lib/operately_web/controllers/account_session_html/new.html.heex
I'm aware that this has not been top of mind but the other day I noticed that our entry door looks bad on mobile so let's start slowly improving.
=> feat: Mobile friendly Sign in page

assets/js/api/index.tsx, assets/js/features/ProjectListItem/index.tsx, assets/js/features/goals/GoalTree/components/NodeName.tsx, assets/js/features/projects/PrivacyIndicator.tsx, assets/js/pages/GoalSubgoalsPage/loader.tsx, assets/js/pages/GoalsPage/loader.tsx, assets/js/pages/ProfileGoalsPage/loader.tsx, assets/js/pages/ProjectsPage/loader.tsx, assets/js/pages/SpaceGoalsPage/loader.tsx, assets/js/pages/SpaceProjectsPage/index.tsx, lib/operately/projects/project.ex, lib/operately_web/api/queries/get_projects.ex, lib/operately_web/api/serializers/project.ex
fixes https://github.com/operately/operately/issues/966
=> feat: Show privacy levels on every project list

assets/js/pages/ProjectPage/ContributorsSection.tsx, assets/js/pages/ProjectPage/Header.tsx, assets/js/pages/ProjectPage/index.tsx, test/support/features/project_steps.ex
+ extra: extract contributors section
=> chore: Change Manage Team -> Manage Team & Access

assets/js/components/Forms/TextInput.tsx, assets/js/pages/DesignPage/Forms.tsx
As I'm transitioning the Project Add form, I need placeholders for Text Inputs.
=> chore: Add placeholder for TextInputs

assets/js/components/Forms/FieldGroup.tsx, assets/js/pages/DesignPage/Forms.tsx
In the design:
This is needed on the project add form:
=> chore: Add grid form layout

assets/js/features/Permissions/AccessLevel.tsx, assets/js/features/Permissions/PermissionSelector.tsx, assets/js/features/Permissions/PermissionsContext.tsx, assets/js/features/Permissions/PrivacyLevel.tsx, assets/js/features/Permissions/usePermissionsState.tsx, assets/js/features/Permissions/utils.tsx, assets/js/features/goals/GoalForm/Form.tsx, assets/js/features/goals/GoalForm/useForm.tsx, assets/js/pages/GoalAddPage/page.tsx, assets/js/pages/GoalEditPage/page.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectAddPage/useForm.tsx, assets/js/pages/ProjectEditAccessLevelsPage/page.tsx, assets/js/pages/SpaceAccessManagementPage/SpaceAccessLevel.tsx, assets/js/pages/SpaceAccessManagementPage/page.tsx, assets/js/pages/SpaceAddPage/page.tsx
Prep work for changing the selector UI in the ProjectAdd form.
=> chore: Convert permissions context to a hook

assets/js/components/Form/radio.tsx
=> chore: Fix testID warning in dev

assets/js/api/index.tsx, lib/operately/notifications.ex, lib/operately/notifications/subscription_list.ex, lib/operately/operations/subscriptions_list_editing.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/edit_subscriptions_list.ex, lib/operately_web/api/mutations/subscribe_to_notifications.ex, test/operately_web/api/mutations/edit_subscriptions_list_test.exs
I've added the mutation `OperatelyWeb.Api.Mutations.EditSubscriptionsList`.
=> feat: Add EditSubscriptionsList mutation

assets/js/components/Forms/SelectPerson.tsx, assets/js/components/PeopleSearch/index.tsx, assets/js/pages/CompanyAdminManageAdminsPage/AddAdminsModal.tsx, assets/js/pages/GroupMembersPage/AddMembersModal.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectPage/index.tsx, lib/operately/operations/project_creation.ex, test/features/project_creation_test.exs, test/operately/operations/project_creation_test.exs, test/support/features/project_creation_steps.ex
https://github.com/user-attachments/assets/becfde5a-5a34-4cae-b1bd-1f9b0e6a47c3
=> feat: Allow the creation of projects without reviewers

assets/js/components/ContributorAvatar/index.tsx, assets/js/components/Tooltip/index.tsx, assets/js/pages/ProjectContributorsPage/ContributorItem.tsx, assets/js/pages/ProjectContributorsPage/page.tsx, assets/js/pages/ProjectPage/ContributorsSection.tsx, test/features/project_creation_test.exs, test/support/features/project_creation_steps.ex
=> feat: Show a reviewer placeholder when project has no reviewer

assets/js/components/Badges/AccessLevelBadges.tsx, assets/js/components/Tooltip/index.tsx, assets/js/pages/ProjectContributorsPage/index.tsx, assets/js/utils/strings.tsx
https://github.com/user-attachments/assets/38b757ea-3aa5-4bc9-813c-c99adce127a7
As the video is showcasing all the possibilities, we get a "rainbow effect" of various colors. In practice, most contributors will get the mostly same access level. On the flip side, if someone has a different level, it is instantly noticeable because it will stand out from the crowd.
=> feat: Access Level badges with tooltips

assets/js/api/index.tsx, assets/js/components/Forms/SelectPerson.tsx, assets/js/components/Forms/useSelectPersonField.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/features/Permissions/index.tsx, assets/js/models/projects/index.tsx, assets/js/pages/ProjectContributorsAddPage/index.tsx, assets/js/pages/ProjectContributorsPage/index.tsx, assets/js/pages/ProjectPage/CheckInSection.tsx, assets/js/routes/paths.tsx, lib/operately/activities/content/project_contributor_addition.ex, lib/operately/operations/project_contributor_addition.ex, lib/operately_web/api/mutations/add_project_contributor.ex, test/features/project_creation_test.exs, test/operately_web/api/mutations/add_project_contributor_test.exs, test/support/features/project_creation_steps.ex
https://github.com/user-attachments/assets/74fbd282-c5aa-4329-bd53-e1fb37a10841
=> feat: Add reviewer if missing

assets/js/pages/ProjectContributorsPage/index.tsx, test/features/project_contributors_test.exs, test/support/features/project_contributors_steps.ex
https://github.com/user-attachments/assets/2e5d8ee3-5ff5-4a79-8870-c3706885bd89
=> feat: Remove project reviewer completely from the project

assets/js/api/index.tsx, assets/js/pages/ProjectContributorsAddPage/index.tsx, assets/js/pages/ProjectContributorsEditPage/index.tsx, assets/js/pages/ProjectContributorsPage/index.tsx, assets/js/routes/paths.tsx, lib/operately/operations/project_contributor_editing.ex, lib/operately/projects.ex, lib/operately_web/api/mutations/remove_project_contributor.ex, lib/operately_web/api/mutations/update_project_contributor.ex, test/features/project_contributors_test.exs, test/support/features/project_contributors_steps.ex
https://github.com/user-attachments/assets/34cb4bc9-0380-438c-926f-85561846570a
=> feat: Reassign a Champion or a Reviewer as a contributor on the project

lib/operately/repo/getter.ex
I'm doing some modifications to the get_project API endpoint, and I needed this options. As the `Resource.get` interface is touching lots of places, I would like to confirm this change with you as well @Rockyy174.
=> chore: Introduce with_deleted in the getter

assets/js/features/projectCheckIns/Form/Form.tsx
fixes https://github.com/operately/operately/issues/1126.
=> fix: Form submission loader added to cancel button

assets/js/components/Forms/Submit.tsx
For the project add form, I wanted to have a bigger button, but the default form handler didn't allow it.
=> chore: Allow changing the size of the submit buttons in a form

assets/js/pages/ProjectAddPage/page.tsx
related to https://github.com/operately/operately/issues/769
=> feat: Default access level when creating a project is comment-access

assets/js/features/projects/AccessLevel.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectContributorsPage/index.tsx, assets/js/routes/paths.tsx
related to https://github.com/operately/operately/issues/769
=> feat: Add section about general access to the team and access page

assets/js/pages/ProjectEditAccessLevelsPage/page.tsx, assets/js/pages/ProjectPage/ProjectOptions.tsx
related to https://github.com/operately/operately/issues/769
=> feat: Move the edit access page under the project contributor section

assets/js/pages/ProjectPage/ContributorsSection.tsx
fixes https://github.com/operately/operately/issues/1141
Before:
After:
=> fix: Big round button when the collaborators push the button out of the line

assets/js/features/Permissions/index.tsx, assets/js/features/activities/ProjectContributorEdited/index.tsx
fixes: https://github.com/operately/operately/issues/1139
=> fix: Show feed item when access changes for a contributor 

lib/operately/access/binded_people_loader.ex, lib/operately/projects/project.ex, test/operately/access/binded_people_loader_test.exs, test/support/factory/accounts.ex, test/support/factory/companies.ex, test/support/factory/projects.ex, test/support/factory/spaces.ex, test/support/factory/utils.ex
preparation for https://github.com/operately/operately/issues/684
=> feat: Allow the lookup of all people bound to an access context

assets/js/api/index.tsx, lib/operately/access/binded_people_loader.ex, lib/operately/people/person.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/get_binded_people.ex, lib/operately_web/api/serializers/person.ex, test/operately/access/binded_people_loader_test.exs, test/operately_web/api/queries/get_binded_people_test.exs, test/operately_web/api/queries/get_project_contributor_test.exs, test/support/turbo_case.ex
related to https://github.com/operately/operately/issues/684
=> feat: Expose api endpoint for fetching bound people to a project

assets/js/components/Link/index.tsx, assets/js/pages/ProjectContributorsPage/BorderedRow.tsx, assets/js/pages/ProjectContributorsPage/OtherPeople.tsx, assets/js/pages/ProjectContributorsPage/Section.tsx, assets/js/pages/ProjectContributorsPage/index.tsx, assets/js/pages/ProjectContributorsPage/loader.tsx, test/features/project_check_ins_test.exs, test/features/project_contributors_test.exs, test/support/features/project_check_ins_steps.ex, test/support/features/project_contributors_steps.ex
fixes https://github.com/operately/operately/issues/684
=> feat: Show all people who can see the project

assets/js/components/Forms/useForm.tsx, assets/js/components/Menu/index.tsx, assets/js/pages/ProjectContributorsEditPage/EditContributor.tsx, assets/js/pages/ProjectContributorsEditPage/PageTitle.tsx, assets/js/pages/ProjectContributorsEditPage/ReassignAsContributor.tsx, assets/js/pages/ProjectContributorsEditPage/index.tsx, assets/js/pages/ProjectContributorsEditPage/loader.tsx, assets/js/pages/ProjectContributorsEditPage/useAccessLevelField.tsx, assets/js/pages/ProjectContributorsPage/index.tsx
Preparation for introducing new contributor edit actions.
=> chore: Clean up project contributor page

lib/operately/access.ex, lib/operately/access/binder.ex, lib/operately/operations/project_contributor_edited.ex, lib/operately/projects/project.ex, test/operately/operations/project_contributor_edited_test.exs
Introduces utility functions for working with access bindings.
``` elixir
mike = People.find(...)
context = Project.get_access_context(project_id)
Access.bind_person(context, mike.id, level)
Access.unbind_person(context, mike.id)
```
=> chore: Access binding helpers

.semaphore/cache.yml, .semaphore/semaphore.yml
fixes https://github.com/operately/operately/issues/1188
=> chore: Populate CI cache on every build on the main branch

assets/js/components/FormattedTime/index.tsx, assets/js/pages/ProjectEditTimelinePage/MilestoneList.tsx, assets/js/pages/ProjectEditTimelinePage/useForm.tsx, assets/js/pages/ProjectMilestonePage/useForm.tsx, assets/js/pages/ProjectMilestonesPage/page.tsx, assets/js/utils/time.tsx, test/support/features/invite_member_steps.ex
Fixes https://github.com/operately/operately/issues/1203.
=> fix: Project Timeline shows the correct date regardless of the user's time zone

assets/js/api/index.tsx, lib/operately/groups/group.ex, lib/operately/notifications/subscriber.ex, lib/operately_web/api/queries/get_space.ex, lib/operately_web/api/serializers/space.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_space_test.exs
`OperatelyWeb.Api.Queries.GetSpace` can now include potential subscribers.
=> chore: GetSpace query can include potential subscribers

assets/js/components/Link/index.tsx, assets/js/pages/ProjectContributorsPage/OtherPeople.tsx
=> fix: TestID and unique key warning

assets/js/components/Forms/useForm.tsx, assets/js/components/ProjectPageNavigation/index.tsx, assets/js/features/projects/AccessFields.test.tsx, assets/js/features/projects/AccessFields.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectEditAccessLevelsPage/index.tsx, lib/operately/operations/project_permissions_editing.ex
fixes: https://github.com/operately/operately/issues/1222
=> fix: Fix access level editing

lib/operately/demo/data.ex, lib/operately/demo/people.ex
related to https://github.com/operately/operately/issues/1220
=> chore: Introduce person.reports_to in the demo data

docs/README.md, docs/demo-data.md
fixes #1237 
something is better than nothing.
=> docs: Document the location of demo data

lib/operately/demo/data.ex, lib/operately/demo/goals.ex
fixes: https://github.com/operately/operately/issues/1220
----
remaining sub-tasks:
=> chore: Introduce new demo data

lib/operately/demo.ex, lib/operately/demo/projects.ex, lib/operately/projects.ex, lib/operately/projects/milestone.ex, test/operately/demo_test.exs
Continuation of https://github.com/operately/operately/pull/1229.
=> chore: Mark milestone as done in demo data

lib/operately/demo/data.ex, lib/operately/demo/goals.ex, test/operately/demo_test.exs
related to https://github.com/operately/operately/pull/1229
=> chore: Allow creating annual goals

.semaphore/semaphore.yml
Remove unnecessary and join fast running things into one job.
=> chore: Optimize jobs in CI

assets/js/pages/ProjectRetrospectivePage/page.tsx
Wider page, no separator lines, etc...
=> feat: Visual updates for project retrospectives

assets/js/pages/SpaceProjectsPage/index.tsx, test/features/spaces_test.exs, test/support/features/space_steps.ex
fixes https://github.com/operately/operately/issues/1276
=> fix: Include space name to be able to construct privacy indicator

assets/js/pages/GoalProgressUpdatePage/AckCTA.tsx, lib/operately/goals.ex, lib/operately/goals/goal.ex, lib/operately/goals/permissions.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, test/operately_web/api/queries/get_goal_test.exs
fixes: https://github.com/operately/operately/issues/1305
=> fix: Calculate UI permissions based on access level, not on champion status

assets/js/features/goals/GoalForm/useForm.tsx, assets/js/pages/GoalAddPage/page.tsx, assets/js/pages/GoalPage/index.tsx, test/features/goal_creation_test.exs, test/support/features/goal_steps.ex
fixes https://github.com/operately/operately/issues/1315
=> fix: Save selected parent goal

assets/js/features/goals/GoalTree/tree/buildTree.tsx, lib/operately/activities/content/goal_created.ex, lib/operately/activities/notifications/goal_created.ex, lib/operately/goals/goal.ex, lib/operately/operations/goal_creation.ex, test/support/features/profile_steps.ex, test/support/features/project_creation_steps.ex
fixes: https://github.com/operately/operately/issues/1308
=> fix: Don't assume that a goal always has a champion

assets/js/pages/ProjectEditTimelinePage/MilestoneList.tsx, assets/js/pages/ProjectEditTimelinePage/useForm.tsx, assets/js/pages/ProjectEditTimelinePage/useMilestoneListState.tsx, test/features/project_timeline_test.exs, test/support/features/project_timeline_steps.ex
Fixes https://github.com/operately/operately/issues/1320.
=> fix: Show correct dates regardless of time zone

assets/js/features/Subscriptions/SubscribersSelector.tsx
Fixes https://github.com/operately/operately/issues/1307.
=> fix: Label changed in subscriptions widget

assets/js/components/PaperContainer/Navigation.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/Subscriptions/current-subscriptions/ExistingSubscriptionsList.tsx, assets/js/features/Subscriptions/current-subscriptions/Unsubscribe.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/TaskPage/page.tsx
=> fix: Make discussions mobile responsive

assets/js/components/PaperContainer/index.tsx, assets/js/pages/TaskPage/page.tsx
=> fix: Normalize padding in PaperContainer body

assets/js/features/activities/ProjectGoalConnection/index.tsx
Change description in #1207 for `connecting projects to the goal`
=> chore: Change description for connecting projects to the goal

assets/js/features/Subscriptions/current-subscriptions/ExistingSubscriptionsList.tsx, assets/js/features/Subscriptions/current-subscriptions/Unsubscribe.tsx, assets/js/pages/DiscussionPage/page.tsx
Using `text-[16px]` as a workaround while we can't use `text-base` #1327.
Fixes #1337.
=> fix: Polish responsiveness of the discussion page

assets/js/features/PerfBar/index.tsx, assets/js/features/PerfBar/usePerfBarData.tsx, assets/js/pages/index.tsx, assets/js/routes/pageRoute.tsx, lib/mix/tasks/operately.gen.page.index.ex
=> chore: Show page name in the development toolbar

lib/operately/demo.ex, lib/operately/demo/data.ex, lib/operately/demo/discussions.ex
=> chore: Add a discussion to the demo

assets/css/animations.css, assets/js/components/Menu/index.tsx, assets/js/pages/DesignPage/Menus.tsx
https://github.com/user-attachments/assets/41c22e3c-112b-43fa-9570-27a16deab33b
=> chore: Introduce submenus

assets/js/api/index.tsx, assets/js/features/DevBar/ToggleCompanyOwner.tsx, assets/js/features/DevBar/ToggleTestIds.tsx, assets/js/features/DevBar/index.tsx, assets/js/features/DevBar/useDevBarData.tsx, assets/js/layouts/DefaultLayout/index.tsx, assets/js/models/companies/index.tsx, assets/js/pages/CompanyAdminManageAdminsPage/useForm.tsx, assets/js/routes/pageRoute.tsx, lib/operately/operations/company_admin_adding.ex, lib/operately_web/api/mutations/add_company_admins.ex, lib/operately_web/api/mutations/remove_company_admin.ex, lib/operately_web/api/queries/get_me.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_me_test.exs
fixes https://github.com/operately/operately/issues/1355
=> chore: Add company owner toggle to devbar

assets/js/pages/SpaceAppearancePage/page.tsx, assets/js/pages/SpacePage/page.tsx, test/features/spaces_test.exs, test/support/features/space_steps.ex
fixes https://github.com/operately/operately/issues/1370
=> fix: Edit space appearance

assets/js/pages/ReviewPage/page.tsx, assets/js/utils/time.tsx
Fixes https://github.com/operately/operately/issues/1377.
=> fix: Correct day is displayed on Review page

assets/js/features/Reactions/index.tsx
fixes https://github.com/operately/operately/issues/1374.
=> fix: Set surface-base as bg for reactions popup

assets/js/api/index.tsx, assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/Reactions/index.tsx, assets/js/features/goals/GoalCheckIn/index.tsx, assets/js/pages/DiscussionPage/loader.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/GoalActivityPage/index.tsx, assets/js/pages/GoalProgressUpdatePage/loader.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, assets/js/pages/ProjectCheckInPage/page.tsx, assets/js/pages/ProjectMilestonePage/page.tsx, assets/js/pages/ProjectRetrospectivePage/page.tsx, lib/operately/activities/activity.ex, lib/operately/goals/goal.ex, lib/operately/messages/message.ex, lib/operately_web/api/queries/get_activity.ex, lib/operately_web/api/queries/get_discussion.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, lib/operately_web/api/serializers/activity.ex, lib/operately_web/api/serializers/activity_permission.ex, lib/operately_web/api/serializers/goal_permission.ex, lib/operately_web/api/serializers/message.ex, lib/operately_web/api/types.ex
Fixes https://github.com/operately/operately/issues/1375.
=> fix: Hide comment box when user doesn't have permissions

lib/operately/groups/permissions.ex, lib/operately_web/api/mutations/join_space.ex, test/operately_web/api/mutations/join_space_test.exs
fixes https://github.com/operately/operately/issues/1367
=> fix: View access is enough to join a space

assets/js/features/goals/GoalTree/components/Controls.tsx, assets/js/features/goals/GoalTree/tree/buildTree.test.tsx, assets/js/features/goals/GoalTree/tree/projectNode.tsx, test/features/goal_tree_test.exs, test/support/factory/projects.ex, test/support/features/goal_tree_steps.ex
fixes https://github.com/operately/operately/issues/1379
=> fix: Don't show closed projects by default

assets/js/pages/SpaceAccessManagementPage/page.tsx
fixes https://github.com/operately/operately/issues/1371
=> fix: Don't show access management button if no access

lib/operately/blobs.ex
fixes: https://github.com/operately/operately/issues/1366
=> fix: Set filename for downloaded links via S3

assets/js/components/Editor/Blob/BlobView.tsx, lib/operately/blobs.ex, lib/operately_web/controllers/blob_controller.ex
fixes https://github.com/operately/operately/issues/1366
=> fix: Use filename, not id, when downloading file

assets/js/features/goals/GoalTree/tree-v2.tsx
https://github.com/user-attachments/assets/035708f3-9668-4dc5-a6dd-0e87ce23f19f
=> feat: "Collapse All" and "Expand All" buttons enabled

assets/js/features/goals/GoalTree/components/GoalDetails.tsx
Now, a goal's timeframe, champion, space and subgoals/projects count is also displayed on the Goals page.
https://github.com/user-attachments/assets/417c153c-f1fd-4790-aa32-19980d206336
=> feat: Add goal details to Goals V2 page

assets/js/contexts/CurrentUserContext.tsx, assets/js/layouts/DefaultLayout/Review.tsx, assets/js/models/assignments/index.tsx, assets/js/models/assignments/useAssignmentsCount.tsx, assets/js/models/comments/index.tsx, assets/js/models/notifications.tsx
Now, review count should refresh when the review page loads.
=> Review count refreshed when page loads

lib/operately/projects/check_in.ex, lib/operately/projects/project.ex, lib/operately/projects/retrospective.ex, lib/operately_web/api/queries/get_project.ex, lib/operately_web/api/queries/get_project_check_in.ex, lib/operately_web/api/queries/get_project_retrospective.ex
Fixes https://github.com/operately/operately/issues/1402.
=> fix: Ignore contributors whose person is suspended

assets/js/components/Editor/index.tsx, assets/js/components/Modal/index.tsx, assets/js/features/Subscriptions/current-subscriptions/EditSubscriptionsModal.tsx, assets/js/features/Subscriptions/selector/SubscribersSelectorModal.tsx, assets/js/features/Tasks/NewTaskModal/index.tsx, assets/js/features/goals/GoalTree/components/Controls-v2.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/pages/CompanyAdminManageAdminsPage/AddAdminsModal.tsx, assets/js/pages/CompanyAdminManagePeoplePage/index.tsx, assets/js/pages/ProjectMilestonePage/page.tsx
fixes https://github.com/operately/operately/issues/1414
https://github.com/user-attachments/assets/b0c6f3ab-9a24-4a15-be52-7d9c8ebd5f7a
=> fix: Responsive modals

assets/js/features/goals/GoalTree/components/Controls-v2.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx, test/features/goal_tree_test.exs, test/support/factory/goals.ex, test/support/features/goal_tree_steps.ex
I've added UI tests for the new Goals page.
=> chore: Add UI tests for Goals V2 page

assets/js/components/Duration/index.tsx, assets/js/models/projects/index.tsx, assets/js/pages/ProjectMilestonesPage/page.tsx, assets/js/pages/ProjectPage/TimelineSection.tsx, assets/js/utils/time.test.tsx, assets/js/utils/time.tsx, lib/operately/time.ex, test/features/project_timeline_test.exs, test/operately/data/change_034_add_space_project_pausing_to_activity_test.exs, test/operately_web/api/queries/get_milestone_test.exs, test/operately_web/api/queries/get_project_test.exs, test/support/factory.ex, test/support/factory/accounts.ex, test/support/factory/projects.ex, test/support/features/project_timeline_steps.ex, test/support/features/ui.ex
fixes https://github.com/operately/operately/issues/622
fixes https://github.com/operately/operately/issues/1407
waiting for this one to continue https://github.com/operately/operately/issues/1404, as it will reintroduce the project.closedAt in the API.
=> feat: Show project progress as a countdown

assets/js/components/RichContent/contentOps.tsx, assets/js/features/SpaceTools/Discussions.tsx, assets/knip.json, test/support/features/project_timeline_steps.ex
If the Discussion title doesn't take more than 1 line, a preview of the Discussion content is displayed in the second line.
=> feat: Display content preview in Discussions tool

assets/js/routes/ErrorPage.tsx
=> chore: Show erorr trace in dev and test

assets/js/components/PieChart/index.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/features/SpaceTools/utils.tsx, assets/knip.json
I've added a pie chart component which will be used in the Goals & Projects header in the space tools.
=> feat: Display goals and projects headers in space tools

assets/js/pages/CompanyAdminManageAdminsPage/page.tsx, assets/js/pages/CompanyAdminPage/OptionsMenu.tsx, assets/js/pages/CompanyAdminPage/loader.tsx, assets/js/pages/CompanyAdminPage/page.tsx, test/features/company_admin_test.exs, test/support/features/company_admin_steps.ex
=> feat: Separate the menu to pronounce who can do what

assets/js/features/SpaceTools/Discussions.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/components.tsx
I've defined a fixed height for tools containers.
=> feat: Set fixed height for containers in space tools

assets/js/features/Tasks/NewTaskModal/MultiPeopleSearch.tsx, lib/operately_web/api/queries/search_people.ex
https://github.com/operately/operately/issues/1439
=> fix: Fix race condition between onBlur and onClick events when selecting people in the task popup

assets/js/api/index.tsx, assets/js/components/PieChart/index.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/utils.tsx, lib/operately/goals.ex, lib/operately_web/api/serializers/goal.ex, lib/operately_web/api/types.ex
The pie chart in the Goal & Projects tool is now built using goal updates status.
=> feat: Goals & Projects tools shows pie chart summarizing resources status

lib/mix/tasks/operation/gen_api_mutation.ex
fixes https://github.com/operately/operately/issues/1462
=> chore: Use call and not run for api mutations

lib/mix/tasks/operation/gen_notification_handler.ex
fixes https://github.com/operately/operately/issues/1460
=> chore: Remove excess alias in generated notification code

lib/mix/tasks/operation/gen_api_mutation.ex
fixes https://github.com/operately/operately/issues/1461
=> chore: Inject generated api endpoint into api router

assets/js/features/activities/CompanyAdminAdded/index.tsx, lib/operately_email/templates/company_admin_added.html.eex
fixes https://github.com/operately/operately/issues/1475
=> fix: Link admin added to company admin page 

assets/js/api/index.tsx, assets/js/features/activities/CompanyAdding/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/content/company_adding.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/company_adding.ex, lib/operately/operations/company_adding.ex, lib/operately_web/api/serializers/activity_content/company_adding.ex, lib/operately_web/api/types.ex, test/features/companies_test.exs, test/support/features/companies_steps.ex
fixes https://github.com/operately/operately/issues/839
=> feat: Show company creation in feed

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/components/Status.tsx
On the Goals page, when a user clicks on a project or goal status, they are redirected to the last check-in/update page.
=> feat: Clicking on "status" redirects the user

assets/js/components/Avatar/index.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx
On the Goals page, clicking on a resource now redirects to the resource page.
=> feat: Add resource links to Goals page

assets/js/components/Avatar/index.tsx, assets/js/components/AvatarList/index.tsx, assets/js/components/PeopleSearch/index.tsx, assets/js/features/Tasks/TaskBoard.tsx, assets/js/pages/DesignPage/Avatars.tsx, assets/js/pages/DesignPage/index.tsx
Screenshot from `localhost:4000/__design__`.
=> chore: Introduce avatar list component

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx
Nodes in the goals tree are now aligned:
https://github.com/user-attachments/assets/cdc83410-8d1d-412c-ae00-ea3def41a42e
=> feat: Align tree nodes vertically

assets/js/components/Forms/SelectPerson.tsx, assets/js/components/Forms/TextInput.tsx, assets/js/components/PeopleSearch/index.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectContributorsAddPage/AddContributors.tsx
fixes https://github.com/operately/operately/issues/1487
=> fix: Fix auto-focus for project-add and goal-add pages

assets/js/pages/ProjectEditTimelinePage/page.tsx
fixes https://github.com/operately/operately/issues/1482
=> fix: Justify between title and actions

lib/mix/tasks/operately.gen.operation.ex, lib/mix/tasks/operation/gen_api_mutation.ex
fixes https://github.com/operately/operately/issues/1458
=> chore: Generate mutation API tests

assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectPage/Navigation.tsx, assets/js/routes/paths.tsx
Fixes https://github.com/operately/operately/issues/1501.
https://github.com/user-attachments/assets/11fa3a61-868b-4a92-8c68-09bcc66da2ce
=> fix: Fix project navigation

assets/js/pages/DiscussionPage/page.tsx
fixes https://github.com/operately/operately/issues/1357
=> fix: Misplaced separator dot

assets/js/components/Line/index.tsx, assets/js/features/Feed/index.tsx, assets/js/features/spaces/SpaceCards/SpaceCard.tsx, assets/js/features/spaces/SpaceCards/SpaceCardGrid.tsx, assets/js/pages/SpaceListPage/page.tsx, lib/operately_web/api/queries/get_spaces.ex, test/operately_web/api/queries/get_spaces_test.exs
fixes https://github.com/operately/operately/issues/1431
Some notes:
- I'm very happy with the new space cards that show people. 🏅 
- The top message that says "Good morning" is meh. I like it when there is something on the top, but I would be even more pleased if it showed some actual useful information to me. Leaving it like this until better ideas arrive.
- The styling of the bottom feed could be better.
Before:
After:
=> feat: Feed on homepage

assets/js/features/goals/GoalPageNavigation/index.tsx
Fixes https://github.com/operately/operately/issues/1507.
=> fix: Fix goal navigation

assets/css/app.css, assets/css/lineclamp.css, assets/js/features/Feed/index.tsx
fixes https://github.com/operately/operately/issues/1523
This also fixes weird line breaks in feed elements.
=> fix: Specify that we are only breaking long words, not every possible word

lib/operately/access/access_context.ex, lib/operately/data/change_041_create_one_resource_hub_for_each_existing_space.ex, lib/operately/resource_hubs.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/node.ex, lib/operately/resource_hubs/resource_hub.ex, priv/repo/migrations/20241107152926_add_resource_hub_resource_node_and_folder.exs, priv/repo/migrations/20241107172651_create_one_resource_hub_for_every_existing_space.exs, test/operately/data/change_041_create_one_resource_hub_for_each_existing_space_test.exs
I've added the schemas and migrations for the resource_hubs, nodes and folders. 
I've also added a data migrations which creates one resource hub for every existing space.
=> feat: Add resource hubs, nodes and folders schemas, and create resource hubs for spaces

lib/operately_email/emails/project_check_in_submitted_email.ex, test/features/project_check_ins_test.exs, test/operately_web/api/queries/get_goals_test.exs, test/support/features/project_check_ins_steps.ex
fixes https://github.com/operately/operately/issues/1274
=> fix: Send email to contributors even if project has no reviewer

assets/js/components/Forms/SelectStatus.tsx, assets/js/components/status/Status.tsx, assets/js/features/goals/GoalCheckInForm/Form.tsx, assets/js/pages/GoalProgressUpdateEditPage/index.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, assets/js/pages/ProjectCheckInEditPage/Form.tsx, assets/js/pages/ProjectCheckInNewPage/Form.tsx, assets/js/pages/ProjectCheckInNewPage/loader.tsx
Fixes https://github.com/operately/operately/issues/1326. 
There were actually several pages where we had the same problem 🙈:
- ProjectCheckInNewPage
- ProjectCheckInEditPage
- GoalProgressUpdatePage
- GoalProgressUpdateEditPage
=> fix: Display reviewer name in updade/check-in status

assets/js/features/activities/GoalCheckIn/ConditionChanges.tsx, assets/js/features/goals/GoalCheckIn/TargetsSection.tsx, assets/js/utils/numbers.test.tsx, assets/js/utils/numbers.tsx
fixes https://github.com/operately/operately/issues/1248
=> fix: Round up progress update numbers

assets/js/api/index.tsx, assets/js/features/activities/ProjectKeyResourceAdded/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/content/project_key_resource_added.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/project_key_resource_added.ex, lib/operately/operations/project_key_resource_adding.ex, lib/operately/projects/key_resource.ex, lib/operately_email/emails/project_key_resource_added_email.ex, lib/operately_email/templates/project_key_resource_added.html.eex, lib/operately_email/templates/project_key_resource_added.text.eex, lib/operately_web/api/mutations/add_key_resource.ex, lib/operately_web/api/serializers/activity_content/project_key_resource_added.ex, lib/operately_web/api/types.ex, test/features/project_resources_test.exs, test/operately/operations/project_key_resource_adding_test.exs, test/support/features/feed_steps.ex, test/support/features/project_steps.ex
Handles the "adding key resource" part of https://github.com/operately/operately/issues/666.
=> feat: Adding a key resource shows event in the feed

assets/js/api/index.tsx, assets/js/features/activities/ProjectKeyResourceDeleted/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/content/project_key_resource_deleted.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/project_key_resource_deleted.ex, lib/operately/operations/project_key_resource_adding.ex, lib/operately/operations/project_key_resource_deleting.ex, lib/operately/projects.ex, lib/operately/projects/key_resource.ex, lib/operately_web/api/mutations/edit_key_resource.ex, lib/operately_web/api/mutations/remove_key_resource.ex, lib/operately_web/api/serializers/activity_content/project_key_resource_deleted.ex, lib/operately_web/api/types.ex, test/features/project_resources_test.exs, test/support/features/feed_steps.ex, test/support/features/project_steps.ex
This PR and https://github.com/operately/operately/pull/1543 fix https://github.com/operately/operately/issues/666.
=> feat: Removing a key resource shows event in the feed

lib/operately/activities/content/resource_hub_created.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_created.ex, lib/operately/data/change_041_create_one_resource_hub_for_each_existing_space.ex, lib/operately/operations/resource_hub_creating.ex, lib/operately/resource_hubs.ex, test/operately/operations/resource_hub_creating_test.exs, test/operately_web/api/mutations/create_resource_hub_folder_test.exs, test/support/factory/resource_hubs.ex, test/support/fixtures/resource_hubs_fixtures.ex
I've added the `ResourceHubCreating` operation which creates a Resource Hub as well as its access context and access bindings.
=> feat: Add ResourceHubCreating operation

test/operately_web/api/mutations/create_resource_hub_folder_test.exs
I've added permissions tests for the `CreateResourceHubFolder` operation.
=> chore: Add permissions tests to CreateResourceHubFolder operation

lib/operately/operations/resource_hub_folder_creating.ex, lib/operately/resource_hubs.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/node.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/create_resource_hub_folder.ex, lib/operately_web/api/queries/list_resource_hub_content.ex, lib/operately_web/api/serializers/resource_hub_node.ex, lib/operately_web/paths.ex, priv/repo/migrations/20241112130317_rename_node_folder_field_to_parent_field.exs, test/operately_web/api/queries/list_resource_hub_content_test.exs, test/support/factory.ex, test/support/factory/resource_hubs.ex
I've added the `OperatelyWeb.Api.Queries.ListResourceHubContent` query.
=> feat: Add ListResourceHubContent query

assets/js/pages/SpaceDiscussionsPage/page.tsx
=> fix: Prevent long line overflow

assets/js/api/index.tsx, lib/operately/groups/space_tools.ex, lib/operately/messages/messages_board.ex, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/list_space_tools.ex, lib/operately_web/api/serializers/messages_board.ex, lib/operately_web/api/serializers/resource_hub.ex, lib/operately_web/api/serializers/space_tools.ex, lib/operately_web/api/types.ex, lib/operately_web/paths.ex, test/operately_web/api/queries/list_space_tools_test.exs, test/support/factory.ex
I've added the `OperatelyWeb.Api.Queries.ListSpaceTools` query.
=> feat: add ListSpaceTools query

assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/models/spaces/index.tsx, assets/js/pages/SpacePage/loader.tsx, assets/js/pages/SpacePage/page.tsx, lib/operately_web/api/queries/list_space_tools.ex, lib/operately_web/api/serializers/space_tools.ex, test/operately_web/api/queries/list_space_tools_test.exs, test/support/features/discussions_steps.ex
`OperatelyWeb.Api.Queries.ListSpaceTools` is used to load space tools.
=> chore: Space tools are loaded using ListSpaceTools query

assets/js/api/index.tsx, lib/operately/groups/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/create_resource_hub.ex, test/operately_web/api/mutations/create_resource_hub_test.exs
I've added the `OperatelyWeb.Api.Mutations.CreateResourceHub` mutation.
=> feat: Add CreateResourceHub mutation

assets/js/components/Buttons/OptionsButton.tsx, assets/js/features/SpaceTools/ResourceHub.tsx, assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/SpacePage/page.tsx, assets/js/pages/SpaceResourceHubPage/index.tsx, assets/js/pages/SpaceResourceHubPage/loader.tsx, assets/js/pages/SpaceResourceHubPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx
I've added Resource Hubs as an experimental feature:
https://github.com/user-attachments/assets/f1112a12-45bf-4952-a6f6-1665d549abc2
=> feat: Resource Hub added as experimental feature

assets/js/pages/DiscussionEditPage/index.tsx, assets/js/pages/DiscussionNewPage/index.tsx, test/features/discussions_test.exs, test/support/features/discussions_steps.ex
fixes https://github.com/operately/operately/issues/692
=> feat: Make draft messages generally available

assets/js/api/index.tsx, lib/operately/activities/content/resource_hub_created.ex, lib/operately/activities/content/resource_hub_document_created.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_document_created.ex, lib/operately/operations/resource_hub_document_creating.ex, lib/operately/resource_hubs.ex, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/node.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/create_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex, lib/operately_web/paths.ex, priv/repo/migrations/20241118100459_add_resource_hub_documents_schema.exs, test/operately_web/api/mutations/create_resource_hub_document_test.exs
I've added the `OperatelyWeb.Api.Mutations.CreateResourceHubDocument` mutation.
=> feat: Add CreateResourceHubDocument mutation

assets/js/components/Forms/RichTextArea.tsx, assets/js/pages/ProjectCheckInNewPage/Form.tsx
fixes https://github.com/operately/operately/issues/1574.
=> fix: Avoid race conditions between blur events and editor updates

assets/js/api/index.tsx, assets/js/components/Forms/RichTextArea.tsx, assets/js/components/Forms/TitleInput.tsx, assets/js/components/Forms/index.tsx, assets/js/models/people/index.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubNewDocumentPage/form.tsx, assets/js/pages/ResourceHubNewDocumentPage/index.tsx, assets/js/pages/ResourceHubNewDocumentPage/loader.tsx, assets/js/pages/ResourceHubNewDocumentPage/page.tsx, assets/js/pages/SpaceResourceHubPage/AddNewFiles.tsx, assets/js/pages/SpaceResourceHubPage/NodesList.tsx, assets/js/pages/SpaceResourceHubPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/search_people.ex, test/operately_web/api/queries/get_resource_hub_test.exs
Now we can also add a document to a resource hub:
https://github.com/user-attachments/assets/75b177dd-9e24-4e8f-ba70-f0b04848c273
=> feat: Add ResourceHubNewDocumentPage page

assets/js/api/index.tsx, lib/operately/resource_hubs.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/node.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_resource_hub_folder_test.exs, test/support/factory.ex, test/support/factory/resource_hubs.ex, test/support/fixtures/resource_hubs_fixtures.ex
I've added the `OperatelyWeb.Api.Queries.GetResourceHubFolder` query.
=> feat: Add GetResourceHubFolder query

assets/js/components/Editor/Blob/AddBlobsEditorCommand.tsx
related to https://github.com/operately/operately/issues/1576
=> fix: Prevent large files from breaking the message that is posted

assets/js/api/index.tsx, assets/js/features/ResourceHub/AddNewFiles.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/ZeroNodes.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/pages/ResourceHubFolderPage/index.tsx, assets/js/pages/ResourceHubFolderPage/loader.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, assets/js/pages/ResourceHubNewDocumentPage/form.tsx, assets/js/pages/ResourceHubNewDocumentPage/page.tsx, assets/js/pages/ResourceHubPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_node.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_resource_hub_folder_test.exs, test/operately_web/api/queries/get_resource_hub_test.exs
I've added the `ResourceHubFolderPage` page.
=> feat: Add ResourceHubFolderPage page

assets/js/api/index.tsx, assets/js/components/PaperContainer/Navigation.tsx, assets/js/features/ResourceHub/AddNewFiles.tsx, assets/js/pages/ResourceHubFolderPage/loader.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, lib/operately/resource_hubs/folder.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_resource_hub_folder_test.exs
I've added a navigation to the folders page:
https://github.com/user-attachments/assets/54211d7e-fefc-45b4-9b43-c32f3412e8ff
=> feat: Add navigation to Folder page

lib/operately_web/api/queries/list_space_tools.ex
Fixes https://github.com/operately/operately/issues/1590.
=> fix: Order messages by published_at in space tools

assets/js/api/index.tsx, lib/operately/resource_hubs/document.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, test/operately_web/api/queries/get_resource_hub_document_test.exs
I've added the `OperatelyWeb.Api.Queries.GetResourceHubDocument` query.
=> feat: Add GetResourceHubDocument query

assets/js/api/index.tsx, lib/operately/operations/resource_hub_document_creating.ex, lib/operately/resource_hubs/document.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex, priv/repo/migrations/20241120165930_add_author_field_to_resource_hub_document.exs, test/operately_web/api/queries/get_resource_hub_document_test.exs, test/operately_web/api/queries/get_resource_hub_folder_test.exs, test/support/factory.ex, test/support/factory/resource_hubs.ex, test/support/fixtures/resource_hubs_fixtures.ex
The field `author_id` was missing in the documents schema, so I added it.
=> chore: Add author to document

assets/js/features/ResourceHub/AddFiles.tsx, assets/js/features/ResourceHub/AddFolderModal.tsx, assets/js/features/ResourceHub/AddNewFiles.tsx
I've added a modal for uploading files to the Resource Hub. However, the backend is still not ready for handling file uploads.
=> feat: Add AddFileModal to Resource Hub

assets/js/api/index.tsx, assets/js/features/ResourceHub/AddFiles.tsx, assets/js/features/ResourceHub/AddNewFiles.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/resourceHubs/index.tsx, lib/operately/operations/resource_hub_file_creating.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_node.ex, lib/operately_web/api/types.ex
Resource Hub now supports file uploads.
=> feat: File uploads working

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFolderCreated/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/content/resource_hub_folder_created.ex, lib/operately/activities/preloader.ex, lib/operately/operations/resource_hub_folder_creating.ex, lib/operately_web/api/serializers/activity_content/resource_hub_folder_created.ex, lib/operately_web/api/types.ex
`resource_hub_folder_created` activity records are displayed in the feed.
=> feat: Show folder created activity in the feed

assets/js/api/index.tsx, assets/js/models/reactions/index.tsx, assets/js/pages/ResourceHubDocumentPage/loader.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/permissions.ex, lib/operately/updates/comment.ex, lib/operately/updates/reaction.ex, lib/operately_web/api/mutations/add_reaction.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, test/operately_web/api/mutations/add_reaction_test.exs
Resource Hub Documents now support reactions.
=> feat: Users can add reactions to documents

assets/js/features/CommentSection/useComments.tsx, assets/js/models/comments/index.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/ProjectRetrospectivePage/page.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, lib/operately/activities/content/resource_hub_document_commented.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_document_commented.ex, lib/operately/operations/comment_adding.ex, lib/operately/operations/comment_adding/activity.ex, lib/operately/resource_hubs/document.ex, lib/operately/updates.ex, lib/operately_web/api/mutations/add_reaction.ex, lib/operately_web/api/mutations/create_comment.ex, lib/operately_web/api/queries/get_comments.ex, test/operately_web/api/mutations/add_reaction_test.exs, test/operately_web/api/mutations/create_comment_test.exs
Resource Hub Documents now support comments.
=> feat: Users can add comments to document

assets/js/api/index.tsx, assets/js/features/Subscriptions/SubscribersSelector.tsx, assets/js/pages/ResourceHubNewDocumentPage/form.tsx, assets/js/pages/ResourceHubNewDocumentPage/loader.tsx, lib/operately/notifications/subscription_list.ex, lib/operately/operations/resource_hub_document_creating.ex, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api/mutations/create_resource_hub_document.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/serializers/resource_hub.ex, lib/operately_web/api/types.ex, test/operately_web/api/mutations/create_resource_hub_document_test.exs
I've added the subscriptions widget to the document creation form.
=> feat: Add subscriptions widget to document creation form

assets/js/features/SpaceTools/Discussions.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/ResourceHub.tsx, assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/features/SpaceTools/components.tsx, assets/js/pages/SpacePage/page.tsx
w-340 seems to work good on any screen size if the page layout is xlarge.
=> chore: Adjust tool width to fit 3 boxes on the screen

assets/js/api/index.tsx, assets/js/features/Subscriptions/CurrentSubscriptions.tsx, assets/js/pages/ResourceHubDocumentPage/loader.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, lib/operately/notifications.ex, lib/operately/notifications/subscriber.ex, lib/operately/operations/resource_hub_document_creating.ex, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api/mutations/edit_subscriptions_list.ex, lib/operately_web/api/mutations/subscribe_to_notifications.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex, test/support/fixtures/resource_hubs_fixtures.ex
We can now see and edit a document's subscriptions.
=> feat: Document subscriptions are visible and editable

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubDocumentCreated/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/preloader.ex, lib/operately_web/api/serializers/activity_content/resource_hub_document_created.ex, lib/operately_web/api/types.ex
I've added the `ResourceHubDocumentCreated` event to the feed.
=> feat: Add document created event to feed

lib/operately/activities/notifications/resource_hub_document_created.ex, lib/operately/resource_hubs/notifications.ex, lib/operately_email/emails/resource_hub_document_created_email.ex, lib/operately_email/templates/resource_hub_document_created.html.eex, lib/operately_email/templates/resource_hub_document_created.text.eex, lib/operately_web/paths.ex, test/operately/operations/resource_hub_document_creating_test.exs
When a document is created, subscribers receive a notification.
=> feat: Creating a document notifies subscribers

lib/operately/activities/content/resource_hub_document_edited.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_document_edited.ex, lib/operately/operations/resource_hub_document_editing.ex, lib/operately/resource_hubs.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/edit_resource_hub_document.ex, test/operately_web/api/mutations/edit_resource_hub_document_test.exs
I've added the `OperatelyWeb.Api.Mutations.EditResourceHubDocument` mutation.
=> feat: Add EditResourceHubDocument mutation

lib/operately/activities/content/resource_hub_document_deleted.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_document_deleted.ex, lib/operately/operations/resource_hub_document_deleting.ex, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/node.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/delete_resource_hub_document.ex, priv/repo/migrations/20241126115317_add_soft_deleted_to_documents.exs, test/operately_web/api/mutations/delete_resource_hub_document_test.exs
I've added the `OperatelyWeb.Api.Mutations.DeleteResourceHubDocument` mutation.
=> feat: Add DeleteResourceHubDocument mutation

assets/js/api/index.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubEditDocumentPage/form.tsx, assets/js/pages/ResourceHubEditDocumentPage/index.tsx, assets/js/pages/ResourceHubEditDocumentPage/loader.tsx, assets/js/pages/ResourceHubEditDocumentPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex
I've added the `ResourceHubEditDocumentPage` page.
=> feat: Add document edit page

lib/operately/activities/notifications/resource_hub_document_commented.ex, lib/operately_email/emails/resource_hub_document_commented_email.ex, lib/operately_email/templates/resource_hub_document_commented.html.eex, lib/operately_email/templates/resource_hub_document_commented.text.eex, lib/operately_web/paths.ex, test/operately/operations/comment_adding_test.exs
I've added notifications for document comments.
=> feat: Commenting on document notifies subscribers

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, assets/js/pages/ResourceHubFolderPage/loader.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, assets/js/pages/ResourceHubPage/loader.tsx, assets/js/pages/ResourceHubPage/page.tsx, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
I've added an option to edit documents to the resource hub, folder and document pages.
=> feat: Add document actions to resource hub

assets/js/features/ResourceHub/AddFolderModal.tsx, assets/js/features/ResourceHub/AddNewFiles.tsx, lib/operately/operations/resource_hub_folder_creating.ex, lib/operately/resource_hubs/folder.ex, lib/operately_web/api/mutations/create_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, priv/repo/migrations/20241127142637_remove_description_field_from_folder.exs, test/operately_web/api/mutations/create_resource_hub_folder_test.exs, test/support/fixtures/resource_hubs_fixtures.ex
I've removed the `description` field from folders.
=> chore: Remove description field from folder

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, assets/js/pages/ResourceHubPage/page.tsx, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
A document can now be deleted from a resource hub or folder.
=> feat: Documents can be deleted

lib/operately/activities/notifications/resource_hub_document_edited.ex, lib/operately_email/emails/resource_hub_document_edited_email.ex, lib/operately_email/templates/resource_hub_document_edited.html.eex, lib/operately_email/templates/resource_hub_document_edited.text.eex, test/operately/operations/resource_hub_document_editing_test.exs
I've added notifications for document-edited events.
=> feat: Editing document notifies subscribers

lib/operately/activities/notifications/resource_hub_document_deleted.ex, lib/operately/resource_hubs/notifications.ex, lib/operately_email/emails/resource_hub_document_deleted_email.ex, lib/operately_email/templates/resource_hub_document_deleted.html.eex, lib/operately_email/templates/resource_hub_document_deleted.text.eex, lib/operately_web/paths.ex, test/operately/operations/resource_hub_document_deleting_test.exs
I've added notifications for document-deleted events.
=> feat: Deleting document notifies subscribers

assets/js/features/SpaceTools/components.tsx, assets/js/pages/SpaceDiscussionsPage/page.tsx
It stood out too much to me, text seemed like an announcement and not a placeholder/tip that it is.
=> chore: Reduce font weight on Discussion tool zero state.

assets/js/components/PaperContainer/Navigation.tsx, assets/js/features/ResourceHub/AddFolderModal.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/SpaceTools/ResourceHub.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, lib/operately/resource_hubs/node.ex, lib/operately_web/paths.ex, test/features/project_tasks_test.exs, test/features/resource_hub_test.exs, test/support/factory/resource_hubs.ex, test/support/features/discussions_steps.ex, test/support/features/resource_hub_steps.ex, test/support/features/ui.ex
I've added feature tests for the Resource Hub folders and documents.
=> chore: Add feature tests for Resource Hub

assets/js/api/index.tsx, lib/operately/resource_hubs/file.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/get_resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_resource_hub_file_test.exs
I've added the `OperatelyWeb.Api.Queries.GetResourceHubFile` query.
=> feat: Add GetResourceHubFile query

lib/operately/activities/notifications/resource_hub_file_created.ex, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/notifications.ex, lib/operately_email/emails/resource_hub_file_created_email.ex, lib/operately_email/templates/resource_hub_file_created.html.eex, lib/operately_email/templates/resource_hub_file_created.text.eex, lib/operately_web/paths.ex, test/operately/operations/resource_hub_file_creating_test.exs
I've added notifications for file-created events.
=> feat: Creating file notifies subscribers

assets/js/features/ResourceHub/AddNewFiles.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubFilePage/index.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx
I've added the `ResourceHubFilePage` page, which so far supports only images.
=> feat: Add ResourceHubFilePage page

assets/js/api/index.tsx, assets/js/models/reactions/index.tsx, assets/js/pages/ResourceHubFilePage/Content.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/permissions.ex, lib/operately/updates/reaction.ex, lib/operately_web/api/mutations/add_reaction.ex, lib/operately_web/api/queries/get_resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, test/operately_web/api/mutations/add_reaction_test.exs
I've added Reactions to Resource Hub Files.
=> feat: Add reactions to files

assets/js/api/index.tsx, lib/operately/activities/content/resource_hub_file_deleted.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_file_deleted.ex, lib/operately/operations/resource_hub_file_deleting.ex, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/delete_resource_hub_file.ex, priv/repo/migrations/20241204102735_add_soft_deleted_to_resource_hub_file.exs, test/operately_web/api/mutations/delete_resource_hub_file_test.exs
I've added the `OperatelyWeb.Api.Mutations.DeleteResourceHubFile` mutation.
=> feat: Add DeleteResourceHubFile mutation

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/components/DocumentMenu.tsx, assets/js/features/ResourceHub/components/FileMenu.tsx, assets/js/features/ResourceHub/components/index.tsx, assets/js/models/resourceHubs/index.tsx, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
We can now delete files from a Resource Hub.
=> feat: Files can be deleted

lib/operately/activities/notifications/resource_hub_file_deleted.ex, lib/operately_email/emails/resource_hub_file_deleted_email.ex, lib/operately_email/templates/resource_hub_file_deleted.html.eex, lib/operately_email/templates/resource_hub_file_deleted.text.eex, test/operately/operations/resource_hub_file_deleting_test.exs
I've added notifications for file-deleted events.
=> feat: Deleting file notifies subscribers

assets/js/features/CommentSection/useComments.tsx, assets/js/models/comments/index.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, lib/operately/activities/content/resource_hub_file_commented.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_file_commented.ex, lib/operately/operations/comment_adding.ex, lib/operately/operations/comment_adding/activity.ex, lib/operately/resource_hubs/file.ex, lib/operately/updates.ex, lib/operately/updates/comment.ex, lib/operately_web/api/mutations/add_reaction.ex, lib/operately_web/api/mutations/create_comment.ex, lib/operately_web/api/queries/get_comments.ex, test/operately_web/api/mutations/add_reaction_test.exs, test/operately_web/api/mutations/create_comment_test.exs
I've added comments to Resource Hub Files.
=> feat: Add comments to files

README.md
it's more useful when landing on this first the first time
=> docs: remove alpha large logo and alpha note, add screenshot

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/blobs/index.tsx, assets/js/pages/ResourceHubFilePage/Content.tsx, lib/operately/blobs/blob.ex, lib/operately_web/api/mutations/create_blob.ex, lib/operately_web/api/serializers/blob.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/types.ex, lib/operately_web/paths.ex, priv/repo/migrations/20241205122925_add_height_and_width_fields_to_blobs_schema.exs
I've added a blob serializer and included the `height` and `width` fields in the blobs schema.
=> chore: Add blob serializer and height/width fields

lib/operately/activities/content/resource_hub_folder_renamed.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_folder_renamed.ex, lib/operately/operations/resource_hub_folder_renaming.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/rename_resource_hub_folder.ex, test/operately_web/api/mutations/rename_resource_hub_folder_test.exs
I've added the `OperatelyWeb.Api.Mutations.RenameResourceHubFolder` mutation.
=> feat: Add RenameResourceHubFolder mutation

assets/js/api/index.tsx, assets/js/features/Subscriptions/CurrentSubscriptions.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, lib/operately/notifications.ex, lib/operately/notifications/subscriber.ex, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api/mutations/edit_subscriptions_list.ex, lib/operately_web/api/mutations/subscribe_to_notifications.ex, lib/operately_web/api/queries/get_resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_resource_hub_file_test.exs, test/support/fixtures/resource_hubs_fixtures.ex
Existing subscriptions are now displayed on the file page.
=> feat: Display current subscriptions on file page

lib/operately/activities/content/resource_hub_folder_deleted.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_folder_deleted.ex, lib/operately/operations/resource_hub_folder_deleting.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/delete_resource_hub_folder.ex, priv/repo/migrations/20241206102636_add_soft_deleted_to_folders.exs, test/operately_web/api/mutations/delete_resource_hub_folder_test.exs
I've added the `OperatelyWeb.Api.Mutations.DeleteResourceHubFolder` mutation.
=> feat: Add DeleteResourceHubFolder mutation

assets/js/api/index.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, lib/operately_web/api/queries/get_resource_hub_file.ex
I've added a `Navigation` component to the files page.
=> feat: Add navigation to file page

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/components/FolderMenu.tsx, assets/js/features/ResourceHub/components/index.tsx, assets/js/models/resourceHubs/index.tsx, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
=> feat: Folders can be renamed

assets/js/features/ResourceHub/components/FileMenu.tsx, assets/js/models/blobs/index.tsx, assets/js/models/blobs/useDownloadFile.tsx
Files can now be downloaded from a Resource Hub.
=> feat: Files can be downloaded

lib/operately/demo/data.ex, lib/operately/demo/discussions.ex, lib/operately/demo/goals.ex, lib/operately/demo/people.ex, lib/operately/demo/poor_mans_markdown.ex, lib/operately/demo/projects.ex, lib/operately/demo/resources.ex, lib/operately/demo/spaces.ex, lib/operately/messages/message.ex
related to https://github.com/operately/operately/issues/1665
=> chore: Demo updates for Help Center

assets/js/models/blobs/index.tsx, assets/js/models/blobs/utils.tsx, assets/js/pages/ResourceHubFilePage/Content.tsx
Videos are now also supported in the Resource Hub.
=> feat: Resource Hub supports videos

assets/js/pages/ResourceHubFilePage/Content.tsx
PDFs preview is now also supported in the Resource Hub.
=> feat: Resource Hub supports pdfs

assets/js/models/blobs/index.tsx, assets/js/models/blobs/utils.tsx, assets/js/pages/ResourceHubFilePage/Options.tsx, assets/js/pages/ResourceHubFilePage/page.tsx
I've added the file description and actions to the File page.
=> feat: Add description and actions to file page

assets/js/components/Editor/Blob/BlobView.tsx, assets/js/components/Forms/RichTextArea.tsx, assets/js/components/LoadingProgressBar/index.tsx, assets/js/components/Modal/index.tsx, assets/js/features/ResourceHub/AddFiles.tsx
A progress bar is now displayed while files are being uploaded.
=> feat: Display progress bar while file is being uploaded

lib/operately/activities/content/resource_hub_parent_folder_edited.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_parent_folder_edited.ex, lib/operately/operations/resource_hub_parent_folder_editing.ex, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/edit_parent_folder_in_resource_hub.ex, test/operately_web/api/mutations/edit_parent_folder_in_resource_hub_test.exs
I've added the `OperatelyWeb.Api.Mutations.EditParentFolderInResourceHub` mutation.
=> feat: Add EditParentFolderInResourceHub mutation

lib/operately/demo/data.ex
=> docs: Demo messages in Product, People, and Marketing

lib/operately/activities/content/resource_hub_file_edited.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_file_edited.ex, lib/operately/operations/resource_hub_file_editing.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/edit_resource_hub_file.ex, test/operately_web/api/mutations/edit_resource_hub_file_test.exs
I've added the `OperatelyWeb.Api.Mutations.EditResourceHubFile` mutation.
=> feat: Add EditResourceHubFile mutation

assets/js/api/index.tsx, assets/js/features/ResourceHub/components/FileMenu.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubEditFilePage/form.tsx, assets/js/pages/ResourceHubEditFilePage/index.tsx, assets/js/pages/ResourceHubEditFilePage/loader.tsx, assets/js/pages/ResourceHubEditFilePage/page.tsx, assets/js/pages/ResourceHubFilePage/Options.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
A file's name and description can now be edited.
=> feat: File can be edited

assets/js/features/ResourceHub/FileDragAndDropArea.tsx
I've changed the files drag-and-drop animation. This is what it looks like now:
https://github.com/user-attachments/assets/de51f8dd-8217-43f4-8dde-7afb16f38b4e
=> chore: Improve drag-and-drop animation

lib/operately/demo.ex, lib/operately/demo/comments.ex, lib/operately/demo/data.ex, lib/operately/demo/discussions.ex, lib/operately/demo/poor_mans_markdown.ex, lib/operately/demo/resource_hubs.ex
Our demo now also creates documents within each Space's Resource Hub.
In order to support the latest demo data, I've expanded `Operately.Demo.PoorMansMarkdown` to also support headings and mentions. 
Solves https://github.com/operately/operately/issues/1733.
=> chore: Demo also creates documents within resource hubs

assets/js/features/CommentSection/useComments.tsx, assets/js/pages/DiscussionPage/loader.tsx, lib/operately/access/access_context.ex
Fixes https://github.com/operately/operately/issues/1709.
=> fix: People can be mentioned in comments

assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/GoalsAndProjects/AllDoneState.tsx, assets/js/features/SpaceTools/GoalsAndProjects/RegularState.tsx, assets/js/utils/time.tsx, test/features/spaces_test.exs, test/support/features/spaces_steps.ex
fixes https://github.com/operately/operately/issues/1770
=> feat: Show all done message when all goals and projects are complete

assets/js/api/index.tsx, assets/js/components/Buttons/OptionsButton.tsx, assets/js/features/ResourceHub/AddFilesButton.tsx, assets/js/features/ResourceHub/contexts/NewFileModalsContext.tsx, assets/js/features/ResourceHub/utils.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubNewLinkPage/form.tsx, assets/js/pages/ResourceHubNewLinkPage/index.tsx, assets/js/pages/ResourceHubNewLinkPage/loader.tsx, assets/js/pages/ResourceHubNewLinkPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, assets/js/utils/validators.test.tsx, assets/js/utils/validators.tsx, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
Links can now be added to a Resource Hub. However, we cannot add specific links yet, such as a Google Sheet or Doc link. I will handle those specific links in the near future.
=> feat: Links can be created

lib/operately/activities/notifications/resource_hub_link_created.ex, lib/operately/resource_hubs/notifications.ex, lib/operately_email/emails/resource_hub_link_created_email.ex, lib/operately_email/templates/resource_hub_link_created.html.eex, lib/operately_email/templates/resource_hub_link_created.text.eex, lib/operately_web/paths.ex, test/operately/operations/resource_hub_link_creating_test.exs
I've added notifications for link-created events.
=> feat: Creating a link notifies subscribers

assets/js/api/index.tsx, assets/js/features/ResourceHub/utils.tsx, assets/js/features/Subscriptions/CurrentSubscriptions.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubLinkPage/index.tsx, assets/js/pages/ResourceHubLinkPage/loader.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, assets/js/pages/ResourceHubNewLinkPage/form.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, lib/operately/notifications.ex, lib/operately/resource_hubs/node.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api/mutations/edit_subscriptions_list.ex, lib/operately_web/api/mutations/subscribe_to_notifications.ex, lib/operately_web/api/serializers/resource_hub_node.ex, lib/operately_web/api/types.ex
I've added a page for Resource Hub Links.
=> feat: Add Link page

lib/operately/activities/notifications/resource_hub_link_commented.ex, lib/operately_email/emails/resource_hub_link_commented_email.ex, lib/operately_email/templates/resource_hub_link_commented.html.eex, lib/operately_email/templates/resource_hub_link_commented.text.eex, lib/operately_web/paths.ex, test/operately/operations/comment_adding_test.exs
I've added notifications for link-commented events.
=> feat: Commenting on link notifies subscribers

assets/js/features/documents/DocumentTitle.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx
Fixes https://github.com/operately/operately/issues/1799.
This PR unifies the document title from discussions and documents from resource hub into one single component.
=> feat: Visual improvements for document title

assets/js/api/index.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx, assets/js/pages/ResourceHubLinkPage/loader.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, assets/js/pages/ResourceHubPage/page.tsx, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/link.ex, lib/operately/resource_hubs/node.ex, lib/operately_web/api/queries/get_resource_hub_file.ex, lib/operately_web/api/queries/get_resource_hub_link.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/serializers/resource_hub_link.ex, lib/operately_web/api/types.ex, test/features/resource_hub_test.exs, test/support/features/resource_hub_steps.ex
Fixes https://github.com/operately/operately/issues/1746.
=> feat: Add complete navigation to Link and File pages

assets/js/components/PaperContainer/index.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx
fixes: https://github.com/operately/operately/issues/1760
=> fix: Adjust sizing to improve readability

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/components/DocumentMenu.tsx, assets/js/features/ResourceHub/components/LinkMenu.tsx, assets/js/features/ResourceHub/components/MoveResources/index.tsx, assets/js/features/ResourceHub/components/index.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubDocumentPage/Options.tsx, assets/js/pages/ResourceHubFilePage/Options.tsx, assets/js/pages/ResourceHubLinkPage/Options.tsx, assets/js/pages/ResourceHubLinkPage/loader.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, lib/operately/resource_hubs/link.ex, lib/operately_web/api/mutations/edit_parent_folder_in_resource_hub.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, test/features/resource_hub_test.exs, test/support/features/resource_hub_steps.ex
Links can now be deleted from both a nodes list and the link's page.
=> feat: Links can be deleted and moved

lib/operately/activities/content/resource_hub_link_edited.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_link_edited.ex, lib/operately/operations/resource_hub_link_editing.ex, lib/operately/resource_hubs/link.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/edit_resource_hub_link.ex, test/operately_web/api/mutations/edit_resource_hub_link_test.exs
I've added the `OperatelyWeb.Api.Mutations.EditResourceHubLink` mutation.
=> feat: Add EditResourceHubLink mutation

lib/operately/activities/notifications/resource_hub_link_deleted.ex, lib/operately_email/emails/resource_hub_link_deleted_email.ex, lib/operately_email/templates/resource_hub_link_deleted.html.eex, lib/operately_email/templates/resource_hub_link_deleted.text.eex, test/features/resource_hub_link_test.exs, test/operately/operations/resource_hub_link_deleting_test.exs, test/support/features/resource_hub_link_steps.ex
I've added notifications for link-deleted events.
=> feat: Deleting link notifies subscribers

assets/js/api/index.tsx, assets/js/components/PaperContainer/Navigation.tsx, assets/js/features/ResourceHub/components/LinkMenu.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubEditLinkPage/form.tsx, assets/js/pages/ResourceHubEditLinkPage/index.tsx, assets/js/pages/ResourceHubEditLinkPage/loader.tsx, assets/js/pages/ResourceHubEditLinkPage/page.tsx, assets/js/pages/ResourceHubLinkPage/Options.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx, lib/operately_web/api/serializers/resource_hub_link.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, test/features/resource_hub_link_test.exs, test/support/features/resource_hub_link_steps.ex
=> feat: Links can be edited

assets/js/features/ResourceHub/utils.tsx, assets/js/features/SpaceTools/ResourceHubs/RegularState.tsx
Fixes https://github.com/operately/operately/issues/1788.
=> fix: Sort Resources Hub nodes on Space page

lib/operately/activities/notifications/resource_hub_link_edited.ex, lib/operately_email/emails/resource_hub_link_edited_email.ex, lib/operately_email/templates/resource_hub_link_edited.html.eex, lib/operately_email/templates/resource_hub_link_edited.text.eex, test/features/resource_hub_link_test.exs, test/operately/operations/resource_hub_link_editing_test.exs, test/support/features/resource_hub_link_steps.ex
I've added notifications for link-edited events.
=> feat: Editing link notifies subscribers

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubDocumentCommented/index.tsx, assets/js/features/activities/ResourceHubDocumentCreated/index.tsx, assets/js/features/activities/ResourceHubDocumentDeleted/index.tsx, assets/js/features/activities/ResourceHubDocumentEdited/index.tsx, assets/js/features/activities/ResourceHubFileCommented/index.tsx, assets/js/features/activities/ResourceHubFileCreated/index.tsx, assets/js/features/activities/ResourceHubFileDeleted/index.tsx, assets/js/features/activities/ResourceHubFileEdited/index.tsx, assets/js/features/activities/ResourceHubFolderCreated/index.tsx, assets/js/features/activities/ResourceHubFolderDeleted/index.tsx, assets/js/features/activities/ResourceHubFolderRenamed/index.tsx, assets/js/features/activities/ResourceHubLinkCreated/index.tsx, assets/js/features/activities/ResourceHubLinkDeleted/index.tsx, assets/js/features/activities/feedItemLinks.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_document_commented.ex, lib/operately_web/api/serializers/activity_content/resource_hub_document_created.ex, lib/operately_web/api/serializers/activity_content/resource_hub_document_deleted.ex, lib/operately_web/api/serializers/activity_content/resource_hub_document_edited.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_commented.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_created.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_deleted.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_edited.ex, lib/operately_web/api/serializers/activity_content/resource_hub_folder_created.ex, lib/operately_web/api/serializers/activity_content/resource_hub_folder_deleted.ex, lib/operately_web/api/serializers/activity_content/resource_hub_folder_renamed.ex, lib/operately_web/api/serializers/activity_content/resource_hub_link_created.ex, lib/operately_web/api/types.ex, test/support/features/resource_hub_link_steps.ex, test/support/features/resource_hub_steps.ex
Fixes https://github.com/operately/operately/issues/1795.
=> fix: Include name of space in feed items outside of space

assets/js/api/index.tsx, assets/js/features/ResourceHub/AddFileModal.tsx, assets/js/features/activities/ResourceHubFileCreated/index.tsx, lib/operately/activities/content/resource_hub_file_created.ex, lib/operately/activities/notifications/resource_hub_file_created.ex, lib/operately/data/change_046_update_file_created_activity_format.ex, lib/operately/operations/notifications/subscription.ex, lib/operately/operations/resource_hub_file_creating.ex, lib/operately_email/emails/resource_hub_file_created_email.ex, lib/operately_email/templates/resource_hub_file_created.html.eex, lib/operately_email/templates/resource_hub_file_created.text.eex, lib/operately_web/api/mutations/create_resource_hub_file.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_created.ex, lib/operately_web/api/types.ex, priv/repo/migrations/20250108125221_update_file_created_activity_format.exs, test/operately/data/change_046_update_file_created_activity_format_test.exs, test/operately/operations/comment_adding_test.exs, test/operately/operations/resource_hub_file_creating_test.exs, test/operately/operations/resource_hub_file_deleting_test.exs, test/operately_web/api/mutations/create_resource_hub_file_test.exs, test/support/features/resource_hub_steps.ex
The `Operately.Operations.ResourceHubFileCreating` operation can create multiple files at a time.
=> chore: ResourceHubFileCreating operation creates multiple files

assets/js/components/PaperContainer/Header.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/features/ResourceHub/AddFilesButton.tsx, assets/js/features/ResourceHub/NodesList.tsx
fixes https://github.com/operately/operately/issues/1820.
=> chore: Improve layout on mobile

assets/js/pages/LoginPage/index.tsx
fixes https://github.com/operately/operately/issues/1841
=> fix: Log in page doesn't react to return key

lib/operately_web/api/ids.ex, lib/operately_web/api/queries/list_space_tools.ex, test/operately_web/api/queries/list_space_tools_test.exs
fixes https://github.com/operately/operately/issues/1771
=> fix: Handling of 422 in API

assets/js/api/index.tsx, assets/js/features/ResourceHub/DocumentPageNavigation.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, assets/js/pages/ResourceHubEditDocumentPage/loader.tsx, assets/js/pages/ResourceHubEditDocumentPage/page.tsx, lib/operately_web/api/queries/get_resource_hub_document.ex
fixes https://github.com/operately/operately/issues/1851
=> fix: Edit document page navigation

Makefile
fixes https://github.com/operately/operately/issues/1382
=> chore: Generate an OPERATELY_BLOB_TOKEN_SECRET_KEY for development

assets/js/features/ResourceHub/FolderSelectField/index.tsx, assets/js/features/ResourceHub/FolderSelectField/viewModel.tsx, assets/js/features/ResourceHub/components/CopyResource.tsx, assets/js/features/ResourceHub/components/MoveResource.tsx
fixes https://github.com/operately/operately/issues/1798
=> feat: Visually improve the move and copy UX

assets/js/features/ResourceHub/LinkIcon.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/pages/ResourceHubNewLinkPage/form.tsx, assets/js/pages/ResourceHubNewLinkPage/page.tsx
fixes https://github.com/operately/operately/issues/1798
=> feat: Visual improvements for the new link page

assets/js/api/index.tsx, assets/js/components/Forms/index.tsx, assets/js/features/ResourceHub/components/CopyDocument.tsx, assets/js/features/ResourceHub/components/CopyFolder.tsx, assets/js/features/ResourceHub/components/CopyResource.tsx, assets/js/features/ResourceHub/components/DocumentMenu.tsx, assets/js/features/ResourceHub/components/FolderMenu.tsx, assets/js/models/resourceHubs/index.tsx, lib/operately/operations/resource_hub_folder_copying.ex, lib/operately/operations/resource_hub_folder_copying/folders.ex, lib/operately/resource_hubs/node.ex, lib/operately_web/api/mutations/copy_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, test/operately/operations/resource_hub_folder_copying_test.exs, test/operately_web/api/mutations/copy_resource_hub_folder_test.exs
=> feat: Folder can be copied

assets/js/api/index.tsx, assets/js/components/status/constants.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/components/Status.tsx, assets/js/features/goals/GoalTree/tree/goalNode.tsx, assets/js/features/goals/GoalTree/tree/node.tsx, assets/js/features/goals/GoalTree/tree/projectNode.tsx, assets/js/pages/GoalClosingPage/page.tsx, lib/operately_web/api/serializers/goal.ex, lib/operately_web/api/types.ex, test/features/goal_tree_test.exs, test/operately_web/api/mutations/close_goal_test.exs, test/support/features/goal_tree_steps.ex
When a goal is marked as completed, we display the Accomplished/Not accomplished status in the goal map:
=> feat: Show accomplished/not accomplished in goal map

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/GoalStatusCompact.tsx, assets/js/features/goals/GoalTree/index.tsx
=> feat: Show warning if goal is overdue

assets/js/__tests__/mocks/index.tsx, assets/js/components/TimeframeSelector/index.tsx, assets/js/features/goals/GoalTree/components/Controls.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/GoalStatusCompact.tsx, assets/js/features/goals/GoalTree/components/NodeName.tsx, assets/js/features/goals/GoalTree/index.tsx, assets/js/features/goals/GoalTree/tree/__tests__/buildTree.test.tsx, assets/js/features/goals/GoalTree/tree/buildTree.tsx, assets/js/features/goals/GoalTree/tree/goalNode.tsx, assets/js/features/goals/GoalTree/tree/node.tsx, assets/js/features/goals/GoalTree/tree/projectNode.tsx, assets/js/features/goals/GoalTree/treeContext.tsx, assets/js/utils/time.tsx, assets/js/utils/timeframes.test.tsx, assets/js/utils/timeframes.tsx, test/support/factory/goals.ex
fixes https://github.com/operately/operately/issues/1823
=> feat: Time travel for goals map

assets/js/layouts/CompanyLayout/CompanyDropdown.tsx, assets/js/layouts/CompanyLayout/DropdownMenu.tsx, assets/js/layouts/CompanyLayout/HelpDropdown.tsx, assets/js/layouts/CompanyLayout/NewDropdown.tsx, assets/js/layouts/CompanyLayout/index.tsx, assets/js/routes/paths.tsx, test/support/features/goal_creation_steps.ex
fixes https://github.com/operately/operately/issues/1839
=> feat: In app help menu

assets/js/features/goals/GoalTree/components/Controls.tsx
fixes https://github.com/operately/operately/issues/1728
=> fix: Fix expand all/collapse all button

assets/js/features/goals/GoalTree/context/Expandable.tsx, assets/js/features/goals/GoalTree/treeContext.tsx, assets/js/hooks/useStateWithLocalStorage.tsx, assets/js/utils/timeframes.tsx
fixes https://github.com/operately/operately/issues/1885
=> feat: Remember timeframe selection in Goal Map

assets/js/components/TimeframeSelector/index.tsx, assets/js/utils/timeframes.tsx
fixes https://github.com/operately/operately/issues/1898
=> fix: Change timeframe when you change the timeframe type

assets/js/features/goals/GoalTree/GoalSelector.tsx, assets/js/features/goals/GoalTree/GoalSelectorDropdown.tsx, assets/js/features/goals/GoalTree/components/Controls.tsx, assets/js/features/goals/GoalTree/tree/__tests__/buildTree.test.tsx, assets/js/features/goals/GoalTree/tree/__tests__/treeTester.tsx, assets/js/features/goals/GoalTree/tree/buildTree.tsx, assets/js/features/goals/GoalTree/treeContext.tsx, test/features/goal_tree_test.exs, test/support/features/goal_tree_steps.ex
fixes https://github.com/operately/operately/issues/1886
=> feat: Show/hide goals and projects in the goal map

assets/js/components/Forms/Form.tsx, assets/js/features/ResourceHub/FolderSelectField/index.tsx, assets/js/features/ResourceHub/components/MoveResource.tsx, test/features/resource_hub_document_test.exs, test/features/resource_hub_file_test.exs, test/features/resource_hub_folder_test.exs, test/features/resource_hub_link_test.exs, test/support/features/resource_hub/moving.ex, test/support/features/resource_hub_document_steps.ex, test/support/features/resource_hub_file_steps.ex, test/support/features/resource_hub_folder_steps.ex, test/support/features/resource_hub_link_steps.ex, test/support/features/resource_hub_steps.ex
I've added feature tests for moving documents, files, links and folders.
=> chore: Add tests for moving resources

test/support/features/ui.ex
This is an attempt to stabilize `UI.refute_text/3` which got kind of flaky since the Resource Hub tests were added.
=> fix: Stabilize UI.refute_text/3

assets/js/features/ResourceHub/components/CopyResource.tsx, test/features/resource_hub_document_test.exs, test/features/resource_hub_folder_test.exs, test/support/features/resource_hub_document_steps.ex, test/support/features/resource_hub_folder_steps.ex
I've added feature for copying documents and folders.
=> chore: Add feature tests for copying resources

assets/js/features/ResourceHub/AddFileWidget.tsx, assets/js/features/ResourceHub/components/FileMenu.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/features/ResourceHub/utils.tsx, assets/js/pages/ResourceHubEditFilePage/form.tsx, assets/js/pages/ResourceHubFilePage/Options.tsx, assets/js/pages/ResourceHubFilePage/page.tsx
Fixes https://github.com/operately/operately/issues/1866
=> fix: File extension is not editable

assets/js/features/ResourceHub/components/FileMenu.tsx, test/features/resource_hub_file_test.exs, test/support/features/resource_hub_file_steps.ex
I've added feature tests for editing files.
=> chore: Add feature tests for editing a file

assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/models/companies/hasFeature.tsx, assets/js/models/companies/index.tsx, assets/js/pages/SpacePage/loader.tsx, assets/js/pages/SpacePage/page.tsx, knip.json, test/support/features/resource_hub_steps.ex
I'm removing the "resource_hubs" experimental feature condition. Now, the Resource Hub feature will be available to every company by default.
=> feat: Release Resource Hub feature

assets/js/features/goals/GoalTree/treeContext.tsx, assets/js/pages/GoalSubgoalsPage/page.tsx, assets/js/pages/GoalsAndProjectsPage/page.tsx, assets/js/pages/ProfileGoalsPage/page.tsx, assets/js/pages/SpaceGoalsPage/page.tsx
fixes https://github.com/operately/operately/issues/1904
=> feat: Use a different namespace for different goals-and-project contexts

assets/js/components/TextElements/index.tsx, assets/js/features/ResourceHub/NodeDescription.tsx, assets/js/features/documents/DocumentTitle.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, test/support/features/resource_hub_link_steps.ex
fixes https://github.com/operately/operately/issues/1864
fixes https://github.com/operately/operately/issues/1862
=> feat: Improve the visuals of the the link page

lib/operately/blobs.ex
fixes https://github.com/operately/operately/issues/999
=> fix: Use www form params instead of simple encode for disposition filename

assets/js/components/FormattedTime/LongDate.tsx, assets/js/utils/numbers.test.tsx, assets/js/utils/numbers.tsx
Fixes https://github.com/operately/operately/issues/1916.
=> fix: Ordinal numbers are displayed correctly in dates

assets/js/components/AvatarList/index.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx
fixes https://github.com/operately/operately/issues/1878
=> feat: Never wrap avatars on goal map

assets/js/components/Pages/Page.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/pages/GoalsAndProjectsPage/page.tsx
fixes https://github.com/operately/operately/issues/1909
=> fix: Remove unnecessary scroll on goal map page

assets/js/pages/ReviewPage/AssignmentsList.tsx, assets/js/pages/ReviewPage/page.tsx, test/features/review_test.exs, test/support/features/review_steps.ex
I've updated the Review Screen according to https://github.com/operately/operately/issues/1705. 
@shiroyasha and I discussed the result and some more UI work will be needed, so the issue will remain open for further improvements.
=> chore: Separate review assignments on Review Page

assets/js/features/goals/GoalForm/Form.tsx, assets/js/features/goals/GoalForm/useForm.tsx, assets/js/models/people/index.tsx, lib/operately/repo/getter.ex, lib/operately_web/api/mutations/create_goal.ex, test/operately_web/api/mutations/create_goal_test.exs, test/support/features/goal_creation_steps.ex, test/support/features/goal_steps.ex
Fixes https://github.com/operately/operately/issues/1897.
=> fix: Only show possible contributors who have access when creating a goal

assets/js/pages/GoalProgressUpdatePage/page.tsx, lib/operately_web/paths.ex, test/features/review_test.exs, test/support/factory.ex, test/support/factory/goals.ex, test/support/factory/projects.ex, test/support/features/review_steps.ex
Split up tests into smaller well defined behaviors that test one flow at a time.
=> chore: Refactor review page BDD tests

assets/js/pages/ReviewPage/AssignmentsList.tsx, assets/js/pages/ReviewPage/loader.tsx, assets/js/pages/ReviewPage/page.tsx, test/support/features/review_steps.ex
fixes https://github.com/operately/operately/issues/1705
fixes https://github.com/operately/operately/issues/800
=> feat: New visuals for the review page, improved zero state

assets/js/features/goals/GoalPageHeader/index.tsx, test/features/goal_test.exs
fixes https://github.com/operately/operately/issues/1896
=> chore: Remove archivation option from the goal options

lib/operately/assignments/assignment.ex, lib/operately/assignments/filter_late_assignments.ex, lib/operately/assignments/loader.ex, lib/operately/assignments/management_hierarchy.ex, lib/operately/assignments/reviewable.ex, lib/operately_web/api/serializers/person.ex, test/operately/assignments/loader_test.exs
`Operately.Assignments.Loader` now includes a list of individuals responsible for a specific assignment. The list is ordered from the most senior to the least senior in the management hierarchy.
=> chore: Assignments loader includes management hierarchy

assets/js/features/Permissions/PermissionSelector.tsx, assets/js/features/projects/AccessSelectors.tsx, assets/js/features/spaces/AccessSelectors/index.tsx
related to https://github.com/operately/operately/issues/1874
=> chore: Hide public access level selection from the UI

assets/js/features/goals/GoalTree/tree/__tests__/buildTree.test.tsx, assets/js/features/goals/GoalTree/tree/buildTree.tsx, assets/js/features/goals/GoalTree/tree/node.tsx, test/support/features/profile_steps.ex
Fixes https://github.com/operately/operately/issues/1912.
=> fix: Goals tree on profile page includes complete goal lineage

ee/assets/js/admin_api/index.tsx, ee/assets/js/pages/SaasAdminPage/index.tsx, ee/lib/admin_api/queries/get_companies.ex, ee/lib/admin_api/types.ex, lib/operately/companies.ex
fixes https://github.com/operately/operately/issues/1973
New look:
=> feat: Show and sort by created at on the SaaS admin panel

assets/js/pages/SpaceDiscussionsPage/page.tsx, lib/operately/time.ex, lib/operately_web/api/queries/get_discussions.ex, test/operately_web/api/queries/get_discussions_test.exs, test/support/factory/messages.ex
fixes https://github.com/operately/operately/issues/1969
=> fix: Discussions should be listed by published date, instead of inserted_at

assets/js/features/activities/ProjectMilestoneCommented/index.tsx
fixes https://github.com/operately/operately/issues/1996
=> fix: Project milestone completed events have no associated message

assets/js/pages/DiscussionPage/page.tsx, test/support/features/discussions_steps.ex
Fixes https://github.com/operately/operately/issues/2004.
=> chore: Move the edit button outside of the dropdown on Discussion page

assets/js/features/goals/GoalForm/Form.tsx
fixes https://github.com/operately/operately/issues/2007
=> fix: Avarage -> Average typo on the goal creation page

lib/operately_email/layouts/activity.html.eex, lib/operately_email/templates.ex, lib/prosemirror2html.ex, test/prosemirror2html_test.exs, test/support/features/editor_steps.ex
fixes https://github.com/operately/operately/issues/2013
=> fix: Highlight colors in the email

assets/js/components/RichContent/Summary.tsx, assets/js/pages/LoginPage/index.tsx, config/runtime.exs, lib/operately/release.ex, rel/single-host/templates/install.sh.eex, test/features/session_test.exs, test/features/signup_test.exs, test/operately/assignments/loader_test.exs, test/support/feature_case.ex
fixes https://github.com/operately/operately/issues/2019
fixes https://github.com/operately/operately/issues/2020
=> fix: Login with email page should use allowLoginWithEmail instead of the allowLoginWithGoogle flag

assets/js/components/RichContent/Summary.tsx
I'm implementing step 1 of https://github.com/operately/operately/issues/1567:
https://github.com/user-attachments/assets/94bb7509-ee89-408f-a073-d10bb04dea84
=> feat: Display filename in the content of feed events

README.md
=> docs: Correct Discord link and license badge in Readme

assets/js/pages/DiscussionEditPage/index.tsx, package-lock.json
This pull request includes the following changes:
- added cancel link to the form mentioned in #1900 
- `package-lock.json` was updated to reflect the removal of external dependencies.
=> add cancel link to discussion edit form

lib/operately/people/account.ex, test/operately_web/controllers/account_oauth_controller_test.exs
fixes https://github.com/operately/operately/issues/2042
=> fix: Signing up with Google from the login page

assets/js/components/charts/ProgressBar.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/DesignProgressPage/index.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx
https://github.com/user-attachments/assets/70ac62d2-ab9d-423a-a371-bf6335ee8e8a
=> chore: Progress bars in Design

assets/js/components/Chronometer/index.tsx, assets/js/pages/DesignChronometerPage/index.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx
I've added the Chronometer component, which will be used on the new Goal Check-in page:
https://github.com/user-attachments/assets/1007fd3b-af9e-475f-9f15-95e5b021709a
=> chore: Chronometer component added

assets/js/pages/GoalProgressUpdatePage/AckCTA.tsx, lib/operately_email/emails/goal_check_in_commented_email.ex, lib/operately_email/emails/goal_check_in_email.ex, lib/operately_email/templates/goal_check_in.html.eex, lib/operately_email/templates/goal_check_in.text.eex, test/features/goal_progress_update_test.exs, test/support/features/goal_progress_update_steps.ex
fixes https://github.com/operately/operately/issues/467
=> chore: If you are a reviewer, you get a goal check-in message with Acknowledge CTA

assets/js/routes/pageRoute.tsx, test/features/goal_check_ins_test.exs, test/support/features/goal_check_ins_steps.ex
Un-implemented details are commented out.
=> chore: Bootstrap feature tests for new check-in page

assets/js/components/Buttons/UnstalyedButton.tsx, assets/js/components/Chronometer/index.tsx, assets/js/components/Forms/GoalTargetsField.tsx, assets/js/components/Forms/NumberInput.tsx, assets/js/components/Forms/SelectGoalStatus.tsx, assets/js/components/Forms/TimeframeField.tsx, assets/js/components/Forms/index.tsx, assets/js/components/Forms/useForm/field.tsx, assets/js/components/Forms/validations/isNumber.tsx, assets/js/components/PaperContainer/Navigation.tsx, assets/js/pages/GoalCheckInNewPage/Form.tsx, assets/js/pages/GoalCheckInNewPage/index.tsx
I've added the new Goal Check-in page (currently behind a feature flag):
https://github.com/user-attachments/assets/1fbb2c53-818d-468c-a10f-fd1707972aba
=> feat: Add new Goal Check-In page

assets/js/components/Chronometer/index.tsx
=> feat: Show ticks for completed part of the chronometer

assets/js/components/Forms/SelectGoalStatus.tsx
Now, when the goal check-in form is submitted, if the status is not selected, an error message is shown to the user.
=> fix: Add validation to SelectGoalStatus field

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/loader.tsx
The new Goal Page now also includes the goal targets field.
=> feat: Add targets field to new Goal page

assets/js/components/Pages/Page.tsx, assets/js/components/status/colors.tsx, assets/js/models/activities/index.tsx, assets/js/models/goals/index.tsx, assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/Messages.tsx, assets/js/pages/GoalV2Page/components.tsx, assets/js/pages/GoalV2Page/loader.tsx, assets/js/utils/timeframes.tsx
The new Goal Page now also includes the Goal's discussions and check-ins.
=> feat: Add messages list to new Goal Page

assets/js/pages/GoalV2Page/Form.tsx, lib/operately_web/api/serializers/goal.ex
I've added "Next Check-in" to the new Goal Page.
=> feat: Add "Next Check-in" to new Goal Page

assets/js/components/Forms/TimeframeField.tsx, assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/Messages.tsx, assets/js/pages/GoalV2Page/utils.tsx, assets/js/utils/time.tsx
I've added the timeframe field to the new Goal Page.
=> feat: Add timeframe to new Goal Page

assets/js/api/index.tsx, lib/operately/access/fetch.ex, lib/operately/goals.ex, lib/operately_web/api.ex, lib/operately_web/api/queries/list_goal_contributors.ex, test/operately_web/api/queries/list_goal_contributors_test.exs
I've added the `OperatelyWeb.Api.Queries.ListGoalContributors` query.
=> chore: Add ListGoalContributors query

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/NextCheckIn.tsx, assets/js/pages/GoalV2Page/Timeframe.tsx, assets/js/pages/GoalV2Page/contributors.tsx, assets/js/pages/GoalV2Page/loader.tsx
The new Goal Page now includes the Goal's Champion and Reviewer.
=> feat: Add champion and reviewer to new Goal Page

assets/js/api/index.tsx, assets/js/models/goals/index.tsx, assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/contributors.tsx, assets/js/pages/GoalV2Page/loader.tsx, lib/operately/goals.ex, lib/operately_web/api/queries/list_goal_contributors.ex, test/operately_web/api/queries/list_goal_contributors_test.exs
A Goal's contributors list is now also displayed on the new Goal Page.
=> feat: Add contributors to Goal Page

assets/js/pages/GoalV2Page/GoalFeed.tsx, assets/js/pages/GoalV2Page/page.tsx
I've added the feed section to the new Goal Page.
=> feat: Add feed to new Goal Page

assets/js/components/status/colors.tsx, assets/js/features/goals/GoalTree/MinimalTree.tsx, assets/js/features/goals/GoalTree/index.tsx, assets/js/features/goals/GoalTree/tree/goalNode.tsx, assets/js/features/goals/GoalTree/tree/projectNode.tsx, assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/RelatedWork.tsx, assets/js/pages/GoalV2Page/loader.tsx, assets/js/pages/GoalV2Page/page.tsx
The new Goal Page now includes a "Related Work" session.
=> feat: Add realted work to new Goal page

assets/js/pages/GoalV2Page/page.tsx
I've added a navigation to the new Goal page.
=> feat: Add navigation to new Goal page

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/Header.tsx, assets/js/pages/GoalV2Page/loader.tsx
I've added the Goal's status to the new Goal page.
=> feat: Add status to new Goal page

assets/js/components/Forms/RichTextArea.tsx, assets/js/pages/GoalV2Page/Description.tsx, assets/js/pages/GoalV2Page/NextCheckIn.tsx, assets/js/pages/GoalV2Page/ParentGoal.tsx, assets/js/pages/GoalV2Page/contributors.tsx
I've adjusted some margins and paddings on the new Goal Page.
=> fix: Adjust paddings and margins on new Goal Page

assets/js/features/goals/GoalPageHeader/index.tsx, assets/js/utils/timeframes.tsx
This feature addresses issue #596 - I have added a function to format days to weeks
=> feat: goal time in weeks

priv/repo/migrations/20250317102620_add_cycle_prevention_function_to_goals.exs, test/operately/goals/cycle_detection_test.exs
I've added a trigger which prevents the creation of cycles among goals and their parents.
=> chore: Add constraint to prevent goals cycles

assets/js/features/goals/GoalTargetsV2/TargetNameSection.tsx, assets/js/features/goals/GoalTargetsV2/TargetValue.tsx
The new `GoalTargetsField` component now adjusts to the dark theme.
=> fix: Goal Targets inputs adjust to dark theme

assets/js/layouts/CompanyLayout/index.tsx
fixes https://github.com/operately/operately/issues/2017
Probably not the most optimal solution, but it is waaay better then the current broken one.
https://github.com/user-attachments/assets/26612bda-eb3a-40f3-bff1-30a699d7f31e
I did a minimal implementation of this because without it all the effort we put into optimizing the check-in page for mobile is meaningless.
=> feat: Mobile burger navigation

assets/js/features/ResourceHub/components/DocumentMenu.tsx, assets/js/utils/markdown.ts
fixes https://github.com/operately/operately/issues/2125
fixes https://github.com/operately/operately/issues/2124
=> fix: Export as markdown when images are present

assets/js/features/richtexteditor/components/Toolbar.tsx
https://github.com/user-attachments/assets/3254673e-2091-48d0-a910-74cb7cdfdb3e
=> fix: Mobile-friendly toolbar for the rich text editor

assets/js/features/goals/GoalTargetsV2/AddTargetButton.tsx, assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/index.tsx, assets/js/features/goals/GoalTargetsV2/types.tsx, assets/js/features/goals/GoalTargetsV2/utils.tsx, assets/js/pages/GoalV2Page/useForm.tsx, assets/js/pages/GoalV2Page/utils.tsx
Targets can now be added inline on the new Goal Page.
=> feat: Targets can be added inline on the new Goal Page

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/Name.tsx, assets/js/pages/GoalV2Page/useForm.tsx
The Goal status badge is now displayed in the sidebar.
=> fix: Goal status moved to sidebar

assets/js/components/Forms/TitleInput.tsx, assets/js/components/Forms/useForm.tsx, assets/js/components/Forms/validations/presence.tsx, assets/js/pages/GoalV2Page/Name.tsx
I've added a placeholder and error handling for the Goal title.
=> fix: Add error handling Goal title

assets/js/pages/GoalV2Page/Description.tsx
On the new Goal page, the Goal description can be expanded and collapsed in the view mode.
=> feat: Goal description can be expanded and collapsed

assets/js/pages/GoalV2Page/Timeframe.tsx, assets/js/pages/GoalV2Page/utils.tsx, assets/js/utils/time.tsx
If a Goal is due, now the timeframe text is in red.
=> fix: Timeframe text is red when goal is due

assets/js/pages/GoalV2Page/Description.tsx
Goal description placeholder changed to "Add description...".
=> fix: Improve description placeholder

assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/pages/GoalV2Page/Form.tsx
A large unit no longer overflows the target container.
=> fix: Large unit doesn't overflow the target container

assets/js/features/goals/GoalTargetsV2/components/TargetNumericField.tsx
Target numeric inputs now handle NaN values.
=> fix: Target inputs handle NaN values

assets/js/features/goals/GoalTargetsV2/AddTargetButton.tsx, assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/TargetsContext.tsx
Goal targets now have a similar design in both view and edit modes.
=> chore: Targets have similar design in edit and view mode

assets/js/components/Forms/useForm.tsx, assets/js/features/goals/GoalCheckIn/useForm.tsx, assets/js/features/goals/GoalTargetsV2/AddTargetButton.tsx, assets/js/features/goals/GoalTargetsV2/TargetsContext.tsx, assets/js/features/goals/GoalTargetsV2/components/TargetNumericField.tsx, assets/js/features/goals/GoalTargetsV2/components/TargetTextField.tsx, assets/js/features/goals/GoalTargetsV2/index.tsx, assets/js/features/goals/GoalTargetsV2/targetErrors.tsx, assets/js/features/goals/GoalTargetsV2/types.tsx, assets/js/pages/GoalV2Page/useForm.tsx
Target validation now works when the form is submitted.
=> fix: Target validation when form is submitted

assets/js/features/goals/GoalTree/GoalSelector.tsx, assets/js/features/goals/GoalTree/GoalSelectorDropdown.tsx, assets/js/features/goals/GoalTree/components/CompanyGoalOption.tsx, assets/js/pages/GoalV2Page/ParentGoal.tsx
I've improved the widget for editing a Goal's parent on the new Goal page.
=> chore: Improve parent goal widget on Goal page

assets/js/features/DragAndDrop/animation.tsx, assets/js/features/DragAndDrop/dropzone.tsx, assets/js/features/DragAndDrop/index.tsx, assets/js/features/Tasks/TaskBoard.tsx, assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/TargetsContext.tsx, assets/js/features/goals/GoalTargetsV2/index.tsx, assets/js/pages/GoalV2Page/useForm.tsx
Goal targets can now be rearranged by dragging and dropping them into the desired order.
=> feat: Goal targets can be reordered by dragging and dropping

assets/js/pages/GoalV2Page/Messages.tsx, assets/js/pages/GoalV2Page/Options.tsx
Goals can now be closed and reopened from the new Goal page.
=> feat: Goal can be closed on new Goal page

lib/operately/goals/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/delete_goal.ex, test/operately_web/api/mutations/delete_goal_test.exs
I've added the `OperatelyWeb.Api.Mutations.DeleteGoal` mutation.
=> chore: Add DeleteGoal mutation

assets/js/api/index.tsx, assets/js/components/Modal/index.tsx, assets/js/models/goals/findGoalChildren.tsx, assets/js/models/goals/index.tsx, assets/js/pages/GoalV2Page/DeleteGoalModal.tsx, assets/js/pages/GoalV2Page/Options.tsx, assets/js/pages/GoalV2Page/page.tsx, lib/operately_web/api/serializers/goal_permission.ex, lib/operately_web/api/types.ex
A Goal can now be deleted from the new Goal page.
=> feat: Goal can be deleted

assets/js/pages/GoalV2Page/DeleteGoalModal.tsx, test/features/goal_test.exs, test/support/features/goal_steps.ex
I've added feature tests for deleting goals on the new Goal Page.
=> chore: Add feature tests for deleting Goal

.projections.json
I've fixed `projections.json` to work with the new monorepo.
=> fix: Fix projections.json

app/lib/operately_web/controllers/account_oauth_controller.ex, app/test/operately_web/controllers/account_oauth_controller_test.exs
This is an attempt to fix https://github.com/operately/operately/issues/2015.
=> fix: User redirected to correct path after oauth login

app/assets/js/features/auth/Buttons.tsx, app/lib/operately_web/controllers/account_oauth_controller.ex, app/test/operately_web/controllers/account_oauth_controller_test.exs
Fixes https://github.com/operately/operately/issues/2015.
=> fix: Redirect user to correct path after oauth login

design/astro.config.mjs, design/package-lock.json, design/package.json, design/src/components/WorkMap/TableRow.tsx, design/src/components/WorkMap/WorkMapTable.tsx, design/src/mockData.ts, design/src/pages/design-system.astro, design/src/pages/design-system/progress-bars.astro, design/src/pages/design-system/status-badges.astro, design/src/types/workmap.ts, design/tsconfig.json, turboui/src/ProgressBar/index.tsx, turboui/src/ProgressBar/types.ts, turboui/src/index.tsx
I've moved the `ProgressBar` component from `design` to `turboui`.
=> chore: Extract ProgressBar component to turboui

turboui/src/StatusBadge/StatusBadge.stories.tsx
I've added a storybook for the `StatusBadge` component.
=> chore: Add storybook for StatusBadge

turboui/.storybook/global.css, turboui/.storybook/main.ts, turboui/.storybook/preview.tsx, turboui/package-lock.json, turboui/package.json
fixes https://github.com/operately/operately/issues/2267
=> chore: Add a light/dark toggle to the storybook

turboui/src/Button/Button.stories.tsx, turboui/src/Button/UnstalyedButton.tsx, turboui/src/WorkMap/TableRow/ActionButtons.tsx
I've expanded the `Button` components so that they can now take an icon as a prop.
=> feat: Button can now take an icon as a prop

turboui/.storybook/main.ts, turboui/src/WorkMap/TableRow/ItemNameCell.tsx, turboui/tsconfig.json
WorkMap icons are now dark by default and turn blue on hover.
=> fix: WorkMap links are blue only when hovered

turboui/src/WorkMap/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/WorkMap.stories.tsx
In the WorkMap, items no longer have identation in the "projects" and "completed" views.  
I've also added more items to the WorkMap storybook.
=> chore: Improve WorkMap stories and identation

turboui/.storybook/main.ts, turboui/src/WorkMap/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/TableRow/ProgressCell.tsx, turboui/src/WorkMap/TableRow/SpaceCell.tsx, turboui/src/WorkMap/WorkMap.stories.tsx, turboui/src/WorkMap/WorkMapTable/TableHeader.tsx, turboui/src/WorkMap/index.tsx, turboui/src/index.tsx, turboui/tsconfig.json
I've updated the width of the WorkMap cells. Now, they have the exact same width as the cells in https://bprd.pages.dev/work-map/.
=> chore: Update width of WorkMap cells

design/src/components/Navigation/NavigationBar.astro, design/src/components/WorkMap/TableRow.tsx, design/src/mockData.ts, design/src/pages/design-system/avatars.astro, design/src/pages/design-system/progress-bars.astro, design/src/pages/design-system/status-badges.astro, design/src/types/workmap.ts
I've fixed the imports in the design app.
=> fix: Fix imports in design app

app/lib/operately/projects.ex, app/lib/operately/work_maps/get_work_map_query.ex, app/lib/operately/work_maps/work_map.ex, app/lib/operately/work_maps/work_map_item.ex, app/test/operately/work_maps/get_work_map_query_test.exs, app/test/operately/work_maps/work_map_test.exs, app/test/support/data_case.ex, app/test/support/factory/projects.ex
I'm adding a query for loading a work map tree directly from the backend.
=> feat: Add GetWorkMap query

app/assets/js/api/index.tsx, app/lib/operately_web/api.ex, app/lib/operately_web/api/queries/get_work_map.ex, app/lib/operately_web/api/serializers/work_map_item.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/queries/get_work_map_test.exs
I've added a query for fetching a work map.
=> feat: Add GetWorkMap endpoint

app/assets/js/pages/CompanyWorkMapPage/index.tsx, app/lib/operately/projects/project.ex, app/lib/operately/work_maps/get_work_map_query.ex, app/lib/operately/work_maps/work_map_item.ex, app/test/operately/work_maps/work_map_test.exs
Now, values are displayed in the `Next step` column and project's status is displayed correctly.
=> fix: Add next step to Work Map and fix project's status

app/assets/js/api/index.tsx, app/lib/operately/work_maps/work_map_item.ex, app/lib/operately_web/api/serializers/timeframe.ex, app/lib/operately_web/api/serializers/work_map_item.ex, app/lib/operately_web/api/types.ex, turboui/src/WorkMap/TableRow.stories.tsx, turboui/src/WorkMap/TableRow/DeadlineCell.tsx, turboui/src/WorkMap/TableRow/index.tsx, turboui/src/WorkMap/WorkMap.stories.tsx, turboui/src/WorkMap/WorkMapTable.stories.tsx, turboui/src/WorkMap/index.tsx, turboui/src/WorkMap/useWorkMapFilter.ts
Only the deadline for Projects was being displayed in the Work Map.
=> fix: Goal deadline is also displayed in Work Map

turboui/src/WorkMap/useWorkMapFilter.ts
Completed items are no longer shown in the "All Work" tab.
=> fix: Don't show completed items in All Work tab

turboui/src/WorkMap/useWorkMapFilter.ts
In a Work Map, root projects are no longer displayed in the "Goals Tab".
=> fix: Root projects are not displayed in the Goals Tab

turboui/src/WorkMap/WorkMapTable/index.tsx, turboui/src/WorkMap/index.tsx
The Work Map content is no longer flowing out of the page on the corners.
=> fix: Work Map also has border radius

app/assets/js/pages/CompanyWorkMapPage/index.tsx, turboui/src/WorkMap/TableRow.stories.tsx, turboui/src/WorkMap/TableRow/ChildRows.tsx, turboui/src/WorkMap/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/TableRow/context.tsx, turboui/src/WorkMap/TableRow/index.tsx, turboui/src/WorkMap/WorkMap.stories.tsx, turboui/src/WorkMap/WorkMapTable.stories.tsx, turboui/src/WorkMap/WorkMapTable/index.tsx, turboui/src/WorkMap/index.tsx
I'm removing the quick action buttons from the Work Map.
=> fix: Remove quick actions widget from Work Map

app/assets/js/api/index.tsx, app/lib/operately/work_maps/get_work_map_query.ex, app/lib/operately/work_maps/work_map_item.ex, app/lib/operately_web/api/serializers/work_map_item.ex, app/lib/operately_web/api/types.ex, turboui/src/PrivacyIndicator/index.tsx, turboui/src/WorkMap/TableRow.stories.tsx, turboui/src/WorkMap/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/WorkMap.stories.tsx, turboui/src/WorkMap/WorkMapTable.stories.tsx, turboui/src/WorkMap/index.tsx
Now, a privacy indicator icon is displayed in Work Map items.
=> feat: Add Privacy Indicator to Work Map items

turboui/src/WorkMap/components/TableRow/SpaceCell.tsx, turboui/src/WorkMap/components/WorkMapTable/TableHeader.tsx
I've reduced the space around the Space column in the Work Map.
=> fix: Reduce the Space column padding in Work Map

app/lib/operately_web/controllers/account_oauth_controller.ex, app/lib/operately_web/controllers/account_session_controller.ex
Another attempt to fix https://github.com/operately/operately/issues/2174.
=> fix: Remember logged in status when browser window is closed

app/assets/js/pages/GoalClosingPage/page.tsx, app/test/features/goal_test.exs, app/test/support/features/goal_steps.ex
Fixes https://github.com/operately/operately/issues/2213.
=> fix: Closing goal without retrospective shows error

app/assets/js/features/ResourceHub/components/CopyDocumentModal.tsx, app/assets/js/features/ResourceHub/components/DocumentMenu.tsx, app/assets/js/features/ResourceHub/index.tsx, app/assets/js/pages/ResourceHubDocumentPage/Options.tsx, app/assets/js/pages/ResourceHubDocumentPage/loader.tsx, app/assets/js/pages/ResourceHubDocumentPage/page.tsx, app/assets/js/routes/paths.tsx, app/test/features/resource_hub_document_test.exs, app/test/support/features/resource_hub_document_steps.ex
Fixes https://github.com/operately/operately/issues/2154.
=> fix: Document can be copied

app/assets/js/routes/paths.tsx, turboui/src/WorkMap/hooks/useWorkMapFilter.ts
The WorkMap selected tab is now stored in the URL.
=> feat: Persist WorkMap tab selection in URL search params

turboui/.storybook/router.tsx, turboui/src/GoalPage/index.stories.tsx, turboui/src/GoalPage/index.tsx, turboui/src/utils/storybook/storypath.tsx
Use `storyPath(category, story)` to create a link to another story.
e.g. `storyPath("Pages/GoalPage", "Default")`.
=> chore: Link up storybooks

turboui/src/StatusBadge/index.tsx, turboui/src/StatusBadge/types.ts, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/index.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/tests/mockData.ts
First time creating turboui components, looking for general feedback and any tips for maximizing the value of these components in later app integration before proceeding further.
=> feat: Bootstrap Task Board prototype

turboui/src/StatusBadge/index.tsx, turboui/src/WorkMap/components/TableRow/index.tsx
I've removed the backdrop-blur effect from the StatusBadge which was causing performance issues.
=> fix: Remove StatusBadge backdrop-blur effect to fix Work Map performance issue

turboui/src/WorkMap/hooks/useWorkMapFilter.ts, turboui/src/WorkMap/stories/WorkMap.stories.tsx
There were some mistakes in the calculation of the timeframe filter.
=> fix: Work Map wasn't filtering items by timeframe correctly

turboui/src/WorkMap/stories/WorkMapPage.stories.tsx
I've added a story for the Work Map page.
=> chore: Add story for Work Map page

app/assets/js/pages/CompanyAdminManagePeoplePage/index.tsx, app/lib/operately/operations/company_member_removing.ex, app/priv/repo/migrations/20250505212802_add_cascade_delete_to_person_and_space_members.exs, app/priv/repo/migrations/20250505213128_add_cascade_delete_to_person_and_notifications.exs, app/priv/repo/migrations/20250505213420_add_cascade_delete_to_person_and_invitations.exs, app/priv/repo/migrations/20250505213630_add_cascade_delete_to_person_and_access_group_memberships.exs, app/priv/repo/migrations/20250505213841_add_cascade_delete_to_person_and_access_groups.exs, app/priv/repo/migrations/20250505214047_add_cascade_delete_to_invitation_and_invitation_tokens.exs, app/priv/repo/migrations/20250505214231_add_cascade_delete_to_access_group_and_access_bindings.exs, app/test/features/company_admin_test.exs, app/test/features/invite_member_test.exs, app/test/support/features/company_admin_steps.ex, app/test/support/features/invite_member_steps.ex
Fixes https://github.com/operately/operately/issues/2328.
=> fix: Mark only existing company members as suspended

app/assets/js/pages/GoalV3Page/index.tsx, turboui/src/GoalPage/PageHeader.tsx, turboui/src/GoalPage/index.tsx
Name, space, navigation, timeframe, parent goal, permissions, champion and reviewer.
=> feat: Integrate basic goal information into the page

app/assets/js/pages/SpaceWorkMapPage/index.tsx, app/assets/js/pages/SpaceWorkMapPage/loader.tsx, app/assets/js/pages/SpaceWorkMapPage/page.tsx, app/assets/js/pages/index.tsx, app/assets/js/routes/index.tsx, app/assets/js/routes/paths.tsx, app/knip.json
I've added the Space Work Map behind the "space_work_map" feature flag.
=> feat: add Space Work Map

app/assets/js/pages/SpaceWorkMapPage/page.tsx, turboui/src/WorkMap/components/WorkMapNavigation.tsx, turboui/src/WorkMap/components/WorkMapTab.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/hooks/useWorkMapFilter.ts
Now, Work Map tabs can marked as hidden.
=> feat: Work Map tabs can be hidden

app/assets/js/pages/SpaceWorkMapPage/loader.tsx, app/assets/js/pages/SpaceWorkMapPage/page.tsx, app/lib/operately_web/api/serializers/work_map_item.ex, app/lib/operately_web/paths.ex
In the Work Map, the Space table cell links to the Space Work Map.
=> feat: Space cell in Work Map links to the Space Work Map

turboui/src/TaskBoard/components/MilestoneCreationModal.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/MilestoneCreationModal.stories.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/tests/mockData.ts
- modal to create milestones
- support empty milestones
- more robust drag and drop
=> feat: Create milestones on task board

app/assets/js/api/index.tsx, app/lib/operately_web/api/types.ex, app/lib/turbo_connect/api.ex, app/lib/turbo_connect/ts_gen.ex, app/lib/turbo_connect/ts_gen/typescript.ex, app/lib/turbo_connect/types.ex, app/test/turbo_connect/api_test.exs, app/test/turbo_connect/ts_gen_test.exs
fixes https://github.com/operately/operately/issues/1048
=> chore: Expose enum fields from the API

turboui/src/WorkMap/components/TableRow/ChildRows.tsx, turboui/src/WorkMap/components/TableRow/DeadlineCell.tsx, turboui/src/WorkMap/components/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/components/TableRow/index.tsx, turboui/src/WorkMap/components/WorkMapNavigation.tsx, turboui/src/WorkMap/components/WorkMapTab.tsx, turboui/src/WorkMap/components/WorkMapTable.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/hooks/useWorkMapTab.ts, turboui/src/WorkMap/stories/TableRow.stories.tsx, turboui/src/WorkMap/stories/WorkMapTable.stories.tsx, turboui/src/utils/storybook/isStorybook.ts
The Work Map tabs are now links.
=> chore: Work Map tabs are now links

turboui/src/TaskBoard/components/DueDateDisplay.tsx, turboui/src/TaskBoard/components/StatusSelector.tsx, turboui/src/TaskBoard/components/TaskItem.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/TaskItem.stories.tsx
Moved `TaskItem` into a separate file and created storybooks for it.
=> chore: Task board refactoring

.gitignore, turboui/src/TaskBoard/components/EmptyMilestoneDropZone.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/MilestoneCreationModal.tsx, turboui/src/TaskBoard/components/StatusSelector.tsx, turboui/src/TaskBoard/components/TaskCreationModal.tsx, turboui/src/TaskBoard/components/TaskItem.tsx, turboui/src/TaskBoard/components/TaskList.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/MilestoneCard.stories.tsx, turboui/src/TaskBoard/stories/MilestoneCreationModal.stories.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/stories/TaskItem.stories.tsx, turboui/src/TaskBoard/stories/TaskList.stories.tsx, turboui/src/TaskBoard/tests/mockData.ts, turboui/src/TaskBoard/types.ts, turboui/src/TaskBoard/utils/taskReorderingUtils.ts
This enables me to move on to creating a milestone page etc.
- Create modular component system from monolithic TaskBoard:
- `TaskList`: Handle task rendering with drag-and-drop support
- `EmptyMilestoneDropZone`: Provide drop target for empty milestones
- `MilestoneCard`: Display milestone with tasks and progress indicators
- Extract task reordering logic to shared utility functions
- Create reusable functions for same-list and cross-milestone reordering
- Ensure consistent behavior across all components
- Implement shared types architecture
- Create centralized `types.ts` file
- Eliminate circular dependencies
- Ensure consistent type usage across components
- Update Storybook stories for all components
- Add interactive examples with proper drag-and-drop functionality
- Demonstrate …
=> chore: Refactor Task Board component system

app/assets/js/pages/ProjectAddPage/page.tsx, app/test/features/project_creation_test.exs, app/test/support/features/project_creation_steps.ex
Fixes https://github.com/operately/operately/issues/2408.
=> fix: Creating Project without Space raises error

app/assets/js/components/PaperContainer/Section.tsx, app/assets/js/pages/CompanyAdminPage/page.tsx
fixes https://github.com/operately/operately/issues/2331
=> fix: Fix typo on company admin page

app/assets/js/pages/CompanyAdminPage/OptionsMenu.tsx, app/assets/js/pages/CompanyAdminPage/page.tsx, app/test/features/company_admin_test.exs, app/test/support/features/company_admin_steps.ex
fixes https://github.com/operately/operately/issues/2332
=> fix: Don't show menu if you are not an admin or owner

app/assets/js/api/index.tsx, app/assets/js/models/workMap/index.tsx, app/assets/js/pages/CompanyWorkMapPage/loader.tsx, app/assets/js/pages/CompanyWorkMapPage/page.tsx, app/assets/js/pages/SpaceWorkMapPage/loader.tsx, app/assets/js/pages/SpaceWorkMapPage/page.tsx, app/lib/operately_web/api/types.ex, turboui/package-lock.json, turboui/package.json, turboui/src/PrivacyIndicator/index.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/tests/mockData.ts
Work Map no longer uses zod in its types.
=> chore: Remove zod from WorkMap

turboui/src/DateDisplayField/DateDisplayField.stories.tsx, turboui/src/DateDisplayField/index.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/TaskBoard/REFACTORING_PLAN.md
Displays a prompt button → opens date picker → displays date. Putting it on the MilestonePage first and will gradually propagate it further.
=> feat: Add DateDisplayField component

app/lib/operately/work_maps/get_work_map_query.ex, app/lib/operately/work_maps/work_map.ex, app/test/operately/work_maps/get_work_map_query_test.exs
Fixes https://github.com/operately/operately/issues/2481.
=> fix: Work Map query was failing in edge cases

app/assets/js/pages/SpaceWorkMapPage/page.tsx, turboui/src/WorkMap/stories/WorkMapSpacePage.stories.tsx
Fixes https://github.com/operately/operately/issues/2482.
=> feat: Add 'All work' tab to Space Work Map

app/lib/operately/work_maps/get_work_map_query.ex
These changes should help improve performance.
https://github.com/operately/operately/issues/2483
=> chore: Load Projects and Goals in parallel for Work Map query

turboui/src/WorkMap/hooks/useWorkMapTab.ts
Projects are now sorted by their due date and goals are sorted by their duration.
=> feat: Add default sorting to Work Map

turboui/src/WorkMap/components/WorkMapNavigation.tsx
Fixes https://github.com/operately/operately/issues/2493.
=> chore: Remove Timeframe selector from Work Map

turboui/src/WorkMap/components/WorkMapNavigation.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/hooks/useWorkMapTab.ts
Now that we not longer have the timeframe selector in the Work Map, all items are displayed.
=> chore: Display all items in Work Map regardless of timeframe

turboui/src/WorkMap/components/WorkMapNavigation.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/hooks/useWorkMapTab.ts, turboui/src/WorkMap/utils/sort.tsx
Fixes https://github.com/operately/operately/issues/2520.
=> feat: Add 'paused' tab to Work Map

app/lib/operately/goals/goal.ex, app/lib/operately/work_maps/work_map_item.ex
Fixes https://github.com/operately/operately/issues/2525.
=> fix: Set the right status to old Goals

app/lib/operately/data/change_055_rename_company_space_to_general.ex, app/lib/operately/groups.ex, app/lib/operately/operations/company_adding.ex, app/priv/repo/migrations/20250522215134_rename_company_space_to_general.exs, app/test/operately/data/change_055_rename_company_space_to_general_test.exs, app/test/operately_web/api/queries/get_space_test.exs
Fixes https://github.com/operately/operately/issues/2039.
=> chore: Rename company space to 'General'

app/assets/js/features/goals/GoalForm/Form.tsx, app/assets/js/features/goals/GoalForm/useForm.tsx
Fixes https://github.com/operately/operately/issues/2521.
=> fix: Goals can be created without a Parent Goal

turboui/src/Tooltip/index.tsx, turboui/src/WorkMap/components/WorkMapTable.tsx
Fixes https://github.com/operately/operately/issues/2531.
=> feat: Show tooltip explaining 'Next step' column in Work Map

app/assets/js/pages/CompanyWorkMapPage/loader.tsx, app/assets/js/pages/CompanyWorkMapPage/page.tsx
Instead of `Company Work Map`, now the Work Map title is `{company.name} Work Map`.
=> feat: Show company name in Work Map title

app/assets/js/features/SpaceTools/GoalsAndProjects.tsx, app/assets/js/layouts/CompanyLayout/index.tsx, app/assets/js/pages/CompanyWorkMapPage/loader.tsx, app/assets/js/pages/GoalsAndProjectsPage/loader.tsx, app/assets/js/pages/SpaceGoalsPage/loader.tsx, app/assets/js/pages/SpaceWorkMapPage/loader.tsx, app/knip.json
Fixes https://github.com/operately/operately/issues/2579.
=> fix: Properly redirect users when Work Map feature is enabled

app/assets/js/pages/ProjectEditTimelinePage/MilestoneList.tsx
Fixes https://github.com/operately/operately/issues/2551.
=> fix: Fix typo in MilestoneForm

app/assets/js/pages/SpaceWorkMapPage/loader.tsx
fixed https://github.com/operately/operately/issues/2595
=> fix: Caching on the space work map

app/config/config.exs, app/lib/operately_web/api/queries/get_space.ex, app/lib/operately_web/endpoint.ex, app/lib/operately_web/logger.ex
Easier to uncover problems in development
=> chore: Compact logs

turboui/src/Page/useHtmlTitle.tsx
fixes https://github.com/operately/operately/issues/2461
=> fix: Fix turbo page titles

app/assets/js/features/goals/GoalCheckIn/Form.tsx, app/assets/js/features/goals/GoalCheckIn/StatusSelector.tsx, app/assets/js/features/goals/GoalCheckIn/useForm.tsx, app/config/test.exs, app/lib/operately/demo/goals.ex, app/lib/operately/goals/update.ex, app/lib/operately/operations/goal_check_in.ex, app/lib/operately/operations/goal_check_in_edit.ex, app/lib/operately_email/emails/goal_check_in_email.ex, app/lib/operately_web/api/mutations/edit_goal_progress_update.ex, app/lib/operately_web/api/mutations/post_goal_progress_update.ex, app/lib/operately_web/controllers/page_controller.ex, app/priv/static/.vite/manifest.json, app/test/features/goal_check_ins_test.exs, app/test/operately/data/change_037_add_space_to_goal_update_activities_test.exs, app/test/operately/operations/comment_adding_test.exs, app/test/operately/operations/goal_check_in_test.exs, app/test/operately_web/api/mutations/edit_goal_progress_update_test.exs, app/test/operately_web/api/mutations/post_goal_progress_update_test.exs, app/test/support/fixtures/goals_fixtures.ex, docker-compose.yml, turboui/src/DateDisplayField/index.stories.tsx, turboui/src/DateDisplayField/index.tsx, turboui/src/index.tsx
fixes https://github.com/operately/operately/issues/2575
fixes https://github.com/operately/operately/issues/2576
=> fix: Use due date selector for the goal check-in page

turboui/src/ProfilePage/index.tsx
Now when the "Completed" tab is selected, the "Completed On" column is displayed.
=> feat: Display 'Completed On' column in the Completed tab

app/lib/operately/work_maps/get_work_map_query.ex, app/test/operately/work_maps/get_work_map_query_test.exs, app/test/support/factory.ex, app/test/support/factory/projects.ex
Fixes https://github.com/operately/operately/issues/2612.
=> fix: Display the correct progress in the WorkMap

app/assets/js/features/goals/GoalTree/components/GoalDetails.tsx, app/assets/js/features/goals/GoalTree/components/GoalStatusCompact.tsx, app/assets/js/features/goals/GoalTree/tree/buildTree.tsx, app/assets/js/features/goals/GoalTree/tree/goalNode.tsx, app/assets/js/features/goals/GoalTree/tree/node.tsx, app/assets/js/pages/SpaceGoalsPage/loader.tsx
fixes https://github.com/operately/operately/issues/2590
=> fix: Allow null due date on the olg goal map

app/assets/js/api/index.tsx, app/assets/js/features/goals/GoalCheckIn/useForm.tsx, app/lib/operately_web/api/goals.ex, app/lib/operately_web/api/mutations/edit_goal_progress_update.ex, app/lib/operately_web/api/mutations/post_goal_progress_update.ex, app/lib/operately_web/api/queries/get_goal_check_ins.ex, app/lib/turbo_connect/fields.ex, app/lib/turbo_connect/plugs/parse_inputs.ex, app/lib/turbo_connect/plugs/required_field_validator.ex, app/test/operately_web/api/mutations/update_profile_test.exs, app/test/operately_web/api/queries/list_space_tools_test.exs, app/test/turbo_connect/api_test.exs
related to https://github.com/operately/operately/issues/2572
=> chore: Remove the required field option in favor of standard field options

turboui/src/WorkMap/components/TableRow/DueDateCell.tsx, turboui/src/WorkMap/components/TableRow/index.tsx, turboui/src/WorkMap/components/WorkMapTable.tsx, turboui/src/WorkMap/components/index.tsx
In the Work Map, the "Deadline" column was renamed to "Due Date".
=> chore: Rename 'deadline' to 'due date

app/assets/js/api/index.tsx, app/assets/js/pages/ProfileV2Page/index.tsx, app/assets/js/pages/ProfileV2Page/loader.tsx, app/lib/operately/people/permissions.ex, app/lib/operately/people/person.ex, app/lib/operately_web/api/queries/get_person.ex, app/lib/operately_web/api/serializers/person.ex, app/lib/operately_web/api/serializers/person_permissions.ex, app/lib/operately_web/api/types.ex, turboui/src/ProfilePage/index.tsx
I've added to the new profile page an option to edit a person.
=> feat: Add editing-person option to new Profile page

turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/PersonField/index.stories.tsx, turboui/src/PersonField/index.tsx, turboui/src/TaskBoard/components/DueDateDisplay.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/TaskItem.tsx, turboui/src/TaskBoard/components/TaskList.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/stories/TaskItem.stories.tsx, turboui/src/TaskBoard/stories/TaskList.stories.tsx
- moved due date and assignee to the right
- assignee widget always present with placeholder if none
- can navigate assignee list with keyboard
- extended PersonField to avatar-only variation to support this
- refactored a little bit to make TaskItem self-contained
=> feat: Assignee selection in TaskItem

turboui/src/WorkMap/hooks/useWorkMapTab.ts
I've changed the paused icon in the Work Map.
=> chore: Change paused icon in Work Map

turboui/src/Avatar/AvatarWithName.tsx, turboui/src/Avatar/types.ts, turboui/src/PersonCard/index.tsx, turboui/src/ProfilePage/components/Colleagues.tsx
The "about" tab on the the new Profile page now looks good on mobile too.
=> chore: About tab on new Profile page looks good in mobile

turboui/CLAUDE.md
Should help streamline work when using Claude Code.
=> chore: Add turboui/CLAUDE.md

turboui/src/WorkMap/components/TableRow/ProgressCell.tsx, turboui/src/WorkMap/components/WorkMapTable.tsx
This is an attempt to improve the empty space between columns in the Work Map.
=> chore: Improve space between columns in the Work Map

app/assets/js/layouts/CompanyLayout/index.tsx
I've added the new navigation behind a feature flag to to mobile, too.
=> feat: Add new navigation to mobile behind feature flag

turboui/src/TaskBoard/components/StatusSelector.tsx, turboui/src/TaskBoard/stories/StatusSelector.stories.tsx, turboui/src/TaskPage/PageHeader.tsx, turboui/src/TaskPage/index.tsx, turboui/tailwind.config.js
=> feat: Clear status on task page

turboui/src/CommentSection/ActivityComponents.tsx, turboui/src/CommentSection/COMMENT_TURBOUI_PLAN.md, turboui/src/CommentSection/CommentInput.tsx, turboui/src/CommentSection/CommentItem.tsx, turboui/src/CommentSection/CommentSection.tsx, turboui/src/CommentSection/index.stories.tsx, turboui/src/CommentSection/index.tsx, turboui/src/CommentSection/types.ts, turboui/src/MilestoneField/index.stories.tsx, turboui/src/TaskPage/Overview.tsx, turboui/src/TaskPage/index.stories.tsx, turboui/src/TaskPage/index.tsx, turboui/src/Timeline/TaskActivities.tsx, turboui/src/Timeline/Timeline.tsx, turboui/src/Timeline/TimelineItem.tsx, turboui/src/Timeline/index.stories.tsx, turboui/src/Timeline/index.tsx, turboui/src/Timeline/types.ts, turboui/src/index.tsx
- created CommentSection and Timeline components in turboui
- applied to TaskPage
- this is still a rough version - first time we mix comments and activity - will need to work on fine tuning details
=> feat: Bootstrap comments & activity section on the task page

Makefile, devenv
fixes https://github.com/operately/operately/issues/2358
=> chore: Silence annoying output on dev.build

turboui/src/DateField/index.tsx
Re-adding negative margins to align it with the label.
=> fix: Visual regression for due date field

turboui/src/PrivacyField/index.tsx
first steps for https://github.com/operately/operately/issues/2722
If the access levels are invalid, log them on sentry for faster discovery.
=> chore: Log invalid access levels

app/lib/operately_web/api/goals.ex, app/test/operately_web/api/goals_test.exs
If you don't change the space, take no action in the DB.
=> feat: Idempotent space change

app/assets/js/models/goals/index.tsx
fixes https://github.com/operately/operately/issues/2722
Adding to the issue list that it needs some more robust tests on the backend/DB.
=> fix: Hotfix for goal access levels

app/test/features/profile_test.exs, app/test/support/features/profile_steps.ex
I've added some feature tests for the new Profile page.
=> chore: Add feature tests for profile page

turboui/src/Colors/Colors.stories.tsx
=> chore: Add Colors page to storybook

turboui/src/GoalPage/PageHeader.tsx, turboui/src/ProjectPage/PageHeader.tsx, turboui/src/TaskPage/PageHeader.tsx, turboui/src/TextField/index.stories.tsx, turboui/src/TextField/index.tsx
For consistency with other fields.
=> chore: Rename EditableText -> TextField

turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/TaskFilter.tsx, turboui/src/TaskBoard/components/index.tsx
- Milestones don't disappear but stay empty when task filters apply
- plus two visual tweaks (see commits)
=> fix: Filtering milestone behavior

turboui/src/CommentSection/ActivityComponents.tsx, turboui/src/CommentSection/types.ts, turboui/src/GoalTargetList/useGoalTargetListState.tsx, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/MilestonePage/mockData.ts, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/types.ts, turboui/src/Timeline/TaskActivities.tsx, turboui/src/Timeline/TimelineItem.tsx, turboui/src/Timeline/types.ts, turboui/src/utils/DragAndDrop/context.tsx, turboui/src/utils/DragAndDrop/draggable.tsx, turboui/src/utils/DragAndDrop/dropzone.tsx
- Added status badge to header
- Made header sticky
- Removed floating 'Milestones' link
- Made status buttons in sidebar work
- Extended timeline examples
- Fixed drag and drop of tasks
=> feat: MilestonePage design improvements

app/assets/js/api/index.tsx, app/lib/operately_web/api/types.ex, turboui/src/MiniWorkMap/MiniWorkMap.stories.tsx, turboui/src/MiniWorkMap/index.tsx, turboui/src/StatusBadge/StatusBadge.stories.tsx, turboui/src/StatusBadge/index.tsx, turboui/src/StatusBadge/types.ts, turboui/src/WorkMap/components/TableRow/DueDateCell.tsx, turboui/src/WorkMap/components/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/components/TableRow/NextStepCell.tsx, turboui/src/WorkMap/components/TableRow/OwnerCell.tsx, turboui/src/WorkMap/components/TableRow/SpaceCell.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/hooks/useItemStatus.ts, turboui/src/WorkMap/stories/TableRow.stories.tsx, turboui/src/WorkMap/tests/mockData.ts
I'm working on https://github.com/operately/operately/issues/2709.
The status badge now works with the new statuses.
=> chore: Update Status Badge to handle new statuses

turboui/src/GoalPage/Sidebar.tsx, turboui/src/LastCheckIn/index.tsx, turboui/src/ProjectPage/OverviewSidebar.tsx, turboui/src/ProjectPage/index.stories.tsx, turboui/src/ProjectPage/index.tsx
previously was within GoalPage, now shared to appear in project page as well
=> chore: Refactor LastCheckIn as a shared component between project and goal pages

turboui/src/Button/Button.stories.tsx, turboui/src/Button/calcClassNames.tsx, turboui/src/Button/index.tsx
=> feat: Square Buttons

turboui/src/Button/index.tsx, turboui/src/Colors/Colors.stories.tsx
=> feat: Buttons in brand blue color

turboui/src/GoalPage/Sidebar.tsx
=> feat: Add tooltips to explain Champion and Reviewer goals in Goal page

app/assets/js/api/index.tsx, app/assets/js/features/activities/GoalClosing/index.tsx, app/lib/operately/activities/content/goal_closing.ex, app/lib/operately/activities/notifications/goal_closing.ex, app/lib/operately/data/change_064_set_goal_closing_activity_success_status.ex, app/lib/operately/operations/goal_closing.ex, app/lib/operately_web/api/serializers/activity.ex, app/lib/operately_web/api/serializers/activity_content/goal_closing.ex, app/lib/operately_web/api/types.ex, app/priv/repo/migrations/20250707134812_add_success_status_field_to_existing_goal_closed_activities.exs, app/test/operately/access/activity_context_assigner_test.exs, app/test/operately/data/change_064_set_goal_closing_activity_success_status_test.exs
Now, the StatusBadge component is used both on the Goal Retrospective page and in the GoalClosing activity.
=> feat: Add 'Missed' and 'Achieved' badges to Goal retrospective page

turboui/src/LastCheckIn/index.tsx, turboui/src/ProgressBar/ProgressBar.stories.tsx, turboui/src/ProgressBar/index.tsx, turboui/src/ProgressBar/types.ts
I've removed legacy statuses from the ProgressBar component.
=> chore: Remove legacy status from Progress Bar

app/assets/js/features/goals/GoalCheckIn/Form.tsx, app/lib/operately_email/emails/goal_check_in_email.ex
I'm adjusting the Goal Check-in copy as described in https://github.com/operately/operately/issues/2709.
=> chore: Adjust Goal Check-in email and page copy

app/lib/operately_email/emails/project_check_in_submitted_email.ex, app/lib/operately_email/templates/project_check_in_submitted.html.eex
I've improved the Project Check-in email copy as described in https://github.com/operately/operately/issues/2709.
=> feat: Improve Project Check-in email copy

Makefile, app/assets/js/window.d.ts, app/config/runtime.exs, app/ee/assets/js/pages/SaasAdminPage/index.tsx, app/lib/operately_web/controllers/page_controller.ex
I've added the release version to the application.
=> chore: Add release version to application

turboui/src/DatePicker/components/DateTypeSelector.tsx, turboui/src/DatePicker/components/InlineCalendar.tsx, turboui/src/DatePicker/components/MonthSelector.tsx, turboui/src/DatePicker/components/OptionButton.tsx, turboui/src/DatePicker/components/QuarterSelector.tsx, turboui/src/DatePicker/components/YearSelector.tsx
Now, the Date Picker component looks good in both Light and Dark themes.
=> chore: Date Picker looks good in both light and dark themes

turboui/src/DatePicker/components/InlineCalendar.tsx, turboui/src/DatePicker/components/MonthSelector.tsx, turboui/src/DatePicker/components/QuarterSelector.tsx, turboui/src/DatePicker/components/YearSelector.tsx, turboui/src/DatePicker/index.tsx, turboui/src/DatePicker/types.ts
The DatePicker component now is a popover which has a trigger and content.
=> feat: Add popover to DatePicker

app/assets/js/api/index.tsx, app/lib/operately/goals/timeframe.ex, app/lib/operately/operations/goal_check_in.ex, app/lib/operately/operations/goal_check_in_edit.ex, app/lib/operately_web/api/goals.ex, app/lib/operately_web/api/serializers/contextual_date.ex, app/lib/operately_web/api/serializers/goal_timeframe.ex, app/lib/operately_web/api/types.ex, app/test/support/fixtures/goals_fixtures.ex
The Goal Timeframe now includes contextual dates.
=> chore: Add contextual dates to Goal timeframe

app/assets/js/features/goals/GoalCheckIn/StatusSelector.tsx
Fixes https://github.com/operately/operately/issues/2852.
=> fix: Improve reviewer validation on Goal Check-in page to handle empty reviewer

turboui/src/DatePicker/index.tsx
Now, DatePicker can be used to remove a date.
=> feat: Add to DatePicker option to clear date

turboui/src/DatePicker/components/InlineCalendar.tsx, turboui/src/DatePicker/components/MonthSelector.tsx, turboui/src/DatePicker/components/OptionButton.tsx, turboui/src/DatePicker/components/QuarterSelector.tsx, turboui/src/DatePicker/components/YearSelector.tsx
Now, the current day, month, quarter or year is highlighted.
=> feat: Highlight current day/month/quarter/year in DatePicker

app/lib/operately/contextual_dates/contextual_date.ex, app/lib/operately/demo/goals.ex
The demo now creates Goals with contextual dates as deadlines.
=> chore: Adjust demo to create contextual dates for Goals

app/lib/operately/data/change_066_update_timeframe_in_goal_activities/goal_check_in_edit.ex, app/lib/operately/operations/goal_check_in_edit.ex, app/priv/repo/migrations/20250722155732_update_timeframes_in_goal_check_in_edit_activities.exs, app/test/operately/data/change_066_update_timeframe_in_goal_activities/goal_check_in_edit_test.exs
I've a migration to update the timeframes in the existing GoalCheckInEdit activities.
=> chore: Update timeframes in GoalCheckInEdit activity

app/lib/operately/data/change_066_update_timeframe_in_goal_activities/goal_created.ex, app/priv/repo/migrations/20250723105434_update_timeframes_in_goal_created_activities.exs, app/test/operately/data/change_066_update_timeframe_in_goal_activities/goal_created_test.exs
I've added a migration to update the timeframes in the existing GoalCreated activities.
=> chore: Update timeframes in GoalCreated activity

app/lib/operately/activities/content/goal_check_in.ex, app/lib/operately/activities/content/goal_check_in_edit.ex, app/lib/operately/activities/content/goal_created.ex, app/lib/operately/activities/content/goal_editing.ex, app/lib/operately/activities/content/goal_timeframe_editing.ex, app/lib/operately/contextual_dates/timeframe.ex, app/lib/operately/goals/goal.ex, app/lib/operately/goals/update.ex, app/lib/operately_email/emails/goal_check_in_email.ex, app/lib/operately_web/api/goals.ex, app/lib/operately_web/api/serializers/goal_timeframe.ex, app/lib/operately_web/api/serializers/work_map_item.ex, app/test/operately/assignments/loader_test.exs, app/test/operately/data/change_028_create_subscriptions_list_for_goal_updates_test.exs, app/test/operately/data/change_052_populate_goal_update_timeframes_test.exs, app/test/operately/goals/timeframe_test.exs, app/test/operately_web/api/mutations/create_goal_test.exs, app/test/support/factory/goals.ex, app/test/support/features/project_steps.ex, app/test/support/fixtures/goals_fixtures.ex
I've moved the Timeframe struct from Goals to ContextualDates as I intend to use the same Timeframe with other resources.
=> chore: Move Timeframe from Goals to ContextualDates directory

app/lib/operately/data/change_067_populate_project_timeframe.ex, app/priv/repo/migrations/20250725101046_populate_project_timeframe_with_deadline_and_started_at.exs, app/test/operately/data/change_067_populate_project_timeframe_test.exs
I've added a migration to populate existing projects timeline.
=> chore: Add migration to populate projects timeline

turboui/src/DateField/index.stories.tsx, turboui/src/DateField/index.tsx
I've added a `lg` size option to the DateField component.
=> feat: Add lg option to DateField

app/assets/js/features/activities/GoalEditing/index.tsx, app/assets/js/utils/timeframes.tsx
Fixes https://operately.sentry.io/issues/6774928730/?project=4506139375239168.
=> fix: Handle undefined timeframes in GoalEditing activities

app/lib/operately/projects/edit_timeline_operation.ex, app/lib/operately/projects/milestone.ex, app/lib/operately_web/api/mutations/update_milestone.ex, app/priv/repo/migrations/20250729090229_add_timeframe_field_to_project_milestone_schema.exs
I've added the `timeframe` to the Project Milestones schema.
=> chore: Add timeframe field to Project Milestones

app/lib/operately/data/change_069_populate_project_milestones_timeframe.ex, app/lib/operately/projects.ex, app/lib/operately/projects/edit_timeline_operation.ex, app/priv/repo/migrations/20250729102831_populate_existing_project_milestones_timeframe.exs, app/test/operately/data/change_069_populate_project_milestones_timeframe_test.exs, app/test/support/factory/projects.ex
I've added a migration to populate existing Project Milestones timeframe.
=> chore: Add migration to populate existing Milestones timeframe

turboui/src/RichEditor/Blob/DropFilePlugin.tsx, turboui/src/RichEditor/Blob/PasteFilePlugin.tsx, turboui/src/RichEditor/Blob/index.tsx
=> fix: Fix plugin reload in HMR context

turboui/src/Checklist/index.stories.tsx, turboui/src/Checklist/index.tsx, turboui/src/Checklist/useChecklistState.tsx
=> feat: Create Checklist component

app/assets/js/pages/GoalPage/index.tsx, turboui/src/Checklist/index.stories.tsx, turboui/src/Checklist/index.tsx, turboui/src/GoalPage/Checklists.tsx, turboui/src/GoalPage/Overview.tsx, turboui/src/GoalPage/Targets.tsx, turboui/src/GoalPage/index.stories.tsx, turboui/src/GoalPage/index.tsx
There's a 'feature flag' parameter so it doesn't leak into production.
=> feat: Integrate Checklist into GoalPage.

app/assets/js/api/index.tsx, app/assets/js/features/activities/ProjectChampionUpdating/index.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/project_champion_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/project_champion_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/activity_content/project_champion_updating.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs
Now the Project champion can be edited on the new Project page.
=> feat: Champion can be edited on Project V2 page

app/assets/js/api/index.tsx, app/assets/js/features/activities/ProjectReviewerUpdating/index.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/project_reviewer_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/project_reviewer_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/activity_content/project_reviewer_updating.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs
Now the Project reviewer can be edited on the new Project page.
=> feat: Reviewer can be edited on Project V2 page

app/ee/assets/js/pages/SaasAdminPage/index.tsx
so we don't need to count number of orgs created by hand
=> chore: Add index to saas admin org table

app/assets/js/api/index.tsx, app/assets/js/features/SpaceTools/GoalsAndProjects.tsx, app/assets/js/features/SpaceTools/GoalsAndProjects/AllDoneState.tsx, app/assets/js/models/projects/index.tsx, app/assets/js/pages/ProjectPage/Banner.tsx, app/assets/js/pages/ProjectPage/TimelineSection.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/projects/check_in.ex, app/lib/operately/projects/project.ex, app/lib/operately_web/api/serializers/project.ex, app/lib/operately_web/api/types.ex, app/test/support/factory/projects.ex
Now the correct status is displayed on the new Project page.
=> fix: Display correct status on Project V2 page

turboui/src/DateField/components/MonthSelector.tsx, turboui/src/DateField/components/QuarterSelector.tsx, turboui/src/DateField/components/YearSelector.tsx, turboui/src/DateField/index.tsx, turboui/src/DateField/utils.ts
I've fixed a timezone related issue with the useStartOfPeriod prop in the DateField component.
=> fix: Fix useStartOfPeriod prop in DateField component

app/assets/js/components/Editor/Blob/index.tsx, app/assets/js/components/Editor/index.tsx, turboui/src/RichEditor/Blob/AddBlobsEditorCommand.tsx, turboui/src/RichEditor/Blob/DropFilePlugin.tsx, turboui/src/RichEditor/Blob/PasteFilePlugin.tsx, turboui/src/RichEditor/Blob/index.tsx, turboui/src/RichEditor/components/AttachmentButton.tsx, turboui/src/RichEditor/useEditor.tsx, turboui/src/index.tsx
I've fixed the drag-and-drop and copy-and-paste Rich Text plugins.
=> fix: Fix rich text drag-and-drop and copy-and-paste plugins

turboui/src/ProjectPage/index.tsx
I've added the activities tab to the new Project page.
=> feat: Add activities tab to Project V2 page

app/assets/js/api/index.tsx, app/assets/js/features/activities/ProjectMilestoneCreation/index.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/project_milestone_creation.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/project_milestone_creation.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/activity_content/project_milestone_creation.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs, turboui/src/ProjectPage/Overview.tsx, turboui/src/ProjectPage/index.stories.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/MilestoneCreationModal.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/MilestoneCreationModal.stories.tsx, turboui/src/TaskBoard/types.ts
Milestones can now be created from the new Project page.
=> feat: Milestones can be created from Project V2 page

app/assets/js/api/index.tsx, app/assets/js/features/activities/ProjectMilestoneUpdating/index.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/project_milestone_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/project_milestone_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/activity_content/project_milestone_updating.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/ProjectPage/MilestoneItem.tsx, turboui/src/ProjectPage/Overview.tsx, turboui/src/ProjectPage/index.stories.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/stories/MilestoneCard.stories.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/types.ts
Milestones can now be edited from the new Project page.
=> feat: Milestones can be edited on Project V2 page

turboui/src/ProjectPage/MilestoneItem.tsx
The Milestone's due date is now displayed using the DateField component, which ensures it's always displayed in the correct format.
=> fix: Display Milestone's due date correctly

app/assets/js/features/activities/ProjectMilestoneUpdating/index.tsx
The dates were not being shown correctly in the MilestoneUpdating activity. Now we are using the DateField component to display them.
=> fix: Use DateField to display correct dates in MilestoneUpdating acitiviy

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately_web/api/mutations/remove_key_resource.ex, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/ResourceLink/index.tsx, turboui/src/ResourceManager/index.tsx
Resources can now be deleted from the new Project page.
=> feat: Resources can be deleted from Project V2 page

turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/types.ts
This was meant to be a placeholder for where this control be in the future but it's now leaking into prod so let's just remove it.
=> chore: Remove mock kanban/table TaskBoard switcher

turboui/src/ProjectPage/MilestoneItem.tsx, turboui/src/ProjectPage/Overview.tsx
fixes https://github.com/operately/operately/issues/3067
=> fix: Milestone input colors

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/projects.ex, app/lib/operately/projects/permissions.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/project_permissions.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs, app/test/support/factory/projects.ex, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/ProjectPage/DeleteModal.tsx, turboui/src/ProjectPage/OverviewSidebar.tsx, turboui/src/ProjectPage/PageHeader.tsx, turboui/src/ProjectPage/index.stories.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/TaskPage/InProjectContextStory.tsx
Projects can now be deleted from the new Project page.
=> feat: Projects can be deleted

turboui/src/Conversations/Conversations.stories.tsx, turboui/src/Conversations/ConversationsExample.tsx, turboui/src/Conversations/index.tsx, turboui/src/Conversations/useConversations.ts, turboui/src/icons/index.tsx
=> feat: Design pre-defined actions and responses in Conversation UI

app/assets/js/api/index.tsx, app/lib/operately/activities/content/task_adding.ex, app/lib/operately/operations/task_adding.ex, app/lib/operately/repo/getter.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/types.ex, app/test/operately/access/activity_context_assigner_test.exs, app/test/operately_web/api/projects_test.exs
I've added a mutation for creating Tasks to the projects API.
=> chore: Add CreateTask mutation

app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately_web/api/projects.ex, turboui/src/MilestonePage/index.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/TaskCreationModal.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/TaskCreationModal.stories.tsx
We can now create Tasks with an assignee from the Project page.
=> feat: Tasks can be created with assignees

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/task_due_date_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/task_due_date_updating.ex, app/lib/operately/tasks/task.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/test/operately_web/api/projects_test.exs, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/TaskItem.tsx, turboui/src/TaskBoard/components/TaskList.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/types.ts
We can now update Tasks due date from the new Project page.
=> feat: Tasks due date can be updated

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/task_assignee_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/task_assignee_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/test/operately_web/api/projects_test.exs, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/MilestoneCard.tsx, turboui/src/TaskBoard/components/TaskItem.tsx, turboui/src/TaskBoard/components/TaskList.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/types.ts
We can now update Tasks assignee from the new Project page.
=> feat: Tasks assignee can be updated

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/task_milestone_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/task_milestone_updating.ex, app/lib/operately/tasks.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/test/operately_web/api/projects_test.exs, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/types.ts
We can now update a Task milestone from the new Project page.
=> feat: Tasks milestone can be updated

app/assets/js/api/index.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/assets/js/pages/index.tsx, app/assets/js/routes/index.tsx, app/lib/operately_web/api/queries/get_task.ex, app/lib/operately_web/api/serializers/task.ex, app/lib/operately_web/api/types.ex, turboui/src/TaskPage/InProjectContextStory.tsx, turboui/src/TaskPage/PageHeader.tsx, turboui/src/TaskPage/index.stories.tsx, turboui/src/TaskPage/index.tsx, turboui/src/index.tsx
=> feat: Add Task v2 page

app/assets/js/api/index.tsx, app/assets/js/models/projectContributors/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/test/operately_web/api/projects_test.exs, turboui/src/TaskBoard/components/TaskList.tsx
Fixes https://github.com/operately/operately/issues/3120.
=> fix: Only people who are contributing to Project are listed on Project page

app/assets/js/pages/ProjectV2Page/index.tsx, turboui/src/ProjectPage/index.tsx
Fixes https://github.com/operately/operately/issues/3123.
=> fix: New Tasks are successfully updated

app/assets/js/pages/ProjectV2Page/index.tsx
Fixes https://github.com/operately/operately/issues/3113.
=> fix: Display contributor's responsibility on Project page

app/assets/js/api/index.tsx, app/assets/js/features/activities/TaskDescriptionChange/index.tsx, app/assets/js/features/activities/feedItemLinks.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/lib/operately/activities/content/task_description_change.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/data/change_075_enhance_task_description_change_activities.ex, app/lib/operately/operations/task_description_change.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/project_tasks.ex, app/lib/operately_web/api/serializers/activity.ex, app/lib/operately_web/api/serializers/activity_content/task_description_change.ex, app/lib/operately_web/api/types.ex, app/priv/repo/migrations/20250819111215_add_project_id_and_project_name_and_task_name_to_change_task_description_activity.exs, app/test/operately/access/activity_context_assigner_test.exs, app/test/operately/data/change_075_enhance_task_description_change_activities_test.exs, app/test/operately_web/api/project_tasks_test.exs
We can now edit a Task's description from the new Task page.
=> feat: Task description can be edited from the Task V2 page

app/assets/js/api/index.tsx, app/assets/js/features/activities/TaskNameUpdating/index.tsx, app/assets/js/features/activities/feedItemLinks.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/lib/operately/activities/content/task_name_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/task_name_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/project_tasks.ex, app/lib/operately_web/api/serializers/activity_content/task_name_updating.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/project_tasks_test.exs
A Task name can now be edited from the new Task page.
=> feat: Task name can be edited

app/assets/js/api/index.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/lib/operately_web/api.ex, app/lib/operately_web/api/project_tasks.ex, app/test/operately_web/api/project_tasks_test.exs, app/test/support/factory/projects.ex, turboui/src/TaskPage/index.tsx
Tasks count is now displayed on the new Tasks page.
=> feat: Display tasks count on new Task page

app/assets/js/components/Forms/TitleInput.tsx
I merged the previous PR too fast. I thought that only the PR name was wrongm, but it seems that there was also a small linting issue but the PR name issue masked it.
=> chore: Fix linting issue

turboui/src/TaskBoard/components/index.tsx
Milestones are now sorted on the TasksBoard.
=> fix: Fix milestones sorting on the TasksBoard

app/assets/js/pages/TaskV2Page/index.tsx, app/assets/js/routes/PageCache.tsx
When we make changes to a Task, the Task feed is refreshed.
=> feat: Task feed is refreshed when there are changes

app/assets/js/api/index.tsx, app/assets/js/models/comments/index.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/lib/operately_web/api/queries/get_comments.ex, app/lib/operately_web/api/types.ex
Comments are now displayed on the new Task page.
=> feat: Comments are listed on Task V2 page

app/assets/js/pages/TaskV2Page/index.tsx, turboui/src/CommentSection/CommentInput.tsx, turboui/src/CommentSection/types.ts, turboui/src/RichEditor/index.tsx, turboui/src/TaskPage/Overview.tsx, turboui/src/Timeline/Timeline.tsx, turboui/src/Timeline/types.ts
It turned out that the new Comments in turboui were not using Tiptap.
=> fix: Use Tiptap instead of textarea for comments

turboui/src/TaskBoard/components/TaskCreationModal.tsx
=> chore: Add more breathing room to the TaskCreationModal

app/assets/js/models/people/index.tsx, app/assets/js/models/people/useMentionedPersonSearch.tsx, app/assets/js/pages/TaskV2Page/index.tsx, turboui/src/RichEditor/extensions/MentionPeople/index.tsx, turboui/src/TaskPage/Description.tsx, turboui/src/TaskPage/InProjectContextStory.tsx, turboui/src/TaskPage/Overview.tsx, turboui/src/TaskPage/index.stories.tsx, turboui/src/TaskPage/index.tsx
I've enabled mentioning people in rich text on the new Task page.
=> feat: Enable mentioning people on Task page

app/assets/js/api/index.tsx, app/assets/js/hooks/index.ts, app/assets/js/hooks/usePageField.ts, app/assets/js/pages/MilestoneV2Page/index.tsx, app/assets/js/pages/ProjectMilestonePage/loader.tsx, app/assets/js/pages/index.tsx, app/assets/js/routes/index.tsx, app/assets/js/routes/paths.tsx, app/lib/operately/projects/milestone.ex, app/lib/operately_web/api/queries/get_milestone.ex, app/lib/operately_web/api/serializers/milestone.ex, app/lib/operately_web/api/types.ex, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/components/Description.tsx, turboui/src/MilestonePage/components/Sidebar.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/RichContent/index.tsx, turboui/src/index.tsx
The Milestone V2 page is now accessible behind the "milestone_v2" feature flag.
=> feat: Add Milestone V2 page behind FF

app/assets/js/pages/MilestoneV2Page/index.tsx, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/components/Description.tsx, turboui/src/MilestonePage/index.tsx
The new Milestone page now supports mentions.
=> feat: New Milestone page supports mentioning people

turboui/src/MilestonePage/components/Sidebar.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/MilestonePage/mockData.ts, turboui/src/utils/storybook/genPeople.tsx
Clicking on the Milestone creator now correctly redirects to the creator's page.
=> fix: Fix creator link on Milestone V2 page

app/assets/js/api/index.tsx, app/assets/js/models/milestones/index.tsx, app/assets/js/pages/MilestoneV2Page/index.tsx, app/lib/operately/comments/milestone_comment.ex, app/lib/operately_web/api/types.ex, turboui/src/CommentSection/CommentSection.tsx, turboui/src/CommentSection/types.ts, turboui/src/MilestonePage/InProjectContextStory.tsx, turboui/src/MilestonePage/MilestonePage.stories.tsx, turboui/src/MilestonePage/index.tsx, turboui/src/TaskPage/mockData.ts
Comments are now displayed on the new Milestone page.
=> feat: Display comments on Milestone V2 page

turboui/src/GoalPage/Sidebar.tsx, turboui/src/MilestoneField/index.tsx, turboui/src/MilestonePage/components/Sidebar.tsx, turboui/src/PersonField/index.tsx, turboui/src/ProjectPage/OverviewSidebar.tsx, turboui/src/SidebarSection/index.tsx, turboui/src/TaskBoard/components/StatusSelector.tsx, turboui/src/TaskPage/PageHeader.tsx, turboui/src/TaskPage/Sidebar.tsx
see each commit title for change notes
=> feat: Responsive tasks, part 2

app/lib/operately/md/project.ex, app/test/operately/md/project_test.exs
fixes: https://github.com/operately/operately/issues/3156
also resolves this problem in proejcts https://github.com/operately/operately/issues/3158
=> feat: Renders timestamp data in project markdown files

app/lib/operately/md/goal.ex, app/lib/operately/md/goal/check_ins.ex, app/lib/operately/md/goal/discussions.ex, app/test/operately/md/goal_test.exs
Addressed this partially: https://github.com/operately/operately/issues/3157
fixes this: https://github.com/operately/operately/issues/3158
=> feat: Goal markdown improvements

app/lib/operately/md/goal/checklist.ex, app/test/operately/md/goal_test.exs
related https://github.com/operately/operately/issues/3157
=> feat: Show completed at for markdownized goal checks

.semaphore/deploy.yml, .semaphore/semaphore.yml, scripts/deploy.rb
Reverts operately/operately#3506
=> Revert "chore: Move production deployment to Superplane"

AGENTS.md
Reverts operately/operately#3508
=> Revert "Dummy to trigger deployment"

app/lib/operately/data/change_080_create_subscriptions_list_for_tasks.ex, app/lib/operately/notifications/subscription_list.ex, app/lib/operately/operations/task_adding.ex, app/lib/operately/tasks/task.ex, app/lib/operately_web/api/project_tasks.ex, app/priv/repo/migrations/20250929131526_add_subscription_list_to_project_tasks.exs, app/priv/repo/migrations/20250929141239_populate_existing_project_tasks_with_subscription_list.exs, app/test/operately/data/change_080_create_subscriptions_list_for_tasks_test.exs, app/test/support/factory/utils.ex, app/test/support/fixtures/tasks_fixtures.ex
I'm adding a relationship between  SubscriptionList and Task.
=> chore: Add subscription_list to Tasks

app/lib/operately/activities/notifications/project_task_commented.ex, app/lib/operately/operations/comment_adding/subscriptions.ex, app/lib/operately/operations/comment_editing/subscriptions.ex, app/lib/operately/tasks/notifications.ex, app/lib/operately_email/emails/project_task_commented_email.ex, app/lib/operately_email/templates/project_task_commented.html.eex, app/lib/operately_email/templates/project_task_commented.text.eex, app/lib/operately_web/paths.ex, app/test/operately/operations/comment_adding_test.exs
Commenting on a Task now notifies the creator, the assignee and mentioned people. 
https://github.com/operately/operately/issues/3401
=> feat: Commenting on Tasks sends notifications

app/lib/operately/activities/notifications/project_task_commented.ex, app/lib/operately/activities/notifications/task_due_date_updating.ex, app/lib/operately_email/emails/task_due_date_updating_email.ex, app/lib/operately_email/templates/task_due_date_updating.html.eex, app/lib/operately_email/templates/task_due_date_updating.text.eex, app/test/features/project_tasks_test.exs, app/test/operately_web/api/project_tasks_test.exs, app/test/support/features/project_tasks_steps.ex, app/test/support/features/ui.ex
Changing the due date for a Task now notifies the assignee.
https://github.com/operately/operately/issues/3401
=> feat: Changing Task due date sends notifications

app/lib/operately/invite_links.ex, app/lib/operately/people.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/invitations.ex, app/lib/operately_web/api/mutations/create_account.ex, app/lib/operately_web/controllers/account_oauth_controller.ex, app/priv/static/.vite/manifest.json, app/test/features/invite_links_test.exs, app/test/operately/invite_links_test.exs, app/test/operately_web/api/invitations_test.exs, app/test/support/factory.ex, app/test/support/factory/accounts.ex, app/test/support/factory/companies.ex, app/test/support/features/invite_links_steps.ex
fixes https://github.com/operately/operately/issues/3573
=> fix: If the account is already member of the organization, just pass them in

turboui/src/InviteLinkJoinPage/index.tsx
fixes https://github.com/operately/operately/issues/3569
=> fix: Join button should be primary

app/lib/operately/invite_links.ex, app/lib/operately/operations/company_member_adding.ex, app/lib/operately/people.ex, app/test/features/invite_links_test.exs, app/test/support/features/invite_links_steps.ex
fixes https://github.com/operately/operately/issues/3570
=> fix: Join general after joining company

app/lib/operately/companies.ex, app/lib/operately/people.ex, app/test/operately/people_test.exs
partially solves https://github.com/operately/operately/issues/3599
only for invite links
=> fix: Don't try to add a person to the general space if he doesn't exists

app/test/features/work_map_test.exs, app/test/support/features/work_map_steps.ex, turboui/src/WorkMap/components/TableRow/ChildRows.tsx, turboui/src/WorkMap/components/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/components/TableRow/index.tsx, turboui/src/WorkMap/components/WorkMapTable.tsx, turboui/src/WorkMap/components/index.tsx, turboui/src/WorkMap/stories/TableRow.stories.tsx, turboui/src/utils/useLocalStorage.ts, turboui/src/utils/useStateWithLocalStorage.ts
Fixes https://github.com/operately/operately/issues/3042.
=> feat: Work Map now remembers what items were collapsed and expanded

docs/dev-env-multi-instance.md, docs/dev-env.md
fixes https://github.com/operately/operately/issues/3595
=> docs: Running multiple local LLM agents

app/lib/operately/companies.ex, app/lib/operately/companies/add_person_to_general_space.ex, app/lib/operately/operations/company_member_adding.ex, app/lib/operately/people/insert_person_into_operation.ex, app/test/operately/companies/add_person_to_general_space_test.exs, app/test/operately/operations/company_member_adding_test.exs
fixes https://github.com/operately/operately/issues/3599
=> fix: Skip adding to general space if that space does not exist

app/lib/operately_web/controllers/page.html.heex, app/lib/operately_web/controllers/page_controller.ex
fixes https://github.com/operately/operately/issues/3622
=> fix: Vite development url
