operately/operately

config/test.exs, lib/operately/okrs.ex, lib/operately/okrs/key_result.ex, lib/operately/okrs/objective.ex, lib/operately_web/controllers/objective_controller.ex, lib/operately_web/controllers/objective_html.ex, lib/operately_web/controllers/objective_html/edit.html.heex, lib/operately_web/controllers/objective_html/index.html.heex, lib/operately_web/controllers/objective_html/new.html.heex, lib/operately_web/controllers/objective_html/show.html.heex, lib/operately_web/router.ex, priv/repo/migrations/20230307123238_create_objectives.exs, priv/repo/migrations/20230307135121_create_key_results.exs, priv/repo/migrations/20230307154049_add_direction_to_key_results_table.exs, test/features/okrs.feature, test/features/okrs_test.exs, test/operately/okrs_test.exs, test/operately_web/controllers/objective_controller_test.exs, test/support/feature_case.ex, test/support/fixtures/okrs_fixtures.ex
This pull request introduces Objectives and Key Results (OKRs) to our product. OKRs are a popular goal-setting framework used to help teams align their efforts and achieve common goals.
Our goal is to improve team alignment and focus on achieving meaningful results. With Operately, we offer an opinionated approach to setting up OKRs, encouraging users to define measurable results using clear and well-understood metrics.
In some organisations, OKRs can become a convoluted to-do list rather than a clear and measurable outcome for the team to focus on. Operately aims to prevent this misuse and ensure that teams set up their OKRs correctly.
Start from the `test/features/okrs.feature` gherkin specification that outlines how objectives should behave in the system. Following this, you will end …
=> Introducing Objectives and Key Results

Dockerfile, lib/operately/tenets.ex, lib/operately/tenets/tenet.ex, lib/operately_web/controllers/tenet_controller.ex, lib/operately_web/controllers/tenet_html.ex, lib/operately_web/controllers/tenet_html/edit.html.heex, lib/operately_web/controllers/tenet_html/index.html.heex, lib/operately_web/controllers/tenet_html/new.html.heex, lib/operately_web/controllers/tenet_html/show.html.heex, lib/operately_web/router.ex, priv/repo/migrations/20230308141139_create_tenets.exs, test/features/tenets.feature, test/features/tenets_test.exs, test/operately/tenets_test.exs, test/operately_web/controllers/tenet_controller_test.exs, test/support/fixtures/tenets_fixtures.ex
In this Pull Request, I'm introducing the concept of company tenets. 
Company tenets are a set of guiding principles or values that define an organization's culture and guide its decision-making processes. These tenets should be established by the company's leadership and are intended to shape the behaviors and attitudes of all team members.
When a company has well-defined tenets, teams make faster decisions in several ways:
1. Clarity on what is most important to the organization. Teams prioritize decisions and reduces the time spent debating options that do not align with the company's values.
2. Alignment: When team members understand and share the same company tenets, they are more likely to be aligned in their decision-making. This alignment helps teams to work towards the same …
=> Introducing company tenets

Makefile, docker-compose.yml
This pull requests fix the issue with overriding default `UID` and `GID` environment variables on  macOS #8
=> Fix overriding default environment variables on macOS

Dockerfile, Makefile
In this pull request I'm fixing problem with setup development environment on macOS.
- Fix `groupadd` problem when group already exists
- Use project root directory as default for screenshots
=> Fix macOS development environment setup

Makefile
Continuation of the https://github.com/operately/operately/pull/17.
This Pull-Request introduces the possibility to explicitly set where the screenshots are exported on the host machine. This is controlled by the `SCREENSHOTS_DIR` environment variable.
If the `SCREENSHOTS_DIR` is not set, this line in the Makefile `SCREENSHOTS_DIR ?= $(PWD)/screenshots` will set it to the screenshots directory in the project's root.
If the `$(pwd)/screenshots` does not exists, `docker run -v $(pwd)/screenshots:/tmp/screenshots` will create a new directory owned by the root user. As this is owned by the root user, the container will not be able to use it.
To avoid this problem, I've added a `mkdir -p $(SCREENSHOT_DIR)` command to the `make test` target to ensure that this directory is always created before …
=> Allow exporting outside of vagrant

assets/js/i18n.js, assets/js/pages/ObjectivePage/KeyResults.tsx, assets/js/pages/ObjectivePage/StatusBadge.tsx, assets/js/pages/ObjectivePage/Table.tsx, assets/js/pages/ObjectivePage/index.tsx, lib/operately/okrs.ex, lib/operately/okrs/key_result.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230413142030_add_status_field_to_key_results.exs, test/features/okrs.feature, test/features/okrs_test.exs
In this pull-request, I'm introducing support for listing key results on the objectives page.
Every key result has a name, status, progress, and the last update time.
The code was written during live coding sessions:
- https://www.youtube.com/watch?v=xPc6byVqtsk
- https://www.youtube.com/watch?v=lew8vKYcLXQ
Screenshot:
=> Show key results on objective screen

assets/js/components/Avatar/index.tsx, assets/js/i18n.js, assets/js/pages/ObjectivePage/Projects.tsx, assets/js/pages/ObjectivePage/Table.tsx, assets/js/pages/ObjectivePage/index.tsx, lib/operately/alignments/alignment.ex, lib/operately/okrs.ex, lib/operately/ownerships/ownership.ex, lib/operately/projects.ex, lib/operately/projects/project.ex, lib/operately_web/schema.ex, test/features/okrs.feature, test/features/okrs_test.exs, test/operately/ownerships_test.exs
In this pull-request, I'm adding support for listing ongoing projects on the objective page.
The displayed fields are: Title, Progress, Champion and Last Updated At.
=> List projects on the objective page

assets/js/components/Button/index.tsx, assets/js/components/Editor/Footer.tsx, assets/js/components/Editor/index.tsx, assets/js/components/RelativeTime/index.tsx, assets/js/i18n.js, assets/js/pages/ObjectivePage/KeyResults.tsx, assets/js/pages/ObjectivePage/index.tsx, assets/package-lock.json, assets/package.json, lib/operately/updates.ex, lib/operately/updates/update.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230416071114_create_updates.exs, test/features/okrs.feature, test/features/okrs_test.exs, test/operately/updates_test.exs, test/support/fixtures/updates_fixtures.ex
In this PR I'm implementing taking the content from the TipTap editor and saving it into the database. Once saved, the `update_created` message is broadcasted and the feeds of people is automatically updated.
We are using the `JSON` format to save the content into the database. The raw JSON format preserves user mentions, in contrast to saving directly the HTML content which passes this information to the backend and makes it difficult to further process this data, for example to send out emails to the mentioned people.
=> Persist updates in the database and display the updates in the Objective Feed

assets/js/components/Editor/index.tsx, assets/js/i18n.js, assets/js/pages/ObjectivePage/index.tsx, lib/operately/updates.ex, lib/operately/updates/comment.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230417173349_create_comments.exs, test/operately/updates_test.exs, test/support/fixtures/updates_fixtures.ex
In this pull-request, I'm introducing the support for leaving comments on status updates.
Screenshot:
=> Add ability to leave comments on status updates

assets/js/components/RelativeTime/index.tsx, assets/js/i18n.js, assets/js/pages/ObjectivePage/Feed.tsx
Displaying `post added 0 seconds ago` is less nice than saying `post added just now`.
The threshold is set to < 10 seconds.
=> Replace 0 seconds ago with just now

Makefile, assets/js/components/Avatar/index.tsx, assets/js/components/Card/index.tsx, assets/js/components/CardList/index.tsx, assets/js/components/Editor/MentionList.tsx, assets/js/components/PageTitle/index.tsx, assets/js/components/SideNavigation/Link.tsx, assets/js/graphql/Me/index.tsx, assets/js/layouts/DefaultLayout/User.tsx, assets/js/layouts/DefaultLayout/index.tsx, assets/js/pages/GroupPage/index.tsx, assets/js/pages/ObjectiveListPage/index.tsx, assets/js/pages/ObjectivePage/Champion.tsx, assets/js/pages/ObjectivePage/Feed.tsx, assets/js/pages/ObjectivePage/PeopleSuggestions.tsx, assets/js/pages/ObjectivePage/Projects.tsx, assets/js/pages/ObjectivePage/index.tsx, lib/operately/people.ex, lib/operately/people/account.ex, lib/operately/people/person.ex, lib/operately_web/components/layouts/root.html.heex, lib/operately_web/controllers/account_oauth_controller.ex, lib/operately_web/graphql/context.ex, lib/operately_web/router.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230420073647_connect_people_with_accounts.exs, test/features/groups.feature, test/features/groups_test.exs
In this pull-request I'm adding support for avatars and paying the debt of hardcoded user profiles. Now, the currently signed in user will leave the comments and updates, instead of a hardcoded one.
Additionally, I'm introducing a notch on the top of the screen that shows the currently signed in account.
---
Screenshot:
=> Fetch user avatars from Google on signup, comment and share updates with the current logged in person

assets/js/graphql/Projects/index.tsx, assets/js/pages/GroupPage/Projects.tsx, assets/js/pages/GroupPage/index.tsx, assets/js/pages/ObjectivePage/Projects.tsx, assets/js/pages/ProjectListPage/index.tsx, lib/operately/groups.ex, lib/operately/projects.ex, lib/operately/projects/list_query.ex, lib/operately/projects/project.ex, lib/operately_web/graphql/queries/projects.ex, lib/operately_web/graphql/types/person.ex, lib/operately_web/graphql/types/projects.ex, lib/operately_web/schema.ex, priv/repo/migrations/20230425114123_add_group_id_to_projects.exs, test/features/groups.feature, test/features/groups_test.exs
In this pull-request I'm adding support for listing projects on the group page.
A small scale refactoring was also executed during the implementation: 
- Project related queries were extracted from components and pages and moved to `graphql/Projects`
- Project queries and types in the Absinth server were extracted and moved to a dedicated file inside of the `operately_web/graphql/` directory.
=> List projects on the group page

assets/js/graphql/Objectives/index.tsx, assets/js/pages/ObjectiveListPage/Group.tsx, assets/js/pages/ObjectiveListPage/index.tsx, lib/operately/groups.ex, lib/operately_web/graphql/types/groups.ex, lib/operately_web/graphql/types/objectives.ex, lib/operately_web/schema.ex, test/features/company_page_test.exs
When the user is on the company page and clicks on the group, the group profile is displayed in a popup, consisting of the group's name and mission statement.
Closes https://github.com/operately/operately/issues/47.
=> See group profile from the company page

assets/js/pages/ObjectiveListPage/Group.tsx, test/features/company_page_test.exs, test/support/feature_case.ex
When a user clicks on a group on the company page, a mini group profile appears. In that mini profile, there is a "Go to Group" button that leads to the group page. This PR implements this functionality.
Closes https://github.com/operately/operately/issues/49.
=> Go to the Group Page from the company page

assets/js/graphql/Objectives/index.tsx, assets/js/pages/ObjectiveListPage/Group.tsx, lib/operately/okrs.ex, lib/operately_web/graphql/mutations/objectives.ex, test/features/company_page_test.exs
A user can visit the company page, click on a group associated with a goal, and unassign that group. This PR implements this functionality.
Closes https://github.com/operately/operately/issues/50.
=> Unassign group from a Goal

assets/js/pages/ObjectiveListPage/Champion.tsx, test/features/company_page_test.exs
When a user click on the Goal's champion on the company page, their details are shown in a dropdown. Below that, a button that says "See Profile" can be clicked that leads to the Champion's profile to see further details. This PR implements this functionality.
Closes https://github.com/operately/operately/issues/55.
=> Goto user profile from company page

assets/js/graphql/Objectives/index.tsx, lib/operately/okrs/key_result.ex, lib/operately_web/graphql/types/key_results.ex, priv/repo/migrations/20230503165843_add_group_id_to_key_results.exs, test/features/company_page_test.exs
When a user visits the company page, click on a group that is associated with a target, a popup appears giving further details about the group. On this popup there is a go to group button. This pull-request implements this button.
Closes https://github.com/operately/operately/issues/56.
Closes https://github.com/operately/operately/issues/57.
=> See target groups on company page

lib/operately/okrs.ex, lib/operately_web/graphql/mutations/key_results.ex, test/features/company_page_test.exs
In this pull-request, I'm adding support for removing a group assignment from the a target on the company page. The flow is that a user opens the company page, clicks on the currently assigned group for a target, and chooses unassign from the dropdown menu.
Closes https://github.com/operately/operately/issues/60.
=> Remove group from a Target

assets/build.js, assets/js/graphql/client.tsx, assets/js/graphql/wsLink.tsx
Before this, a deployment of the app would break the connection which would never reconnect. Now, the connection is retried for an extended amount of time with exponential backoffs.
Example of broken connection that is retriying and finally succeeding:
=> Websocket Connection Retries

assets/js/gql/generated.tsx, assets/js/pages/NotificationsPage/NotificationItem/ProjectTimelineEdited.tsx, assets/js/pages/NotificationsPage/NotificationItem/index.tsx, assets/js/pages/NotificationsPage/loader.tsx, assets/js/pages/ProjectEditTimelinePage/index.tsx, docs/dev_users.md, lib/operately/activities/content.ex, lib/operately/activities/content/project_timeline_edited.ex, lib/operately/activities/notifications/project_timeline_edited.ex, lib/operately/activities/recorder.ex, lib/operately/projects.ex, lib/operately/projects/edit_timeline_operation.ex, lib/operately/projects/milestone.ex, lib/operately/projects/phase_history.ex, lib/operately/schema.ex, lib/operately_email/project_timeline_edited_email.ex, lib/operately_email/templates/project_timeline_edited.html.eex, lib/operately_email/templates/project_timeline_edited.text.eex, lib/operately_email/views/project_timeline_edited.ex, lib/operately_web/graphql/mutations/projects.ex, lib/operately_web/graphql/schema.ex, lib/operately_web/graphql/types/activity_content.ex, lib/operately_web/graphql/types/activity_content_project_timeline_edited.ex, test/features/project_milestones_test.exs, test/features/projects_test.exs, test/support/features/email_steps.ex, test/support/features/notifications_steps.ex, test/support/features/project_steps.ex
Additionally, this PR fixes a bug where the updated deadlines for milestones on the edit project page were not persisted to the database.
=> Send out notifications for project timeline edits

lib/operately_web/account_auth.ex, test/operately_web/account_auth_test.exs
Before, it looked like this, which makes no sense:
=> Don't show redundant flash on login page

assets/js/components/PaperContainer/DimmedSection.tsx
Hello!
This PR fixes the bottom from the `DimmedSection` component in the Company space page:
- when the `size` is `large`, use the margin-top/bottom of 10.
closes https://github.com/operately/operately/issues/446.
=> Fix:  Feed bottom border

assets/js/components/Form/select.tsx, assets/js/pages/AccountEditProfilePage/index.tsx
Replaces "Actual Timezone" with "Timezone".
Removes underscore from some timezone labels, e.g. "Sao_Paulo" is now "Sao Paulo".
=> Visual changes for timezones

assets/js/pages/AccountPage/page.tsx, test/features/notifications_test.exs
**Objective**
- Remove the Notifications button in the Personal Settings area.
**Changes Implemented**
- Removed the Notifications button from the Personal Settings interface.
- Adjusted the layout to ensure consistency after the button removal.
=> Removing Notification button on Personal Settings

test/support/custom_formatter.ex, test/support/features/ui.ex, test/test_helper.exs
I've set up screenshot collection for flaky tests on Semaphore. One thing in common for most of the flaky tests is that it is breaking when we switch from one login session to another.
Example:
``` elixir
ctx
|> UI.login_as(ctx.champion)
|> ...
|> UI.login_as(ctx.reviewew)
|> ...
```
Based on the screenshots, the application is still on the login page when the user action are passed, e.g. "click on the notification bell".
Example screenshot taken after the `UI.login_as(ctx.reviewer)` step:
To mitigate this, I'm adding extra steps to the `UI.login_as` step that will wait for the Operately lobby to load.
=> Fix flaky tests caused by incorrect login

lib/operately/activities.ex, lib/operately/activities/content.ex, lib/operately/activities/content/project_created.ex, lib/operately/activities/list_activities_operation.ex, lib/operately/activities/recorder.ex, lib/operately_email/emails/goal_timeframe_editing_email.ex, lib/operately_email/emails/project_timeline_edited_email.ex, lib/operately_web/graphql/queries/notifications.ex, lib/operately_web/graphql/types/activity_content_goal_editing.ex, lib/operately_web/graphql/types/activity_content_goal_timeframe_editing.ex, lib/operately_web/graphql/types/activity_content_project_created.ex, lib/operately_web/graphql/types/activity_content_project_timeline_edited.ex, test/features/goal_creation_test.exs
Up until now, we couldn't use use a `belongs_to` association on activity data, which means that we couldn't use `Repo.preload(record, [:association1, :association1])`, but had to manually load them.
Loading referenced records without this was error prone, and hard to optimize.
=> Allow using belongs_to on embedded schemas

test/support/custom_formatter.ex
Fixes test flakkines caused by this error:
=> The test suite formatter should not stop when a suite is finished

lib/operately_web/certification.ex
Fixes this https://github.com/operately/operately/issues/531.
The source of the problem was that site_encrypt was starting a local ACME server (responsible for giving out SSL certs) in both the development and test environments, on the same port: 4003.
This pull-request solves this problem by starting the ACME server on port 4003 for dev, and port 4004 for the test environemnt, so they don't clash.
=> Don't start ACME server in test

lib/operately/access/access_context.ex, lib/operately/data/change_009_create_projects_access_context.ex, lib/operately/projects/project.ex, priv/repo/migrations/20240610091322_add_project_access_context.exs, test/operately/access/bindings_test.exs, test/operately/access/contexts_test.exs, test/operately/data/change_009_create_projects_access_context_test.exs
I've added a one-to-one relationship between projects and access contexts.
I've also added a data migration to create access contexts for existing projects.
=> Add access context to projects

lib/mix/operately.ex
When using the command `./devenv mix operately.gen.api.query get_activities`, the system returned the message: `Aborting lib/operately_web/api/queries/get_activities.ex already exists`. The word "Aborting" was displayed in green.
We changed the color of the word "Aborting" to red, improving visual clarity for developers. The new message is:
```elixir
def generate_file(path, generator) do
if File.exists?(path) do
IO.puts "#{IO.ANSI.red()}Aborting#{IO.ANSI.reset()} #{path} already exists"
System.halt(1)
else
generate_file!(path, generator)
end
end
```
- **Visual Clarity:** Red is commonly associated with errors and interruptions, making the message more intuitive.
- **Consistency:** Enhances consistency in displaying critical error messages.
This change aims to improve the developer …
=> Red Abort in generators

lib/operately/access/access_context.ex, lib/operately/data/change_010_create_groups_access_context.ex, lib/operately/groups/group.ex, priv/repo/migrations/20240610184000_add_group_access_context.exs, test/operately/access/contexts_test.exs, test/operately/data/change_010_create_groups_access_context_test.exs
I've added a one-to-one relationship between groups and access contexts.
I've also added a data migration to create access contexts for existing groups.
=> Add access context to groups

assets/js/pages/AccountEditProfilePage/index.tsx, assets/package-lock.json, assets/package.json
This pull request aims to improve the way time zones are displayed in the user's profile form, making the information more comprehensible and user-friendly. Additionally, several improvements and bug fixes have been implemented in the code.
1. **Time Zone Formatting:**
- Added the `formatTimezone` function to format time zones in the format `(UTC-03:00) Sao Paulo`.
- Replaced the previous time zone display, such as `America/Sao_Paulo`, with the new, more descriptive formatting.
2. **User Interface Adjustments:**
- Updated the time zone values in the time zone selector options to use the new formatting.
- Fixes in the styling of the file input and other form components.
- **`formatTimezone` Function:**
- The new `formatTimezone` function has been implemented to format the time zone string …
=> Show UTC for Time zones

lib/operately/access.ex, lib/operately/operations/project_creation.ex, test/features/project_creation_test.exs, test/operately/access/bindings_test.exs, test/operately/access/contexts_test.exs, test/operately/data/change_009_create_projects_access_context_test.exs, test/operately/projects_test.exs, test/support/features/project_creation_steps.ex
I changed the project creation logic so that creating a project will automatically create an access context from now on.
=> Creating a project automatically creates access context

lib/operately/data/change_009_create_projects_access_context.ex, test/operately/data/change_009_create_projects_access_context_test.exs
I improved the Change009CreateProjectsAccessContext data migration. Now it creates an access context for projects that don't have them yet while skipping projects that may already have an access context.
This improvement was necessary because, after https://github.com/operately/operately/pull/553, if the data migration still hadn't been applied and new projects were created, the new projects would have access contexts and the data migration wouldn't work.
=> Data migration skips projects that already have access context

lib/operately/access/access_context.ex, lib/operately/companies/company.ex, lib/operately/data/change_011_create_companies_access_context.ex, priv/repo/migrations/20240610204000_add_company_access_context.exs, test/operately/access/contexts_test.exs, test/operately/data/change_011_create_companies_access_context_test.exs
I've added a one-to-one relationship between companies and access contexts, along with a data migration to create access contexts for existing companies.
Initially, I planned to add the relationship between activity and access context first. However, I realized that activity should be added last since it will use the same context as projects, groups, and companies.
=> Add access context to companies

assets/js/pages/AccountEditProfilePage/index.tsx
In the new approach, we removed the styling class that defined the image size when there was no avatar, resulting in:
```javascript
{avatarUrl === null ? (
) : (
<Avatar person={me} size="xxlarge" />
)}
```
This ensures that the circle maintains its original size regardless of the avatar's presence.
=> Adjust Circle Size for Consistency When Removing Avatar

assets/js/components/Avatar/index.tsx, assets/js/pages/AccountEditProfilePage/index.tsx
This Pull Request implements improvements in the logic for displaying the user's avatar in the profile form. These changes ensure that the user's initials are shown immediately after the profile picture is removed. Additionally, the `ImageAvatar` and `BackupAvatar` components were created and exported to enhance code modularity and reusability.
1. **New Components for Avatar**:
- **`ImageAvatar`**: Component that displays the user's avatar image.
- **`BackupAvatar`**: Component that displays the user's initials as a backup avatar.
2. **Updated Logic in the `ProfileForm` Component**:
- The `handleRemoveAvatar` function now sets `avatarUrl` to `null` immediately when the remove button is clicked.
- The conditional rendering of the avatar has been adjusted to use the new `ImageAvatar` and …
=> Show initials immediately while user removes Avatar

assets/js/pages/AccountEditProfilePage/index.tsx
**Issue Description:**
Previously, when a user set their "Title in the Company" field to an empty value and saved the changes, they were unable to access their own profile. This issue impacted the user's ability to view or edit their profile effectively.
**Steps to Reproduce the Issue:**
1. Navigate to the user profile settings.
2. Set the "Title in the Company" field to an empty value.
3. Save the changes.
4. Attempt to access the user profile again.
**Expected Result:**
The user should be able to access their profile regardless of the "Title in the Company" field being empty.
**Actual Result:**
The user is unable to access their profile after setting the "Title in the Company" field to an empty value.
**Solution:**
This PR addresses the issue by ensuring that the "Title in the Company" …
=> Bug Fix: User Profile Inaccessible When Title in the Company is Set to Empty

test/support/features/project_steps.ex
This test was sometimes failing (recently [here](https://operately.semaphoreci.com/workflows/80c555a8-fb55-4214-ab1c-a7e35f5e52f2/summary?pipeline_id=811f2d10-ccaf-4d6a-ab1c-b89c852ae40e&report_id=31c127ba-6edc-33b1-9f53-fc4a54e74c82&test_id=4e6e595c-da57-3af3-8415-abb2f1baf993)) because, after renaming a project, we tried to assert that the name was changed in the DB, but the assertion was running before the name change was complete. After asserting the project was renamed in the DB, we also checked that the new name was visible in the UI.
To fix the problem, I inverted the order of the assertions. Now, we first assert that the new name is visible in the UI, which indicates the renaming is complete. Then we assert the new name is correct in the DB.
=> Fix flaky test "feature rename a project"

lib/operately/access.ex, lib/operately/data/change_010_create_groups_access_context.ex, test/operately/data/change_010_create_groups_access_context_test.exs
Before there changes, if we ran the groups data migration and a group already had an access context associated with it, the migration would fail. Now the migration skips groups that already have an access context.
=> Groups data migration skips groups that already have context

lib/operately/operations/goal_creation.ex, test/operately/access/contexts_test.exs, test/operately/data/change_012_create_goals_access_context_test.exs
I've changed the goals creation logic so that, from now on, creating a goal automatically creates an access context.
=> Creating a goal automatically creates an access context

assets/js/api/index.tsx, assets/js/components/Editor/Blob/FileUploader.tsx, assets/js/components/Editor/Blob/S3Upload/S3Upload.tsx, assets/js/gql/generated.tsx, assets/js/graphql/Blobs/index.tsx, assets/js/pages/AccountEditProfilePage/index.tsx, lib/operately/blobs/blob.ex, lib/operately/people/person.ex, lib/operately_web/api/queries/get_me.ex, lib/operately_web/api/types.ex, lib/operately_web/graphql/mutations/people.ex, lib/operately_web/graphql/types/blobs.ex, lib/operately_web/graphql/types/person.ex, priv/repo/migrations/20240613093658_add_blob_id_to_people_table.exs, priv/repo/migrations/20240613124458_add_blob_id_to_blob_table.exs, test/operately/people_test.exs, test/operately_web/api/queries/get_me_test.exs, test/operately_web/graphql/mutations/people_test.exs
This PR introduces significant enhancements to support custom avatars in the Operately application. The key changes include:
1. **Database Migration**:
- Adds a new `avatar_blob_id` column to the `people` table, which references the `blobs` table. This allows each user to have a custom avatar stored as a blob in the database.
```elixir
defmodule Operately.Repo.Migrations.AddBlobIdToPeopleTable do
use Ecto.Migration
def change do
alter table(:people) do
add :avatar_blob_id, references(:blobs, on_delete: :delete_all, type: :binary_id)
end
end
end
```
2. **Update to `Person` Schema**:
- Updates the schema of the `Person` entity to include the `avatar_blob_id` field, ensuring that the application aligns with the new database structure.
```elixir
defmodule Operately.People.Person do
use …
```
=> Add avatar blob id reference

test/awsS3/s3mock.exs
This PR removes comments from the `S3mock` module. The functionality of the tests remains unchanged. The comments were removed to make the code cleaner, focusing solely on the test logic, which includes:
1. **Setup**:
- Creating an S3 bucket before the tests run.
- Removing all objects and the bucket after the tests run using the `on_exit` function.
2. **Tests**:
- **upload file to S3**: Uploads a file to the S3 bucket and verifies that the retrieved file content matches the uploaded content.
- **list files in bucket**: Uploads a file and lists the files in the bucket, checking that the uploaded file is listed.
The comments were deemed unnecessary as the code is self-explanatory.
=> Removing useless comments

lib/operately/operations/goal_discussion_editing.ex
I've changed the way the activity was being created in `GoalDiscussionEditing`. Now this operation also uses `Activities.insert_sync` to create the activity. 
This change was necessary because, for the access context to be attached to the activity, the activity creation has to go through `Activities.insert_sync`.
=> Add insert_sync to GoalDiscussionEditing operation

assets/js/components/Avatar/index.tsx, assets/js/pages/AccountEditProfilePage/index.tsx
This pull request fixes the auto-reload issue of the user avatar when a new avatar is uploaded to the site. Below are the changes made:
1. **Removal of Unused Import:**
- File: `assets/js/pages/AccountEditProfilePage/index.tsx`
- Line removed: `import { ImageAvatar } from "@/components/Avatar";`
2. **Modification in the FileInput Component:**
- Specification of inline style for the file input to ensure it remains hidden.
- Before: `style={{ display: "none" }}`
- After: `style={{display: "none"}}`
3. **Update to Avatar Rendering in Profile Form:**
- Replaced the `ImageAvatar` component with an `<img>` tag to display the avatar image.
- Added attributes for the image: `src={avatarUrl}`, `alt="avatar"`, `className="rounded-full w-24 h-24"`.
With these changes, the user's avatar is …
=> Avatar auto reload

lib/operately/data/change_010_create_groups_access_context.ex, test/operately/data/change_010_create_groups_access_context_test.exs
I've updated the data migration used to create access contexts for groups. Now, the migration also creates an access context for soft-deleted groups.
=> Include soft-deleted groups in data migration

config/test.exs, test/features/goals_test.exs, test/support/features/ui.ex
I've noticed that some UI tests are excessively slow. For example this one:
I went down the rabbithole to figure out the reason.
Turns out, this test was heavily using `Wallaby.Browser.refute_has`, which in turn is calling https://github.com/elixir-wallaby/wallaby/blob/main/lib/wallaby/browser.ex#L1496. I've put an IO.inspect into that function and noticed that it is reaching out to the running browser hundreds of times. 
Basically, it was trying to find the element for 3 seconds, and if it didn't found it, it declared that refute_has(text) has passed. In the original test, we were running 4 times in a row refute_has, amount to 12 seconds of needless waiting.
---
the new implementation of the `UI.refute_text` now simply gets all the available text on the screen, and tests if the desired …
=> Speed up slowest test

assets/js/components/Editor/Blob/AddBlobsEditorCommand.tsx, assets/js/components/Editor/Blob/BlobView.tsx
Currently, discussions are creating a src that equals `{id: <blob-id>, url: url}`, while the rest of the rich text system expects just the url.
=> Fixes Rich Text Upload src

lib/operately/access.ex, lib/operately/access/access_group.ex, lib/operately/companies/company.ex, lib/operately/operations/company_adding.ex, priv/repo/migrations/20240628081627_add_company_id_field_to_access_groups_schema.exs, priv/repo/migrations/20240628084820_add_tag_field_to_access_group_schema.exs, test/operately/access/bindings_test.exs, test/operately/operations/company_adding_test.exs
I've updated `Operately.Operations.CompanyAdding` so that, from now on, creating a company automatically creates:
- An access group for company admins
- An access group for company members
- Access bindings between the new access groups and the company's access context
- If an admin user is created with the company, an access group membership between the admin and the new admins access group is also created
By default, the admins access group gets full access and the members access group gets read-only access. I think that's a reasonable behavior, but we can easily change it in the future.
=> Creating a company creates access groups, bindings and memberships

Gemfile.lock, assets/js/components/SpaceColorChooser/index.tsx, assets/js/components/SpaceIconChooser/index.tsx, assets/js/features/Permissions/PrivacyLevel.tsx, assets/js/pages/GroupAddPage/page.tsx, assets/js/pages/GroupAppearancePage/page.tsx
Before:
After:
Reasoning:
- Title: use active voice, this common in UI (will apply to other screens but don't want to do too much in my first PR of the kind)
- subtitle to describe the purpose of spaces - a little bit of help
- color / icon - less words is better
- Privacy / Internal - "Only" felt off
- Added an assuring sentence before the buttons that everything can be changed later so no worries.
=> Wordsmith Spaces form copy

lib/operately/data/change_020_create_project_contributors_bindings.ex, test/operately/data/change_020_create_project_contributors_bindings_test.exs
I've added a data migration for creating access bindings between projects and its contributors.
=> feat: Add migration for creating binding between projects and contributors

assets/js/features/Tasks/TaskBoard.tsx
Previously, the kanban board state was transmitted as string JSON data, but I've converted it to be a proper API type last week. However, the JS API Client automatically converts every key from snake_case to camelCast which broke the lookup when the task.status was in_progress, but the kanbanState only contained the todo, inProgress, done states.
fixes: https://github.com/operately/operately/issues/726
=> fix: Broken task list on milestones in_progress vs inProgress

assets/js/api/index.tsx, assets/js/features/goals/GoalForm/useForm.tsx, assets/js/pages/GoalEditPage/page.tsx, lib/operately/access.ex, lib/operately/operations/goal_editing.ex, lib/operately_web/api/mutations/edit_goal.ex, test/operately/operations/goal_editing_test.exs
I've updated `Operately.Operations.GoalEditing` so that it also updates the access level of bindings between the goal's access context and the company's and space's access groups.
I decided to submit this PR as it is since everything should be working. However, I'd say that the user experience is not that good because we are not loading the current permissions of the goal. So, the user can set new permissions, but they don't know what the current ones are.
In the near future, we should probably update the way goals are loaded, so that it includes permissions information as well.
=> feat: Update GoalEditing operation

lib/operately/projects/check_in.ex, lib/operately_web/api/queries/get_assignments.ex, test/operately_web/api/queries/get_assignments_test.exs
I've fixed the issue described it https://github.com/operately/operately/issues/792.
The problem was that our `Repo.all()` handles the exclusion of soft-deleted items from queries only when it's querying them directly, but it does not handle it when it comes to relationships.
So, it would exclude soft-deleted goals and projects, but it would still load their outstanding check-ins and updates that hadn't been acknowledged yet. However, if we clicked on these check-ins and updates, we would be redirected to their pages and get a 500 because `Repo` can't load soft-deleted goals and projects directly.
=> fix: get_assignments query excludes soft-deleted items

lib/operately/access/filters.ex, lib/operately_web/api/queries/get_activities.ex, lib/operately_web/api/queries/get_activity.ex, test/operately_web/api/queries/get_activity_test.exs
I've added a permissions filter `OperatelyWeb.Api.Queries.GetActivity`. If the user doesn't have `view_access` to the activity, 404 is returned.
=> feat: Add permissions filter to get_activity query

test/operately_web/api/queries/get_activity_test.exs
I've replaced `Operately.Groups.add_members/2` by `Operately.Groups.add_members/3` in the get_activity tests.
=> fix: Replace add_members/2 by add_members/3

assets/js/window.d.ts, lib/operately/people.ex, lib/operately/people/account.ex, lib/operately/people/fetch_or_create_account_operation.ex, lib/operately/people/person.ex, lib/operately_web/account_auth.ex, lib/operately_web/api/helpers.ex, lib/operately_web/api/mutations/mark_all_notifications_as_read.ex, lib/operately_web/api/mutations/mark_notification_as_read.ex, lib/operately_web/api/mutations/update_my_profile.ex, lib/operately_web/api/queries/get_me.ex, lib/operately_web/api/queries/get_notifications.ex, lib/operately_web/api/queries/get_spaces.ex, lib/operately_web/api/queries/get_unread_notification_count.ex, lib/operately_web/api/subscriptions/assignments_count.ex, lib/operately_web/api/subscriptions/unread_notifications_count.ex, lib/operately_web/channels/api_socket.ex, lib/operately_web/components/layouts/root.html.heex, lib/operately_web/router.ex, test/features/first_time_setup_test.exs, test/operately_web/api/mutations/add_first_company_test.exs, test/support/features/invite_member_steps.ex
This is the first half of this change. It is preparing the backend system to be able to handle the `has_many` association between accounts and people, but it is still not handling having multiple companies for one account.
The [current code](https://github.com/operately/operately/pull/808/files#diff-0241219bc5ea0f0d413a0af274f3cc8978695cd5d439a5f484fb068c5900b868R116) uses `account.people |> List.first()` to look up the person in every request. This will be addressed in an upcoming PR.
=> feat: A single account can belong to multiple companies via people records

lib/operately/access/filters.ex, lib/operately/activities/activity.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/data/change_013_create_activities_access_context.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, lib/operately_web/api/queries/get_goal_progress_updates.ex, lib/operately_web/api/queries/get_goals.ex, priv/repo/migrations/20240730162256_rename_activity_context_id_to_activity_access_context_id.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_013_create_activities_access_context_test.exs, test/operately_web/api/queries/get_goal_progress_update_test.exs, test/operately_web/api/queries/get_goal_progress_updates_test.exs, test/operately_web/api/queries/get_goal_test.exs, test/operately_web/api/queries/get_goals_test.exs
- OperatelyWeb.Api.Queries.GetGoal
- OperatelyWeb.Api.Queries.GetGoals
- OperatelyWeb.Api.Queries.GetGoalProgressUpdate
- OperatelyWeb.Api.Queries.GetGoalProgressUpdates
=> feat: Add permissions filter to Goal queries

lib/operately/access/filters.ex, lib/operately_web/api/queries/get_project.ex, lib/operately_web/api/queries/get_project_check_in.ex, lib/operately_web/api/queries/get_project_check_ins.ex, lib/operately_web/api/queries/get_projects.ex, test/operately_web/api/queries/get_project_check_in_test.exs, test/operately_web/api/queries/get_project_check_ins_test.exs, test/operately_web/api/queries/get_project_test.exs, test/operately_web/api/queries/get_projects_test.exs, test/support/features/project_creation_steps.ex
- OperatelyWeb.Api.Queries.GetProject
- OperatelyWeb.Api.Queries.GetProjects
- OperatelyWeb.Api.Queries.GetProjectCheckIn
- OperatelyWeb.Api.Queries.GetProjectCheckIns
=> feat: Add permissions filter to Project queries

assets/js/features/CommentSection/useForGoalCheckIn.tsx, lib/operately_web/api/queries/get_comments.ex, lib/operately_web/paths.ex, test/operately_web/api/queries/get_comments_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Queries.GetComments` query.
=> feat: Add permissions filter to GetComments query

README.md, docs/installation/local.md, docs/installation/single-host.md, rel/single-host/docker-compose.yml.eex, rel/single-host/operately.env
This is a proposal how the installation steps should look like. For the first pass, we will release Operately that is able to run on a single host bundled with a database and file storage.
The missing part for this installation is setting up a valid SSL cert. Setting this up is probably the most complicated step, as it either requires setting up a letsencrypt schema, or purchasing an SSL cert. Not yet sure how to tackle that one. 
**What is not included in this PR?**
HA configuration will come in the future. The installation steps for HA are more involved, as you need to set up an external database, external S3 based file storage, and a load balancer. The HA steps will most likely be based on Kubernetes manifests. 
---
@markoa @Rockyy174 I'm adding you as reviewers to this PR. My main …
=> docs: Self-Hosted Installation docs

docker-compose.yml
I'm testing the DX of local development setup, and I'm cloning multiple instances of the operately codebase (e.g. operately1, operately2). One thing that blocks starting up multiple of them is this container name for the pgweb.
AFAIK it is not needed for our development setup, and the reason it is there is pure copy/paste from the pgweb docs.
=> chore: Remove pgweb container name

assets/js/app.tsx, assets/js/pages/FirstTimeLoginPage/page.tsx, assets/js/pages/FirstTimeLoginPage/useForm.tsx, lib/operately_web/api/serializer.ex, test/features/invite_member_test.exs, test/operately_web/api/queries/get_invitation_test.exs, test/support/features/invite_member_steps.ex, test/support/features/ui.ex
fixing: https://github.com/operately/operately/issues/847
Also, a design update for the screen:
Now, the test is able to work even without a login which makes this testing path more robust.
=> fix: Invitations for company members

lib/operately/access/access_group_membership.ex, lib/operately/access/filters.ex, lib/operately_web/api/queries/get_people.ex, test/operately_web/api/queries/get_people_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Queries.GetPeople` query.
I noticed that the `filter_by_view_access` function was allowing suspended people to use the API. This issue is also handled in this PR.
=> feat: Add permissions filter to GetPeople query

lib/operately_web/api/queries/get_key_resource.ex, test/operately_web/api/queries/get_key_resource_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Queries.GetKeyResource` query.
=> feat: Add permissions filter to GetKeyResource query

lib/operately/access/filters.ex, lib/operately_web/api/mutations/archive_project.ex, lib/turbo_connect/plugs/dispatch.ex, test/operately_web/api/mutations/archive_project_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.ArchiveProject` mutation.
=> feat: Add permissions filter to ArchiveProject mutation

docs/installation/single-host.md
docker-compose is the old standard and might not be available on new machines.
=> docs: Use docker compose without dashes

lib/operately_web/api/mutations/add_project_contributor.ex, test/operately_web/api/mutations/add_project_contributor_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.AddProjectContributor` mutation.
=> feat: Add permissions filter to AddProjectContributor mutation

lib/operately/access/filters.ex, lib/operately_web/api/mutations/add_key_resource.ex, test/operately_web/api/mutations/add_key_resource_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.AddKeyResource` mutation.
=> feat: Add permissions filter to AddKeyResource mutation

lib/operately/release.ex, rel/overlays/bin/create_db
So far this was done with postgres specific tools manually. With these additions the create_db and migrate can be part of the docker compose entry point.
The entry point I have in mind (for next PR) is:
```
#/bin/sh
/app/bin/create_db
/app/bin/migrate
/app/bin/server
```
The create_db has a built in mechanism to wait for the postgres server to fully boot up.
=> chore: Implement wait for db and create db in Elixir

lib/operately/data/change_013_create_activities_access_context.ex
One of the activities is failing to be converted. This is the first step in the fix: to add a bit more logging around the problem.
=> chore: Add logs around assigning contexts to track which one failed

lib/operately/companies.ex, lib/operately_web/api/mutations/add_company_admins.ex, test/features/company_admin_test.exs, test/operately_web/api/mutations/add_company_admins_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.AddCompanyAdmins` mutation.
=> feat: Add permissions filter to AddCompanyAdmins mutation

lib/operately_web/api/mutations/close_project.ex, test/operately_web/api/mutations/close_project_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.CloseProject` mutation.
=> feat: Add permissions filter to CloseProject mutation

lib/operately_web/api/mutations/add_company_member.ex, test/features/invite_member_test.exs, test/operately/data/change_025_populate_account_full_name_test.exs, test/operately_web/api/mutations/add_company_member_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.AddCompanyMember` mutation.
=> feat: Add permissions filter to AddCompanyMember mutation

lib/operately/operations/task_description_change.ex, lib/operately_web/api/mutations/change_task_description.ex, test/operately/operations/task_description_change_test.exs, test/operately_web/api/mutations/change_task_description_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.TaskDescriptionChange` mutation.
=> feat: Add permissions filter to TaskDescriptionChange mutation

lib/operately/operations/project_goal_disconnection.ex, lib/operately_web/api/mutations/disconnect_goal_from_project.ex, test/operately/operations/project_goal_disconnection_test.exs, test/operately_web/api/mutations/disconnect_goal_from_project_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.DisconnectGoalFromProject` mutation.
=> feat: Add permissions filter to DisconnectGoalFromProject mutation

lib/operately_web/api/mutations/create_group.ex, test/operately_web/api/mutations/create_group_test.exs, test/support/features/space_steps.ex
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.CreateGroup` mutation.
=> feat: Add permissions filter to CreateGroup mutation

lib/operately/operations/goal_check_in_edit.ex, lib/operately_web/api/mutations/edit_goal_progress_update.ex, test/operately_web/api/mutations/edit_goal_progress_update_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.EditGoalProgressUpdate` mutation.
=> feat: Add permissions filter to EditGoalProgressUpdate mutation

lib/operately/operations/goal_editing.ex, lib/operately_web/api/mutations/edit_goal.ex, test/operately/operations/goal_editing_test.exs, test/operately_web/api/mutations/edit_goal_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.EditGoal` mutation.
=> feat: Add permissions filter to EditGoal mutation

lib/operately/access/filters.ex, lib/operately/groups.ex, lib/operately/groups/permissions.ex, lib/operately_web/api/mutations/edit_group.ex, lib/operately_web/api/mutations/edit_space_permissions.ex, test/operately_web/api/mutations/edit_group_test.exs, test/operately_web/api/mutations/edit_space_permissions_test.exs
I've added a permissions filter to the `OperatelyWeb.Api.Mutations.EditGroup` and `OperatelyWeb.Api.Mutations.EditSpacePermissions` mutations.
=> feat: Add permissions filter to EditGroup and EditSpacePermissions

lib/operately/operations/project_check_in_edit.ex, lib/operately/projects.ex, lib/operately/projects/check_in.ex, lib/operately/projects/permissions.ex, lib/operately_web/api/mutations/edit_project_check_in.ex, lib/operately_web/api/serializer.ex, test/operately_web/api/mutations/edit_project_check_in_test.exs
I've added a permissions check to the `OperatelyWeb.Api.Mutations.EditProjectCheckIn` mutation.
=> feat: Edit project check-in security

lib/operately/projects/permissions.ex, lib/operately_web/api/mutations/edit_project_timeline.ex, test/operately_web/api/mutations/edit_project_timeline_test.exs
I've added a permissions check to the `OperatelyWeb.Api.Mutations.EditProjectTimeline` mutation.
=> feat: Edit project timeline security

assets/js/routes/index.tsx
Without this, it was impossible to test dark/light mode on the design page.
As the design page is "public" it will follow the system preferences.
Protip: If you are touching design you will have to switch between light/dark mode often.
Set up a mac script and easily switch with `cmd-space` `toggle-dark...`. https://medium.com/@geert.cuppens/macos-keyboard-shortcut-to-toggle-dark-mode-2724c9f7fbfe.
https://github.com/user-attachments/assets/58e6a940-f101-4fab-997d-03e528951821
=> chore: Use system theme on design page

assets/css/app.css, assets/js/components/Forms/ErrorMessage.tsx, assets/js/components/Menu/index.tsx, assets/js/components/MilestoneIcon/index.tsx, assets/js/features/PerfBar/index.tsx, assets/js/features/activities/GoalCheckIn/ConditionChanges.tsx, assets/js/features/goals/GoalCheckInForm/Form.tsx, assets/js/features/goals/GoalForm/Form.tsx, assets/js/features/goals/GoalPageHeader/index.tsx, assets/js/features/goals/GoalTree/components/NodeIcon.tsx, assets/js/features/projectCheckIns/Form/Form.tsx, assets/js/pages/CompanyAdminAddPeoplePage/page.tsx, assets/js/pages/CompanyAdminTrustedEmailDomainsPage/page.tsx, assets/js/pages/DesignPage/Colors.tsx, assets/js/pages/GoalAddPage/page.tsx, assets/js/pages/GoalEditPage/page.tsx, assets/js/pages/GoalEditTimeframePage/index.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, assets/js/pages/JoinPage/page.tsx, assets/js/pages/NewCompanyPage/index.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/ProjectClosePage/page.tsx, assets/js/pages/ProjectEditTimelinePage/MilestoneList.tsx, assets/js/pages/ProjectEditTimelinePage/page.tsx, assets/js/pages/ReviewPage/page.tsx, assets/js/pages/SetupPage/page.tsx, assets/js/pages/SpaceEditPage/page.tsx, assets/tailwind.config.js
fixes: https://github.com/operately/operately/issues/969
I've also separated the colors in three categories. To have a good judgment about text colors I need to see actual text on the page.
The currently nicknamed "Miscellaneous" will most likely become UI elements, or Form colors.
=> chore: Replace text-red-500 with a semantic color name

assets/js/features/Subscriptions/SubscribersSelector.tsx, assets/js/features/Subscriptions/SubscriptionsContext.tsx, assets/js/features/Subscriptions/index.tsx, assets/knip.json
I've added the component `SubscribersSelector` and the context `SubscriptionsContext`.
I tried to follow the wireframe as strictly as possible, but most likely we still need some adjustments in the design.
Also, once I add and update the API endpoints, other adjustments in the functionality will be necessary as well, such as displaying the Space name or whether it's a Space, Goal, Project, etc.
But overall the component and context should be mostly ready.
https://github.com/user-attachments/assets/a275adb5-bbe9-4498-a059-1b787adae512
=> feat: Add SubscribersSelector component

test/support/features/invite_member_steps.ex, test/support/features/ui.ex
My theory is that this tweak will eliminate, or drastically reduce the flakiness related to logins. Why is that?
After running a heavy log-in/log-out loop on my local computer (image down), I've noticed that not every chrome webdriver instance is killed off (I was running htop on the side). This accumulated memory and my machine started to swap which slowed down the execution and ultimately reproduced the same behaviour as we see in flaky tests.
In theory, this should also increase the performance of the test suite and reduce the total time for execution. This is left to be seen in practice.
Heavy log-in/log-out loop on my local computer:
=> chore: Instead of creating a new browser session, clear the cookies to logout

assets/js/components/Forms/useForm.tsx
Example usage:
``` typescript
const form = Forms.useForm({
fields: {
password: Forms.useTextField(""),
passwordConfirmation: Forms.useTextField(""),
},
validate: (fields, addError) => {
if (fields.password.value !== fields.passwordConfirmation.value) {
addError("passwordConfirmation", "Passwords do not match");
}
},
submit: async (form) => {
...
},
});
```
=> chore: Introduce custom validators for forms

lib/operately/operations/project_check_in.ex, lib/operately/time.ex, test/operately/time_test.exs
fixes https://github.com/operately/operately/issues/994
The problem with the previous implementation was that it over scheduled the next check in if you have checked in very early. 
Example:
Given that you have this week that starts with a Saturday and the check-in due date is presented:
```
S  S  M  T  W  T  F  S  S  M  T  W  T  
^                 ^ 
today             check-in due
```
The old implementation would move the check-in due for a week, making it almost 14 days dalay between two check-ins.
```
S  S  M  T  W  T  F  S  S  M  T  W  T  F
^                                      ^ 
today                                  check-in due
```
The new implementation ignores this super early check-in and keeps the due date the same:
```
S  S  M  T  W  T  F  S  S  M  T  W  T  F
^ …
```
=> fix: Fix check-in scheduler when checking in earlier

assets/js/components/Tooltip/index.tsx, assets/js/features/projects/PrivacyIndicator.tsx, assets/js/models/projects/index.tsx, assets/js/pages/ProjectPage/Header.tsx
fixes https://github.com/operately/operately/issues/966
---
Public:
Company-wide (no-indicator):
Only space members:
Restricted project:
=> feat: Show privacy level indicators next to project names

.vscode/settings.json
if we want to use this plugin for all languages then we'd have to add:
```
{
"editor.defaultFormatter": "esbenp.prettier-vscode"
}
```
=> chore: VS Code settings for JS/TS code formatting

assets/js/components/Forms/Submit.tsx
On pages that have a single form, it looks better when the submit button is in the center. Example is the project add page:
=> chore: Centered layout for submit area

assets/js/components/Forms/useSelectPersonField.tsx, assets/js/components/PeopleSearch/index.tsx, assets/js/features/Tasks/NewTaskModal/MultiPeopleSearch.tsx, assets/js/pages/ProjectAddPage/page.tsx, test/features/project_creation_test.exs, test/support/features/project_creation_steps.ex, test/support/features/ui.ex
My initial thought was to filter out the list and remove the champion from the review dropdown box. However, while testing this behavior, it felt wrong as it is giving me the impression that  Operately is not working when I'm searching for a person.
So I've done it with a validation. It is better to be explicit. If you select champion === reviewer, the message is very explicit:
=> feat: Prevent people from assigning themselves as both champion and reviewer

assets/js/pages/ProjectPage/CheckInSection.tsx, assets/js/pages/ProjectPage/index.tsx, test/features/project_creation_test.exs, test/support/features/project_creation_steps.ex
Ideally the link would lead you straight to a popup with a reviewer selection, but that is not yet feasible withe the current contrib page. It'll be added in some upcomming pull-requests.
related to: https://github.com/operately/operately/issues/591
=> feat: Show 'No Reviewer' callout when the project has no review

lib/operately_web/api/serializers/person.ex, test/features/account_settings_test.exs, test/support/features/account_settings_steps.ex
fixes https://github.com/operately/operately/issues/1074
When we introduced the possibility to edit other people's profile, we changed the API call from getMe to getPerson. The get person had no timezone exported, so it allowed setting the timezone, saving to the DB and also applying to the UI (via the getMe API call) but it would be set to null when you visit the profile edit page again.
=> fix: Show current timezone in profile settings

assets/js/models/projectContributors/index.tsx, assets/js/pages/ProjectContributorsPage/page.tsx
When reviewer == null, the project contrib page was raising 500.
=> fix: Fix contributor page if no reviewer is present

.projections.json
Alternates between feature tests and the steps when you type `:A` in vim.
In VSCode, it works with https://marketplace.visualstudio.com/items?itemName=will-wow.vscode-alternate-file.
=> chore: Alternative between feature files and steps

assets/js/components/Forms/FormState.tsx, assets/js/components/Forms/useForm.tsx, assets/js/pages/DesignPage/Forms.tsx
When we click submit or click, the form will reset to the initial state. Useful in places where we want to use the form multiple times.
=> chore: Introduce forms.reset

.semaphore/semaphore.yml
Based on this doc https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#semaphore_git_branch, when the workflow is started on a pull-request it will point to `main`.
To fix this, I'm also testing for the ref type.
=> chore: Don't attempt docker push in pull-requests

assets/js/components/Avatar/index.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/components/RichContent/index.tsx
As we have upgraded to React 18.3, we are getting warnings for things that will no longer work in React 19 once it comes out. Support for default props is one of them.
=> chore: Remove default props as they will not be supported in React 19

assets/js/components/Buttons/index.tsx
I wanted to use a secondary button on the dimmed section of the page, and it looked ugly because it was transparent.
=> chore: Always use white background for secondary buttons

assets/package-lock.json, assets/package.json
In `v5.7.1` the loading spinner had a default value prop that will no longer be supported in React 19.
=> chore: Fix warning on react-select for React 19 compatibility

lib/operately/activities/notifications/discussion_posting.ex, lib/operately/messages/notifications.ex, test/operately/operations/discussion_posting_test.exs, test/operately_web/api/mutations/post_discussion_test.exs
Now, `Operately.Activities.Notifications.DiscussionPosting` sends notifications based on the discussion's subscriptions list.
=> feat: DiscussionPosting notification uses subscriptions list

lib/operately/activities/notifications/discussion_comment_submitted.ex, lib/operately/operations/comment_adding/subscriptions.ex, test/operately/operations/comment_adding_test.exs, test/support/factory.ex, test/support/factory/messages.ex, test/support/fixtures/messages_fixtures.ex, test/support/fixtures/notifications_fixtures.ex
Now, `Operately.Activities.Notifications.DiscussionCommentSubmitted` sends notifications based on the discussion's subscriptions list.
=> feat: DiscussionCommentSubmitted notification uses subscriptions list

lib/operately/goals/notifications.ex, lib/operately/messages/notifications.ex, lib/operately/notifications/subscribers_loader.ex, lib/operately/projects/notifications.ex, test/operately/operations/comment_adding_test.exs
Previously, all the information needed for sending notifications was being loaded in a single query. However, in some edge cases, some notifications were not being sent.
To handle that, I separated the data loading process into two steps.
While working on this issue, I was able to identify a lot of repeated code, which I extracted to `Operately.Notifications.SubscribersLoader`.
=> fix: Notification subscribers were sometimes not loaded

assets/js/pages/ProjectPage/Banner.tsx, assets/js/pages/ProjectPausePage/page.tsx, assets/js/pages/ProjectResumePage/page.tsx
I was about to resume a project and noticed some room for improvement.
=> feat: Refine project pause dialog copy

assets/js/api/index.tsx, assets/js/pages/ProjectCheckInPage/loader.tsx, lib/operately/goals/notifications.ex, lib/operately/messages/notifications.ex, lib/operately/notifications/subscriber.ex, lib/operately/notifications/subscribers_loader.ex, lib/operately/projects/check_in.ex, lib/operately/projects/notifications.ex, lib/operately/projects/project.ex, lib/operately_web/api/queries/get_project_check_in.ex, lib/operately_web/api/serializers/project_check_in.ex, lib/operately_web/api/serializers/subscriber.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_project_check_in_test.exs, test/support/factory.ex, test/support/factory/projects.ex
Now, `OperatelyWeb.Api.Queries.GetProjectCheckIn` can also include potential subscribers.
=> chore: GetProjectCheckIn query can include potential subscribers

assets/js/components/PaperContainer/Navigation.tsx, assets/js/components/PaperContainer/index.tsx, assets/js/pages/DesignPage/index.tsx, assets/js/pages/GoalAddPage/page.tsx, assets/js/pages/GroupAppearancePage/page.tsx, assets/js/pages/GroupMembersPage/index.tsx, assets/js/pages/NewCompanyPage/index.tsx, assets/js/pages/ProjectAddPage/page.tsx, assets/js/pages/SpaceEditPage/page.tsx
Reducing duplication by introducing a `<NavigateBack to={...} title="Back to Lobby />` component.
=> chore: Extract navigate back to a single Paper component

assets/js/api/index.tsx, assets/js/pages/NewCompanyPage/index.tsx, assets/js/window.d.ts, config/runtime.exs, docker-compose.yml, lib/operately/demo.ex, lib/operately/demo/company.ex, lib/operately_web/api/mutations/add_company.ex, lib/operately_web/components/layouts/root.html.heex, test/operately/demo_test.exs
Turns out that with a couple of lines of code we can expose this in the UI. The new option is only available if the OPERATELY_DEMO_BUILDER_ALLOWED environment is set to true.
=> feat: Build a demo company

assets/js/api/index.tsx, lib/operately/goals/update.ex, lib/operately/notifications/subscriber.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, lib/operately_web/api/serializers/goal_update.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_goal_progress_update_test.exs, test/support/factory.ex, test/support/factory/goals.ex
Now, `OperatelyWeb.Api.Queries.GetGoalProgressUpdate` can also include potential subscribers.
=> chore: GetGoalProgressUpdate query can include potential subscribers

assets/js/components/Forms/Form.tsx, assets/js/components/Forms/useForm.tsx, assets/js/pages/DesignPage/Forms.tsx
This pull request introduces a new feature to allow forms to be submitted by pressing the Enter key. It also includes some code cleanup by removing unnecessary console logs. The most important changes include the addition of the `submitOnEnter` property to the form state and its usage in the form submission logic.
* [`assets/js/components/Forms/Form.tsx`](diffhunk://#diff-8eef0f58df09182a53c7bc8ee57659df335bf95574d4bf23ebdec783a6236672R7-R12): Modified the `onSubmit` function to check the `submitOnEnter` property before submitting the form.
* [`assets/js/components/Forms/useForm.tsx`](diffhunk://#diff-0291ddca8539a3cd36562be11acf3381bd9defb19540f71b87594029d0fe449aR12): Added the `submitOnEnter` property to the `FormProps` and `FormState` interfaces, and provided a default value in the …
=> chore: Disable auto-submit in forms

assets/js/api/index.tsx, lib/operately/goals/goal.ex, lib/operately/notifications/subscriber.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/serializers/goal.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_goal_test.exs
`OperatelyWeb.Api.Queries.GetGoal` can now include potential subscribers.
=> chore: GetGoal query can include potential subscribers

assets/js/features/PerfBar/index.tsx
Input type=text elements don't support ::before and ::after pseudo selectors. As a workaround, I'm injecting a mini label above every input field.
=> chore: Show testID annotations on input[text] elements

assets/js/api/index.tsx, assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/notifications/index.tsx, assets/js/features/notifications/useClearNotificationOnIntersection.tsx, assets/js/models/notifications.tsx, lib/operately/updates/comment.ex, lib/operately_web/api/queries/get_comments.ex, lib/operately_web/api/queries/get_notifications.ex, lib/operately_web/api/serializers/comment.ex, lib/operately_web/api/serializers/notifications.ex, lib/operately_web/api/types.ex
When a user sees a comment in a discussion, if there is an unread notification for this comment, the notification is marked as read.
https://github.com/user-attachments/assets/0d5d2947-e4bd-4cda-beb3-df7399fa500c
=> feat: Notifications are cleared when discussion comments are seen by user

assets/js/features/CommentSection/useForCommentThread.tsx, assets/js/pages/GoalActivityPage/index.tsx, lib/operately_web/api/queries/get_activity.ex, lib/operately_web/api/queries/get_comments.ex, lib/operately_web/api/serializers/activity.ex
Continuation of https://github.com/operately/operately/pull/1279.
Now, when a user sees a comment in a project check-in, project retrospective, goal update or goal discussion, if there is an unread notification for this comment, the notification is marked as read.
=> feat: Any comment notification is cleared when user sees comment

assets/js/api/index.tsx, assets/js/features/notifications/index.tsx, assets/js/features/notifications/useClearNotificationsOnLoad.tsx, assets/js/models/notifications.tsx, assets/js/pages/DiscussionPage/page.tsx, lib/operately/messages/message.ex, lib/operately/notifications.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/mark_notifications_as_read.ex, lib/operately_web/api/queries/get_discussion.ex, lib/operately_web/api/serializers/message.ex, lib/operately_web/api/types.ex, test/operately_web/api/mutations/mark_notifications_as_read_test.exs
From now on, when a user opens a discussion page, if there is an unread notification of the type `discussion_posting`, the notification will be marked as read.
I've also added the `MarkNotificationsAsRead` mutation, which can mark many of a user's notifications as read at once. 
This new mutation was probably not necessary for the discussion page since we are clearing only notifications of the type `discussion_posting` and, for any given discussion, a user should only ever have a single notification of this type. 
However, this mutation should be quite useful when we add the "clear-notification" functionality to pages that will clear different types of notifications, such as the project page.
=> feat: New discussion notification is cleared when discussion page loads

assets/js/api/index.tsx, assets/js/pages/ProjectCheckInPage/page.tsx, lib/operately/projects/check_in.ex, lib/operately_web/api/queries/get_project_check_in.ex, lib/operately_web/api/serializers/notifications.ex, lib/operately_web/api/serializers/project_check_in.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_discussion_test.exs, test/operately_web/api/queries/get_project_check_in_test.exs
Now, when a user opens a project check-in page, if there are unread notifications of the type `project_check_in_submitted` or `project_check_in_acknowledged`, the notifications will be marked as read.
=> feat: Project check-in notifications are cleared when check-in page loads

assets/js/api/index.tsx, assets/js/pages/ProjectPage/index.tsx, lib/operately/projects/project.ex, lib/operately_web/api/queries/get_project.ex, lib/operately_web/api/serializers/project.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_project_test.exs
Now, when a user opens a project page, if there are unread notifications related to the project, the notifications will be marked as read.
The notifications that will be marked as read are the following: 
- project_created 
- project_closed
- project_goal_connection
- project_moved
- project_pausing
- project_resuming
- project_timeline_edited
Those are the notifications that redirect the user to project page.
=> feat: Project notifications are cleared when project page loads

assets/js/api/index.tsx, assets/js/pages/GoalPage/index.tsx, lib/operately/goals/goal.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/serializers/goal.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_goal_test.exs
Now, when a user opens a goal page, if there are unread notifications related to the goal, the notifications will be marked as read.
The notifications that will be marked as read are the following:
- goal_created
- goal_editing
- goal_archived
Those are the notifications that redirect the user to the goal page.
=> feat: Goal notifications are cleared when goal page loads

assets/js/api/index.tsx, assets/js/pages/GoalActivityPage/index.tsx, lib/operately/activities/activity.ex, lib/operately/activities/permissions.ex, lib/operately_web/api/helpers.ex, lib/operately_web/api/queries/get_activity.ex, lib/operately_web/api/serializers/activity.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_activity_test.exs
Now, when a user opens a goal activity page, if there are unread notifications related to the goal activity, the notifications will be marked as read.
The notifications that will be marked as read are the following:
- goal_closing
- goal_reopening
- goal_timeframe_editing
Those are the notifications that redirect the user to the goal activity page.
=> feat: Goal Activity notifications are cleared when page loads

assets/js/api/index.tsx, assets/js/pages/GoalProgressUpdatePage/loader.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, lib/operately/goals/update.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, lib/operately_web/api/serializers/goal_update.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_goal_progress_update_test.exs
Now, when a user opens a goal update page, if there are unread notifications of the type `goal_check_in` or `goal_check_in_acknowledgement`, the notifications will be marked as read.
=> feat: Goal Update notifications are cleared when page loads

lib/operately/activities/content/project_created.ex, lib/operately/data/change_032_add_space_to_project_created_activity.ex, lib/operately/operations/project_creation.ex, priv/repo/migrations/20241010142306_add_space_field_to_project_created_activity.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_032_add_space_to_project_created_activity_test.exs
I've added a migration which adds the `space_id` key to all existing `project_created` activities.
I've also updated the `ProjectCreation` operation so that it adds the `space_id` key to new activities. 
=> fix: Add space to project_created activity content

assets/js/api/index.tsx, lib/operately_web/api/helpers.ex, lib/operately_web/api/ids.ex, lib/operately_web/api/mutations/add_group_members.ex, lib/operately_web/api/types.ex, lib/turbo_connect/api.ex, lib/turbo_connect/plugs/parse_inputs.ex, lib/turbo_connect/ts_gen.ex, lib/turbo_connect/ts_gen/typescript.ex, lib/turbo_connect/types.ex, test/turbo_connect/api_test.exs, test/turbo_connect/ts_gen_test.exs
Now, we can define custom primitive types for the API, for example, a primitive type for IDs.
Here is how it works: In the api type definition we can use the `primitive` to define a new primitive, what it will be encoded to in Typescript, and decoder for the values:
``` elixir
primitive :id, encoded_type: :string, decode_with: &Operately.Ids.decode_id/1
```
Before this Pull-Request, we would have to manually decode the types in the API handlers. For single values, this was manageable, but for nested or repeated values this would be a major pain. e.g:
``` elixir
inputs do
field :space_id, :string
field :members, :add_member_input
end
object :add_member_input do
field :id, :string
field :access_level, :string
end
```
To parse this in the API handler, you would need to do something crazy as: …
=> chore: Custom primitive types for the API

lib/operately/activities/content/project_resuming.ex, lib/operately/data/change_033_add_space_to_project_resuming_activity.ex, lib/operately/operations/project_resuming.ex, priv/repo/migrations/20241010162832_add_space_field_to_project_resuming_activity.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_033_add_space_to_project_resuming_activity_test.exs
I've added a migration which adds the space_id key to all existing `project_resuming` activities.
I've also updated the `ProjectResuming` operation so that it adds the space_id key to new activities.
=> fix: Add space to project_resuming activity content

lib/operately/activities/content/project_check_in_acknowledged.ex, lib/operately/activities/content/project_check_in_commented.ex, lib/operately/activities/content/project_check_in_submitted.ex, lib/operately/data/change_035_add_space_to_project_activities.ex, lib/operately/operations/comment_adding/activity.ex, lib/operately/operations/project_check_in.ex, lib/operately/operations/project_check_in_acknowledgement.ex, lib/operately_web/api/mutations/acknowledge_project_check_in.ex, lib/operately_web/api/mutations/create_comment.ex, priv/repo/migrations/20241010185006_add_space_to_project_check_in_activities.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_035_add_space_to_project_activities_test.exs, test/operately/operations/comment_adding_test.exs, test/operately_web/api/mutations/acknowledge_project_check_in_test.exs, test/operately_web/api/mutations/add_reaction_test.exs, test/operately_web/api/mutations/edit_comment_test.exs, test/operately_web/api/queries/get_comments_test.exs
I've added a migration which adds the space_id key to all existing `project_check_in_commented`, `project_check_in_submitted` and `project_check_in_acknowledged` activities.
I've also updated the operations which create these activities so that the space_id is added to new activities.
=> fix: Add space to project check-in activities

lib/operately/activities/content/project_archived.ex, lib/operately/activities/content/project_goal_connection.ex, lib/operately/activities/content/project_goal_disconnection.ex, lib/operately/data/change_036_add_space_to_project_activities.ex, lib/operately/operations/project_goal_connection.ex, lib/operately/operations/project_goal_disconnection.ex, lib/operately/projects.ex, priv/repo/migrations/20241011101759_add_space_key_to_project_activities.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_036_add_space_to_project_activities_test.exs, test/operately/operations/project_goal_disconnection_test.exs, test/support/factory/projects.ex
I've added a migration which adds the space_id key to all existing `project_archived`, `project_goal_connection` and `project_goal_disconnection` activities.
I've also updated the operations which create these activities so that the space_id is added to new activities.
=> fix: Add space to project_archived, project_goal_connection and project_goal_disconnection

lib/operately/activities/content/goal_editing.ex, lib/operately/data/change_038_add_space_to_goal_editing_activity.ex, lib/operately/operations/goal_editing.ex, priv/repo/migrations/20241011142317_add_space_to_goal_editing_activity.exs, test/features/goals_test.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_038_add_space_to_goal_editing_activity_test.exs, test/support/features/feed_steps.ex, test/support/features/goal_steps.ex
I've added a migration which adds the space_id key to all existing `goal_editing` activities.
I've also updated the `GoalEditing` operation so that it adds the space_id key to new activities.
=> fix: Add space to goal_editing activity

lib/operately/activities/content/project_timeline_edited.ex, lib/operately/data/change_039_add_space_to_project_timeline_edited_activity.ex, lib/operately/projects/edit_timeline_operation.ex, priv/repo/migrations/20241014102321_add_space_to_project_timeline_edited_activity.exs, test/features/project_timeline_test.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_039_add_space_to_project_timeline_edited_activity_test.exs, test/support/features/feed_steps.ex, test/support/features/project_timeline_steps.ex
I've added a migration which adds the space_id key to all existing `project_timeline_edtied` activities.
I've also updated the `EditTimelineOperation` operation so that it adds the space_id key to new activities.
=> fix: Add space to project_timeline_edtied activity

assets/js/pages/DiscussionPage/page.tsx, assets/js/utils/time.tsx, test/features/discussions_test.exs
Fixes https://github.com/operately/operately/issues/751.
First, I thought about displaying both the date and time when the discussion was posted, but it didn't look good. 
So, the approach I took was to render the `FormattedTime` component with `format="relative"` if the discussion was posted less than 24 hours ago, but render it with `format="short-date"` if the discussion was posted more than 24 hours. 
Here is how it looks:
https://github.com/user-attachments/assets/cf549698-59f6-4e19-adf9-63c4edb08639
=> feat: Improve how discussion posted time is displayed

assets/js/components/FormattedTime/RelativeTime.tsx, assets/js/components/FormattedTime/RelativeTimeOrDate.tsx, assets/js/components/FormattedTime/index.tsx, assets/js/components/FormattedTime/useRenderInterval.tsx, assets/js/pages/DiscussionPage/page.tsx, test/features/discussions_test.exs
Implementation of https://github.com/operately/operately/pull/1346.
Now, whenever we use `<FormattedTime time={time} format="relative" />`, the component will refresh on a specific interval. The refresh interval is shorter or longer depending on how long ago `time` is:
- if time < 1 minute, the interval is 15 seconds
- else if time < 1 hour, the interval is 60 seconds
- else if time < 1 day, the interval is 60 minutes
- else, the interval is a day
I've also added the format option `relative-time-or-date` to the `FormatTime` component, which displays the same result as ` format="relative"` if `time` is less than 24 hours ago, otherwise it displays the same result as ` format="relative-time-or-date"`.
=> feat: RelativeTime refreshes time on interval

assets/js/features/goals/GoalTree/tree-v2.tsx, assets/js/pages/GoalsAndProjectsPage/index.tsx, assets/js/pages/GoalsAndProjectsPage/loader.tsx, assets/js/pages/GoalsAndProjectsPage/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx
I've added the Goals V2 page. 
So far, the page only shows the existing Goals and Projects and the only functionality that is supported is collapse/expand a Goal's children.
The only way to access this page is to manually go to `/company-id/goals-v2`. The idea here is to add to the page all features it needs, test it well, then swap it with the old Goals page.
=> feat: Add Goals V2 page

assets/js/components/ProgressBar/index.tsx, assets/js/features/goals/GoalTree/context/Expandable.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx
Now, a goal's success conditions can be expanded and collapsed on the Goals V2 page:
https://github.com/user-attachments/assets/8e8cebca-c36e-4374-800d-51f22aeeef71
=> feat: Add goal success conditions to Goals V2 page

assets/js/api/index.tsx, assets/js/features/ProjectListItem/StatusIndicator.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx, assets/js/features/projectCheckIns/DescriptionSection.tsx, assets/js/features/projectCheckIns/SmallStatusIndicator.tsx, assets/js/features/projectCheckIns/StatusSection.tsx, assets/js/pages/GoalsAndProjectsPage/loader.tsx, assets/js/pages/ProjectCheckInPage/page.tsx, lib/operately_web/api/queries/get_projects.ex, test/operately_web/api/queries/get_projects_test.exs
I've added the project status to the Goals V2 page. When you click on it, a pop-up shows the latest check-in:
https://github.com/user-attachments/assets/e7f81cc8-042b-4493-9b05-d7f4ecbd154c
=> feat: Add latest project check-in to Goals V2 page

assets/js/features/goals/GoalTree/components/ProjectDetails.tsx
I've added a pie chart to show the project progress in the Goals V2 page:
=> feat: Add project progress chart to Goals V2 page

assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/CommentSection/useScrollIntoViewOnLoad.tsx, lib/operately_email/emails/comment_added_email.ex, lib/operately_email/emails/discussion_comment_submitted_email.ex, lib/operately_email/emails/goal_check_in_commented_email.ex, lib/operately_email/emails/project_check_in_commented_email.ex, lib/operately_email/emails/project_retrospective_commented_email.ex, lib/operately_web/paths.ex
Fixes https://github.com/operately/operately/issues/1376. I've added the same functionality to all comments, not only discussion comments.
I thought this issue could be fixed by simply appending `#id` to the URL, but it turned out that, since the comments are not loaded instantly with the page, some extra code was needed.
Also, we should expect this functionality not to work 100% as expected when there is layout shift on the page. 
I noticed this issue when I added some very long comments. The little moment that the long comments would take to load was enough to make the browser scroll to the wrong position on the page. I've added a 500ms delay which solved the problem for long comments and didn't affect the user experience (imo). Nevertheless, I expect we will still have this problem …
=> fix: "View Comment" button in email redirects you to the comment

assets/js/features/CommentSection/CommentSection.tsx, assets/js/features/Reactions/index.tsx, assets/js/features/goals/GoalCheckIn/index.tsx, assets/js/models/reactions/index.tsx, assets/js/pages/DiscussionPage/page.tsx, assets/js/pages/GoalActivityPage/index.tsx, assets/js/pages/GoalProgressUpdatePage/page.tsx, assets/js/pages/ProjectCheckInPage/page.tsx, assets/js/pages/ProjectRetrospectivePage/page.tsx
fixes: https://github.com/operately/operately/issues/1394
Previously the parent was declared as "string" so when we changed the name from "goal_update" -> "update" the linter didn't scream. Now, the type is an enum of strings.
=> fix: Adding reactions to goal updates and enforcing rules with enum types

assets/js/features/ProjectListItem/StatusIndicator.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx, assets/js/features/projectCheckIns/SmallStatusIndicator.tsx, assets/js/features/projectCheckIns/StatusSection.tsx, assets/js/pages/GoalsAndProjectsPage/loader.tsx
All project details are now displayed on the Goals V2 page.
=> feat: Add project details to Goals V2 page

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/tree-v2.tsx
"Add sub-goal" and "Create project" buttons are now displayed when the user hovers over a goal:
https://github.com/user-attachments/assets/f53dd3bf-d93e-4121-aca3-2e9630e00633
=> feat: Add goal actions to Goals V2 page

lib/operately_web/api/serializers/project.ex
This was the cause of some flaky tests, like this one: https://operately.semaphoreci.com/workflows/77f95d40-c31b-40a5-8248-00ffe01383ea/summary?pipeline_id=777dbb7d-bec6-47dc-9acd-76ab1aed83b8&report_id=31c127ba-6edc-33b1-9f53-fc4a54e74c82&test_id=c46e1b96-ec05-3e5a-9913-4b006ca8e450.
=> chore: Stabilize contributor ordering in the API

assets/js/api/index.tsx, assets/js/features/ProjectListItem/index.tsx, assets/js/pages/ProjectPage/Banner.tsx, assets/js/pages/ProjectRetrospectivePage/loader.tsx, assets/js/pages/ProjectRetrospectivePage/page.tsx, lib/operately/operations/project_closed.ex, lib/operately/projects/project.ex, lib/operately/projects/retrospective.ex, lib/operately_web/api/queries/get_project_retrospective.ex, lib/operately_web/api/serializers/project_retrospective.ex, priv/repo/migrations/20241024114823_add_closed_at_to_existing_closed_projects.exs
I've updated the `Operately.Operations.ProjectClosed` operation so that `closed_at` is now saved with the project, not the retrospective. 
I've also added a migration which updates the `closed_at` value in existing closed projects. Since this field used to be part of projects and it was never deleted, the migration didn't have to change the projects schema, only the values.
This should be enough to solve https://github.com/operately/operately/issues/1404.
=> chore: Move closed_at from retrospective to project

assets/js/api/index.tsx, assets/js/features/SpaceTools/Discussions.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/features/SpaceTools/components.tsx, assets/js/features/SpaceTools/index.tsx, assets/js/models/discussions/index.tsx, assets/js/models/goals/index.tsx, assets/js/models/projects/index.tsx, assets/js/pages/SpaceDiscussionsPage/loader.tsx, assets/js/pages/SpaceDiscussionsPage/page.tsx, assets/knip.json, lib/operately/messages/message.ex, lib/operately_web/api/queries/get_discussions.ex, lib/operately_web/api/serializers/message.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/get_discussions_test.exs, test/support/factory.ex, test/support/factory/comments.ex
I've started adding the new ToolsSection to the Space page. As this is going to be too much code for a single PR, I decided to build it in the `features/SpaceTools/` directory and add the directory to the ignore list in the `knip.json` file. This way the linter won't complain. 
To see how the component looks, we just need to add it to the Space page:
```
<ToolsSection space={space} />
```
I started building it by the Discussions tool. Here is how it looks:
I'm marking this PR as a draft because I think we could improve some things before merging it:
1) I'm using `Paper.DimmedSection`, that's why the background is not white as in the wireframe. The reason why I'm using it is because it calculates the negative margins, which is necessary for adding a new section to the page. I didn't manage …
=> feat: Add Discussions to space tools

assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/components.tsx
Now, a list of current goals and projects is displayed in the Goals & Projects tool:
=> feat: Display goals and projects space tools

assets/js/features/SpaceTools/Discussions.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/ToolsSection.tsx, assets/js/features/SpaceTools/components.tsx
When we hover over a tool, a subtle shadow appears:
https://github.com/user-attachments/assets/5199f1c4-db17-4f0d-81ea-0f29508c225f
Also, space tools are now responsive. 
2 tools:
https://github.com/user-attachments/assets/053f7c87-c6c0-48f0-ac68-ebc63013e7c5
5 tools: 
https://github.com/user-attachments/assets/d78f1155-694a-41f2-abd8-bd1dfbdb4fc9
=> feat: Space tools are responsive + hovering on them shows shadow

test/support/features/project_timeline_steps.ex, test/support/features/ui.ex
tldr: At the end of the month, two elements match the selector in the test:
=> chore: Fix flaky tests that appears at the end of the month

assets/js/pages/SpaceTemporaryV2Page/index.tsx, assets/js/pages/SpaceTemporaryV2Page/loader.tsx, assets/js/pages/SpaceTemporaryV2Page/page.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/knip.json
This is a copy of the space page where we can see and use the new Space Tools before it's deployed to the main space page. 
To access this page, we have to add `/v2` at the end of the space page URL. 
For example:
`http://localhost:4000/my-company-0bgq/spaces/my-space-EJ1vzAGsxzIF1NWUbKNjkg` -> `http://localhost:4000/my-company-0bgq/spaces/my-space-EJ1vzAGsxzIF1NWUbKNjkg/v2`
=> feat: Space Tools visible on space v2 page

assets/js/api/index.tsx, assets/js/components/status/Status.tsx, assets/js/components/status/constants.tsx, assets/js/components/status/index.tsx, assets/js/features/goals/GoalCheckInForm/Form.tsx, assets/js/features/goals/GoalCheckInForm/useForm.tsx, lib/operately/demo/goals.ex, lib/operately/goals/update.ex, lib/operately/operations/goal_check_in.ex, lib/operately/operations/goal_check_in_edit.ex, lib/operately_web/api/mutations/edit_goal_progress_update.ex, lib/operately_web/api/mutations/post_goal_progress_update.ex, lib/operately_web/api/serializers/goal_update.ex, lib/operately_web/api/types.ex, test/features/goal_progress_update_test.exs, test/operately/data/change_028_create_subscriptions_list_for_goal_updates_test.exs, test/operately/data/change_037_add_space_to_goal_update_activities_test.exs, test/operately/operations/comment_adding_test.exs, test/operately/operations/goal_check_in_test.exs, test/operately_web/api/mutations/edit_goal_progress_update_test.exs, test/operately_web/api/mutations/post_goal_progress_update_test.exs, test/support/features/goal_progress_update_steps.ex, test/support/features/review_steps.ex, test/support/features/subscriptions_steps.ex, test/support/fixtures/goals_fixtures.ex
I've added the "status" field to forms used to edit and create goal update. Now, all new goal updates will have a status.
=> feat: Add status field to goal update forms

lib/operately/data/change_040_add_status_value_for_existing_goal_updates.ex, priv/repo/migrations/20241030164401_pupulate_goal_updates_status_field_with_default_value.exs, test/operately/data/change_040_add_status_value_for_existing_goal_updates_test.exs
I've added a migration which populates the status field of existing goal updates with the `:on_track` value.
=> chore: Migration to populate status of existing goal updates

lib/mix/tasks/operately.gen.operation.ex, lib/mix/tasks/operation/gen_api_types.ex, test/mix/tasks/operately.gen.operation_test.exs
I was adding the company_owners_adding operation and struggled to get this right. If it is not defined in the API types, that means that it is not defined in Typescript as well, so you need to hunt it down.
---
After injection, this is what I see in tests:
Tagging @Rockyy174 to keep you in the loop how this works, I don't want to this to end up like "magic" code. Let me know if you have any questions or feedback how this works.
=> chore: Inject an api type definition for the generated activity content

assets/js/api/index.tsx, assets/js/features/activities/GoalCheckIn/index.tsx, assets/js/pages/GoalPage/index.tsx, lib/operately_web/api/serializers/activity.ex, lib/operately_web/api/serializers/activity_content/goal_check_in.ex, lib/operately_web/api/serializers/activity_content/goal_check_in_acknowledgement.ex, lib/operately_web/api/serializers/goal_update.ex, lib/operately_web/api/types.ex, test/features/goal_progress_update_test.exs, test/support/features/feed_steps.ex, test/support/features/goal_progress_update_steps.ex
Similarly to project check-in status, now a goal update status is also displayed in the feed:
While working on this, I realized that the changes in the targets were not being displayed in the feed. The reason why we didn't catch this before is because the activity content was referencing some old types, so TS wouldn't throw any error. 
I've updated the types and extended the feed tests, so this bug shouldn't appear again.
=> feat: Goal update feed item shows status

assets/js/features/SpaceTools/Discussions.tsx
In the discussions tool, when the title was too short, the comments count was displayed right next to it. In order to fix it, I had to replace flexbox by grid.
Before:
After:
=> fix: Discussions tool doesn't squeeze title and comments count

assets/js/features/SpaceTools/Discussions.tsx, assets/js/features/SpaceTools/GoalsAndProjects.tsx, assets/js/features/SpaceTools/components.tsx, assets/js/pages/SpaceDiscussionsPage/page.tsx
When a user doesn't have any goals, projects or discussions, a short message explaining the tool is shown to them:
I've added a similar message to the discussions page:
=> feat: Handle zero state in space tools

assets/js/pages/GoalProgressUpdatePage/page.tsx, test/support/features/goal_progress_update_steps.ex
The update status is now displayed on the goal update page:
=> feat: Show update status on goal update page

assets/js/features/activities/CommentAdded/index.tsx, lib/operately_email/emails/comment_added_email.ex, lib/operately_web/api/serializers/activity.ex, test/features/goals_test.exs, test/operately_web/api/queries/get_activities_test.exs, test/operately_web/api/queries/get_activity_test.exs, test/support/features/goal_steps.ex
Fixes https://github.com/operately/operately/issues/1473.
=> fix: Commenting on "goal reopening" doesn't break notifications page

assets/js/components/Buttons/OptionsButton.tsx, assets/js/components/status/Status.tsx, assets/js/features/goals/GoalCheckIn/DescriptionSection.tsx, assets/js/features/goals/GoalCheckIn/TargetsSection.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/components/Status.tsx, assets/js/features/projectCheckIns/DescriptionSection.tsx
The latest update/check-in is now displayed both when the user hovers over and clicks on the status. 
- When the user clicks on it, the popup is displayed until the user clicks outside of it. 
- When the user hovers over it for longer than a second, the popup is displayed until the user hovers outside of it for longer than a second.
https://github.com/user-attachments/assets/ce008b95-257e-4d77-9b6d-ec90b75bfdd8
Using `radix-ui/react-popover`, we got a nice popup that behaves nicely most of the time. However, it sometimes does some weird things, such as scrolling the window a little or changing the cursor from pointer to default. I spend some time trying to understand why it would sometimes behave like this, but couldn't find the reason. 
If it turns out that this behavior is not …
=> feat: Show latest update/check-in on hover

assets/js/features/goals/GoalTree/components/Status.tsx
When the Goals Tree is collapsed and there is no scroll on the page, if a status popup was too long, it would be outside of the viewport and there was no way to see it:
https://github.com/user-attachments/assets/494cd4e8-6e6b-491f-a0be-8317aceacf6b
I've limited the height of the popup so that is always stays within the viewport:
https://github.com/user-attachments/assets/48a9df4e-dda7-4f03-9cdd-9d3d614639cd
=> fix: Limit height of status popup on Goals page

assets/js/features/goals/GoalTree/components/Controls-v2.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/treeContext.tsx, test/features/goal_tree_test.exs, test/support/features/goal_tree_steps.ex
The user can now choose between the default and compact Goals tree view:
https://github.com/user-attachments/assets/913097fa-ff3c-41bc-bcd1-e0385acce9d2
=> feat: Add compact view option to Goals tree

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, test/features/goal_tree_test.exs
Success conditions are displayed when the view is compact:
https://github.com/user-attachments/assets/f9a6157c-3a5e-4ec8-a612-75887b64b7b4
=> fix: Display success conditions with compact view

assets/js/components/Avatar/index.tsx, assets/js/components/AvatarList/index.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/pages/SpaceGoalsPage/loader.tsx
The list of contributors was not being displayed on the SpaceGoalsPage goals tree because the contributors were not being loaded. 
In this PR, I've also: 
- aligned the Goal Champion avatar with the Goal Space
- replaced the custom avatar list by the new `AvatarList` component
- extended the `AvatarList` component and added the `linked` option. If it's true, clicking on the avatar will redirect the user to the person's profile
=> fix: Goals tree contributors and avatars

assets/js/pages/DiscussionPage/page.tsx
While fixing the projects navigation, I noticed that the discussions navigation has similar problems.
Before:
https://github.com/user-attachments/assets/91a2eec9-3f5c-43f3-a92c-b1c5ad18ef37
Now:
https://github.com/user-attachments/assets/9f81f2ce-47b4-4cf6-aa15-731b7d8f7935
=> fix: Fix discussions navigation

assets/js/pages/SpacePage/page.tsx
Now that we don't have the top navigation we can reduce the top margin to take up less space on smaller screens.
Before:
After:
=> chore: Reduce top padding for space title

assets/js/components/PaperContainer/PageOptions.tsx, assets/js/components/SpacePageNavigation/index.tsx
Adjusting the menu now that we no longer have a top bar. Wider circle, and the menu behaves like in other places like projects and goals.
Before:
https://github.com/user-attachments/assets/fdf0f8bc-7ebf-4293-aca2-307a02634fc7
After:
https://github.com/user-attachments/assets/f74800fd-bbd9-4a8e-9b88-b4b70db9834d
=> chore: Fix menu on space page

assets/js/features/SpaceTools/components.tsx
A bit smaller text for the title, a bit more accented shadows.
Before:
After:
Originally, I also wanted to change the aspect ratio to be more wide than tall, but after fiddling around, I started to like the more-tall-then-wide. It resembles a "paper" and when you click on it you "expand" the paper.
=> chore: Adjust font sizes and borders

assets/js/features/goals/GoalTree/components/Controls.tsx, assets/js/features/goals/GoalTree/index.tsx
Reducing the visual sharpness of secondary elements.
Before:
After:
=> chore: Adjust visuals on the goals & projects page

assets/js/features/SpaceTools/GoalsAndProjects.tsx
Fixes https://github.com/operately/operately/issues/1512.
=> fix: Show only open Goals/Projects in space tools

assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/index.tsx
Before this the chevrons were "flowing out" to the margins of the page. Small tweaks to keep everything inside.
Before:
After:
=> chore: Small tweaks in paddings

assets/js/components/ProgressBar/index.tsx, assets/js/features/goals/GoalTree/components/GoalDetails.tsx, assets/js/features/goals/GoalTree/components/NodeName.tsx, assets/js/features/goals/GoalTree/components/ProjectDetails.tsx, assets/js/features/goals/GoalTree/index.tsx, assets/js/pages/GoalsAndProjectsPage/page.tsx
Fixes https://github.com/operately/operately/issues/1530.
Regarding decreasing the font-size, it didn't seem to make a big difference and, in the resource details, the font is already pretty small.
Something that still doesn't look good in my opinion is the "add sub-goal" and "create project" buttons. I'm not really sure what to do with them when we run out of space. Is it an option to hide them when the screen is in the "xs" breakpoint?
https://github.com/user-attachments/assets/9cb07b66-fc08-4c7c-aecb-eaf223724411
=> feat: Goals page is responsive

assets/js/api/index.tsx, lib/operately/activities/content/resource_hub_folder_created.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/resource_hub_folder_created.ex, lib/operately/operations/resource_hub_folder_creating.ex, lib/operately/resource_hubs.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/permissions.ex, lib/operately_web/api.ex, lib/operately_web/api/mutations/create_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex, lib/operately_web/paths.ex, priv/repo/migrations/20241111124913_add_timestamps_to_resource_nodes_and_folders.exs, test/operately_web/api/mutations/create_resource_hub_folder_test.exs, test/support/factory.ex, test/support/factory/resource_hubs.ex, test/support/fixtures/resource_hubs_fixtures.ex
I've added an operation for creating folders in the resource hub.
There are two things still missing:
1) I haven't tested the permissions because we don't have a way to create a resource hub with all the necessary bindings yet, which makes it very hard to set up tests. So, I decided to add these tests after I add an operation for creating resource hubs.
2) I haven't added the "resource_hub_folder_created" event to the feed, because we don't have a way to trigger this operation from the UI yet. After we have a way of triggering this operation in the UI, I will add this event to the feed and write some feature tests for it.
As this PR is already getting too big, I will handle these 2 details in upcoming PRs. I made sure to add these 2 todos as tasks in our project, so we won't forget about …
=> feat: Add CreateResourceHubFolder operation

assets/js/api/index.tsx, lib/operately_web/api/queries/list_resource_hub_content.ex, lib/operately_web/api/types.ex, test/operately_web/api/queries/list_resource_hub_content_test.exs, test/support/factory/resource_hubs.ex, test/support/fixtures/resource_hubs_fixtures.ex
The query `ListResourceHubContent` can be used to list the contents of both a Resource Hub root and a folder.
=> feat: ListResourceHubContent query can list folder content

lib/operately/data/change_043_create_access_bindings_between_resource_hubs_and_people.ex, priv/repo/migrations/20241115093941_create_access_bindings_between_resource_hubs_and_company_members.exs, test/operately/data/change_043_create_access_bindings_between_resource_hubs_and_people_test.exs
It turned out that the bindings between the resource hubs and access groups were not created in the previous migrations. I'm fixing that in this PR.
=> fix: Create bindings between existing resource hubs and groups

assets/js/features/goals/GoalTree/index.tsx
Fixes https://github.com/operately/operately/issues/1559.
https://github.com/user-attachments/assets/a3440950-8be8-4b6d-918e-65f7d5d96566
=> fix: On Goals page, don't show icon when Goal has no children

lib/operately_web/api/queries/get_resource_hub.ex
Display only folders and documents that don't have a parent folder in the Resource Hub root.
=> fix: Sub-folders are not listed in the resource hub root

lib/operately/groups/insert_group.ex, test/operately/access/bindings_test.exs, test/operately/data/change_041_create_one_resource_hub_for_each_existing_space_test.exs, test/operately/operations/group_creation_test.exs, test/operately/operations/resource_hub_creating_test.exs, test/operately_web/api/mutations/create_resource_hub_test.exs, test/operately_web/api/queries/list_space_tools_test.exs
When a Space is created, a Resource Hub is also created for it. This will be necessary until we have a way to manually create Resource Hubs.
=> feat: Creating space also creates default resource hub

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubDocumentCommented/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities/content/resource_hub_document_commented.ex, lib/operately/operations/comment_adding/activity.ex, lib/operately_web/api/mutations/create_comment.ex, lib/operately_web/api/serializers/activity_content/resource_hub_document_commented.ex, lib/operately_web/api/types.ex
The `ResourceHubDocumentCommented` event is now displayed in the feed.
=> feat: Display document-commented event in feed

assets/js/api/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/pages/ResourceHubFolderPage/loader.tsx, assets/js/pages/ResourceHubPage/loader.tsx, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_folder.ex, lib/operately_web/api/types.ex
Now, a preview of a document's content and a folder's children count is displayed in the Resource Hub items list:
https://github.com/user-attachments/assets/09d904a1-1760-4d78-a413-f630824757f6
=> feat: Add subtitle to resource hubs items

assets/js/api/index.tsx, assets/js/pages/ResourceHubDocumentPage/loader.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, lib/operately/resource_hubs/document.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex
When the document page loads, `ResourceHubDocumentCreated` and `ResourceHubDocumentEdited` unread notifications are automatically marked as read.
=> feat: Document notifications are cleared when page loads

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFileCreated/index.tsx, assets/js/features/activities/index.tsx, assets/js/routes/paths.tsx, lib/operately/activities/preloader.ex, lib/operately_web/api/serializers/activity_content/resource_hub_file_created.ex, lib/operately_web/api/types.ex
The `ResourceHubFileCreated` event is now displayed in the feed.
=> feat: Display file-created event in feed

Makefile
Unit tests now also use the `tests_with_retries` task.
=> chore: Add retries to unit tests

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFileDeleted/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_file_deleted.ex, lib/operately_web/api/types.ex
The `ResourceHubFileDeleted` event is now displayed in the feed.
=> feat: Display file-deleted event in feed

assets/js/features/activities/GoalCheckInCommented/index.tsx, test/features/goal_progress_update_test.exs, test/support/features/goal_progress_update_steps.ex
Fixes https://github.com/operately/operately/issues/1673.
=> fix: Goal-update-commented notification redirects to correct page

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFileCommented/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_file_commented.ex, lib/operately_web/api/types.ex
The `ResourceHubFileCommented` event is now displayed in the feed.
=> feat: Display file-commented event in feed

assets/js/components/Image/ImageWithPlaceholder.tsx, assets/js/components/Image/index.tsx, assets/js/pages/ResourceHubFilePage/Content.tsx, lib/operately_web/api/serializers/resource_hub_file.ex
I've added an image component which shows a placeholder while the image is loading. Without this component, loading the file page was very chaotic:
https://github.com/user-attachments/assets/5be534a7-80a0-4cab-8b02-bca7c804ee6f
Now everything stays in the same place:
https://github.com/user-attachments/assets/9856f777-e29b-4330-be56-7134aae2b31c
=> feat: Add ImageWithPlaceholder component

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFolderRenamed/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_folder_renamed.ex, lib/operately_web/api/types.ex
The `ResourceHubFolderRenamed` event is now displayed in the feed.
=> feat: Display folder-renamed event in feed

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFolderDeleted/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_folder_deleted.ex, lib/operately_web/api/types.ex
The `ResourceHubFolderDeleted` event is now displayed in the feed.
=> feat: Display folder-deleted event in feed

assets/js/api/index.tsx, assets/js/features/ResourceHub/AddFiles.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/models/blobs/index.tsx, assets/js/models/blobs/utils.tsx, lib/operately/operations/resource_hub_file_creating.ex, lib/operately/resource_hubs/file.ex, lib/operately_web/api/mutations/create_resource_hub_file.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/types.ex, priv/repo/migrations/20241209142058_add_preview_blob_relationship_between_files_and_blobs.exs
When an image is uploaded, a very small version of it is now also uploaded as the file's `preview blob`. Then, in the Resource Hub items list, this small image is used to show a preview of the image in the list.
=> feat: Display image preview in resource hub

assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/features/ResourceHub/utils.tsx, assets/js/features/SpaceTools/ResourceHub.tsx, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api/queries/list_space_tools.ex
On the Space page, the Resource Hub tool shows the appropriate icon and subtitle depending on the resource type.
=> feat: Display resource hub item's icon and subtitle on space page

assets/js/api/index.tsx, assets/js/features/ResourceHub/components/FolderMenu.tsx, assets/js/models/resourceHubs/index.tsx, assets/js/pages/ResourceHubDocumentPage/Options.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, lib/operately_web/api/serializers/resource_hub_permissions.ex, lib/operately_web/api/types.ex
I've added the option to delete folders from the resource hub page.
I've also added the option to delete a document from the document page. Previously, we could delete them only from the resource hub page.
=> feat: Folders can be deleted

assets/js/components/Buttons/OptionsButton.tsx, assets/js/features/ResourceHub/AddFilesButton.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, assets/js/pages/ResourceHubPage/page.tsx
Fixes https://github.com/operately/operately/issues/1717 and https://github.com/operately/operately/issues/1718.
The migration 043 gave comment access to space members, so it makes sense that @markoa is getting 403s. Now, the action buttons are displayed only to members who have permissions to perform those actions.
=> fix: Display resource hub actions only if user has permissions

lib/operately/resource_hubs/resource_hub.ex, test/operately_web/api/mutations/add_reaction_test.exs, test/operately_web/api/mutations/create_comment_test.exs, test/operately_web/api/mutations/create_resource_hub_document_test.exs, test/operately_web/api/mutations/create_resource_hub_file_test.exs, test/operately_web/api/mutations/create_resource_hub_folder_test.exs, test/operately_web/api/mutations/delete_resource_hub_document_test.exs, test/operately_web/api/mutations/delete_resource_hub_file_test.exs, test/operately_web/api/mutations/delete_resource_hub_folder_test.exs, test/operately_web/api/mutations/edit_parent_folder_in_resource_hub_test.exs, test/operately_web/api/mutations/edit_resource_hub_document_test.exs, test/operately_web/api/mutations/rename_resource_hub_folder_test.exs, test/operately_web/api/queries/get_resource_hub_document_test.exs, test/operately_web/api/queries/get_resource_hub_file_test.exs, test/operately_web/api/queries/get_resource_hub_folder_test.exs, test/operately_web/api/queries/get_resource_hub_test.exs, test/operately_web/api/queries/list_space_tools_test.exs
Access to Resource Hubs was based on the Resource Hub's access context. Now, it will be based on the Space's access context.
=> chore: Resource Hub and Space use the same access context

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFileEdited/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_file_edited.ex, lib/operately_web/api/types.ex
The `ResourceHubFileEdited` event is now displayed in the feed.
=> feat: Display file-edited event in feed

assets/js/features/ResourceHub/components/MoveResources/FolderSelectField.tsx
Fixes https://github.com/operately/operately/issues/1737.
https://github.com/user-attachments/assets/87a1f32d-93bf-460e-8a56-460e71241e5a
=> fix: Items in move-file form don't overflow the container

lib/operately/data/change_044_rename_resource_hubs.ex, lib/operately/groups/insert_group.ex, priv/repo/migrations/20241219153512_rename_existing_resource_hubs_to_documents_and_files.exs, test/features/resource_hub_test.exs, test/operately/data/change_044_rename_resource_hubs_test.exs, test/support/features/resource_hub_steps.ex
Fixes https://github.com/operately/operately/issues/1741.
=> chore: Rename existing Resource Hubs to "Documents & Files"

assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/components/ZeroNodes.tsx, assets/js/features/ResourceHub/components/index.tsx, test/features/resource_hub_test.exs, test/support/features/resource_hub_steps.ex
Fixes https://github.com/operately/operately/issues/1732.
This is how the page looks like now:
=> chore: Improve resource hub zero-state copy

assets/js/api/index.tsx, assets/js/features/Comments/CommentsCountIndicator.tsx, assets/js/features/Comments/index.tsx, assets/js/features/ResourceHub/NodesList.tsx, assets/js/features/ResourceHub/utils.tsx, assets/js/features/SpaceTools/Discussions.tsx, assets/js/pages/ResourceHubFolderPage/loader.tsx, assets/js/pages/ResourceHubPage/loader.tsx, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/file.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/node.ex, lib/operately/resource_hubs/resource_hub.ex, lib/operately_web/api/queries/get_resource_hub.ex, lib/operately_web/api/queries/get_resource_hub_folder.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_file.ex, lib/operately_web/api/types.ex, test/features/resource_hub_test.exs, test/operately_web/api/mutations/edit_resource_hub_document_test.exs, test/support/features/resource_hub_steps.ex, test/support/features/ui.ex, test/support/fixtures/resource_hubs_fixtures.ex
Fixes https://github.com/operately/operately/issues/1745.
The logic for loading the comments count is in place. Since comments count is something we will have to display in many places, I made a component for it.
I'm just not sure where it looks better. Here is what it looks like right after the description:
And here is what it looks like at the end of the container:
If we decide to go with the second picture, then this PR should be ready. If the first picture is better, then I would have to remove the last commit.
Also, if you think the count would look better positioned somewhere else, just let me know!
=> feat: Display comments count for documents and files

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubLinkCreated/index.tsx, assets/js/features/activities/index.tsx, assets/js/routes/paths.tsx, lib/operately/activities/preloader.ex, lib/operately_web/api/serializers/activity_content/resource_hub_link_created.ex, lib/operately_web/api/types.ex
The `ResourceHubLinkCreated` event is now displayed in the feed.
=> feat: Display link-created event in feed

test/support/features/ui.ex
If the next month selected in the date picker was January, the `select_day_in_datepicker` function would not work. Now it works.
=> fix: Fix select_day_in_datepicker function used for tests

assets/js/models/blobs/index.tsx, assets/js/models/blobs/utils.tsx, assets/js/pages/ResourceHubFilePage/loader.tsx, assets/js/pages/ResourceHubFilePage/page.tsx
Fixes https://github.com/operately/operately/issues/1747.
I decided to display the required information similarly to how we display it for rich-text files:
=> feat: Show file size and download button on file page

assets/js/pages/SpaceAddPage/index.tsx
Tiny detail but it would be wrong to lead people to think that it is optimal to have " Team" appended to every space name.
=> docs: New space form, remove 'team' from form tip

assets/js/api/index.tsx, assets/js/components/PaperContainer/Navigation.tsx, assets/js/features/ResourceHub/NestedFolderNavigation.tsx, assets/js/features/ResourceHub/index.tsx, assets/js/pages/ResourceHubDocumentPage/loader.tsx, assets/js/pages/ResourceHubDocumentPage/page.tsx, assets/js/pages/ResourceHubFolderPage/page.tsx, lib/operately/resource_hubs/document.ex, lib/operately/resource_hubs/folder.ex, lib/operately/resource_hubs/node.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/serializers/resource_hub_document.ex, lib/operately_web/api/types.ex, test/features/resource_hub_test.exs, test/support/features/resource_hub_steps.ex
The navigation in the Document page now includes to all the document's nested parent folders, resource hub and space:
https://github.com/user-attachments/assets/dd37639b-e962-442f-9035-441ee6a1f528
=> fix: Document navigation includes complete path back to the space

assets/js/pages/GoalsAndProjectsPage/page.tsx, assets/js/pages/SpaceGoalsPage/page.tsx
fixes https://github.com/operately/operately/issues/1783
+ uses the now standard title=center actions=left layout
=> feat: Rename goals page to Goal map

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubLinkDeleted/index.tsx, assets/js/features/activities/feedItemLinks.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_link_deleted.ex, lib/operately_web/api/types.ex, test/features/resource_hub_link_test.exs, test/features/resource_hub_test.exs, test/support/features/resource_hub_link_steps.ex, test/support/features/resource_hub_steps.ex
The `ResourceHubLinkDeleted` event is now displayed in the feed.
=> feat: Display link-deleted event in feed

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubLinkEdited/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_link_edited.ex, lib/operately_web/api/types.ex, test/features/resource_hub_link_test.exs, test/support/features/resource_hub_link_steps.ex
The `ResourceHubLinkEdited` event is now displayed in the feed.
=> feat: Display link-edited event in feed

lib/operately_email/emails/resource_hub_document_commented_email.ex, lib/operately_email/emails/resource_hub_document_created_email.ex, lib/operately_email/emails/resource_hub_document_deleted_email.ex, lib/operately_email/emails/resource_hub_document_edited_email.ex, lib/operately_email/emails/resource_hub_file_commented_email.ex, lib/operately_email/emails/resource_hub_file_created_email.ex, lib/operately_email/emails/resource_hub_file_deleted_email.ex, lib/operately_email/emails/resource_hub_link_commented_email.ex, lib/operately_email/emails/resource_hub_link_created_email.ex, test/support/features/resource_hub_link_steps.ex, test/support/features/resource_hub_steps.ex
Fixes https://github.com/operately/operately/issues/1791.
=> fix: Display space name in subject of Resource Hub emails

priv/repo/migrations/20250103173929_update_blob_size_field_from_int_to_bigint.exs
We were storing the size of files as integers in the `blobs` schema. However, as we were storing the size of files as its number of bytes, a large file would have too many bytes and wouldn't fit in the Postgres integer field. After modifying the size field from integer to bigint, uploads of large files started working.
I'm not sure if these changes will be enough to fix the issue in production, but it was enough to fix it locally.
=> fix: Handle large files

rel/single-host/templates/install.sh.eex
Previously, the installation script was generating a blob secret token, but wasn't injecting it into the .env file. This PR fixes this issue.
=> fix: Blob token secret is added to .env during installation

Dockerfile.prod, rel/single-host/templates/install.sh.eex
In the `Dockerfile.prod` file, the ownership of /media directory is changed. Also, the blob token is now generated using `-base64` instead of `-hex`.
=> fix: Change ownership of /media directory in Dockerfile.prod

assets/js/api/index.tsx, assets/js/models/blobs/index.tsx, lib/operately_web/api/mutations/create_blob.ex, lib/operately_web/api/types.ex, test/operately_web/api/mutations/create_blob_test.exs
We can now use the `OperatelyWeb.Api.Mutations.CreateBlob` mutation to create multiple blobs at once.
=> chore: CreateBlob mutation can be used to create multiple blobs

assets/js/components/RichContent/contentOps.test.tsx, assets/js/components/RichContent/contentOps.tsx, assets/js/features/ResourceHub/components/FolderMenu.tsx, assets/js/pages/ResourceHubEditDocumentPage/form.tsx, assets/js/pages/ResourceHubEditFilePage/form.tsx, assets/js/pages/ResourceHubEditLinkPage/form.tsx, test/features/resource_hub_link_test.exs, test/features/resource_hub_test.exs, test/support/features/resource_hub_link_steps.ex, test/support/features/resource_hub_steps.ex
Resource Hub editing operations now don't make an API call if the data hasn't changed. If a user clicks on "Save" without making any changes to the data, they are just redirected back to the resource page.
This applies to documents, links, files and folders.
=> fix: Resource Hub editing operations don't hit the API when the resource doesn't change

Makefile, assets/js/features/goals/GoalTree/tree/buildTree.test.tsx, assets/js/features/goals/GoalTree/tree/buildTree.tsx, assets/js/features/goals/GoalTree/tree/node.tsx
Previously if we had the following structure:
```
G1 Company
G2 Marketing
G3 Product
```
We would should only marketing goals on the marketing space (no ancestors):
```
G2 Marketing
G3 Product
```
Now, we are showing the full lineage:
```
G1 Company
G2 Marketing
G3 Product
```
=> feat: Show ancestors and descendants of goals when filtering by space

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubFolderCopied/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_folder_copied.ex, lib/operately_web/api/types.ex
The `ResourceHubFolderCopied` event is now displayed in the feed.
=> feat: Display folder-copied event in feed

assets/js/components/FormTitleInput/index.tsx, assets/js/features/DiscussionForm/Form.tsx, assets/js/features/DiscussionForm/useForm.tsx, test/features/discussions_test.exs, test/support/features/discussions_steps.ex
fixes https://github.com/operately/operately/issues/1871
=> feat: Allow posting draft discussion with blank body and add validation message if the title is empty

assets/js/api/index.tsx, assets/js/features/activities/ResourceHubLinkCommented/index.tsx, assets/js/features/activities/index.tsx, lib/operately_web/api/serializers/activity_content/resource_hub_link_commented.ex, lib/operately_web/api/types.ex, test/features/resource_hub_link_test.exs, test/support/features/resource_hub_link_steps.ex
The `ResourceHubLinkCommented` event is now displayed in the feed.
=> feat: Display link-commented event in feed

assets/js/api/index.tsx, assets/js/pages/ResourceHubLinkPage/loader.tsx, assets/js/pages/ResourceHubLinkPage/page.tsx, lib/operately/goals/goal.ex, lib/operately/goals/update.ex, lib/operately/groups/group.ex, lib/operately/messages/message.ex, lib/operately/notifications/unread_notifications_loader.ex, lib/operately/projects/check_in.ex, lib/operately/projects/project.ex, lib/operately/projects/retrospective.ex, lib/operately/resource_hubs/document.ex, lib/operately_web/api/queries/get_discussion.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/queries/get_goal_progress_update.ex, lib/operately_web/api/queries/get_project.ex, lib/operately_web/api/queries/get_project_check_in.ex, lib/operately_web/api/queries/get_project_retrospective.ex, lib/operately_web/api/queries/get_resource_hub_document.ex, lib/operately_web/api/queries/get_resource_hub_link.ex, lib/operately_web/api/queries/get_space.ex, lib/operately_web/api/types.ex
When a Resource Hub resource page loads, unread notifications related to that resource are marked as read.
I've added `Operately.Notifications.UnreadNotificationsLoader` and was able to remove a lot of repeated code.
=> feat: Resource Hub notifications are marked as read when page loads

assets/js/features/activities/ResourceHubFileCommented/index.tsx, assets/js/features/activities/ResourceHubFileCreated/index.tsx, assets/js/features/activities/ResourceHubFileDeleted/index.tsx
I was trying to find out why the notifications page was crashing, as described in https://github.com/operately/operately/issues/1925. 
I couldn't find the reason precisely. However, judging by the error in the console, it seems that the bug is caused by a `null` value in a file page path. So, in this PR I'm adding some assertions to the file notifications. Hopefully, this will enable me to find out which activity has null values.
=> chore: Add assertions to file notification activities

assets/js/api/index.tsx, assets/js/features/activities/GoalReparent/index.tsx, assets/js/features/activities/index.tsx, lib/operately/activities.ex, lib/operately/activities/content/goal_reparent.ex, lib/operately/activities/context_auto_assigner.ex, lib/operately/activities/notifications/goal_reparent.ex, lib/operately/data/change_048_delete_goal_reparent_activities_with_missing_data.ex, lib/operately/operations/goal_reparent.ex, lib/operately_email/emails/goal_reparent_email.ex, lib/operately_email/templates/goal_reparent.html.eex, lib/operately_email/templates/goal_reparent.text.eex, lib/operately_web/api/serializers/activity.ex, lib/operately_web/api/serializers/activity_content/goal_reparent.ex, lib/operately_web/api/types.ex, priv/repo/migrations/20250124144013_delete_goal_reparent_activities_with_missing_data.exs, test/features/goal_test.exs, test/operately/access/activity_context_assigner_test.exs, test/operately/data/change_048_delete_goal_reparent_activities_with_missing_data_test.exs, test/support/features/goal_steps.ex
Fixes https://github.com/operately/operately/issues/1917.
This was a tricky problem. Currently, `GoalReparent` activities only have the `company`, `old_parent_goal` and `new_parent_goal` in its content, but they lack a reference to the specific goal that was reparented. This makes it impossible to determine which goal the activity belongs to.
When there is missing data in an activity, the solution is usually to run a data migration to add/create the missing data. However, in this case, I didn't see any way to find out which goal the activity belonged to.
Another problem is that currently we don't have a clean way to filter out activities that have missing data. So, the activities with missing data were breaking the feed. 
Of course, I could handle those activities so that they don't break …
=> fix: GoalReparent event appears in the feed and sends notifications

assets/js/features/Permissions/PermissionSelector.tsx, assets/js/features/Permissions/usePermissionsState.tsx, assets/js/features/goals/GoalForm/useForm.tsx
- The new default permission for company members is "Comment".
- When creating a goal, the default access level is "Internal".
- When you change the space, the permissions remain as they were.
=> fix: Change Goal permissions default

assets/js/pages/CompanyAdminManagePeoplePage/index.tsx, assets/js/pages/CompanyAdminPage/page.tsx, assets/js/pages/CompanyAdminRestoreSuspendedPeoplePage/index.tsx, test/support/features/company_admin_steps.ex
Following claud's advice to make this flow clearer:
- Using "Deactivate Account" instead of "Remove".
- Using a longer label on the company admin page. These are not common actions, so on the rare occasions you use them they should be clear.
- Using "Reactivate" instead of "Restore suspended"
---
The other good suggestion from Claude was to use "Off board" / "Re-instate". I opted to not use the word off board as that would imply a longer process, not just a one-click action. If we implement a longer process like a screen that re-assigns the offboarded person's projects to someone else, then we can come back to use that term.
fixes https://github.com/operately/operately/issues/1766
=> fix: Use deactivate/reactivate instead of remove/restore suspended

assets/js/api/index.tsx, assets/js/pages/ReviewPage/AssignmentsList.tsx, lib/operately/assignments/assignment.ex, lib/operately/assignments/loader.ex, lib/operately_web/api/queries/get_assignments.ex, lib/operately_web/api/serializers/assigments.ex, lib/operately_web/api/types.ex, test/features/review_test.exs, test/operately/assignments/loader_test.exs, test/operately_web/api/queries/get_assignments_test.exs, test/support/factory.ex, test/support/factory/projects.ex, test/support/features/review_steps.ex
I've added a new module for loading a person's assignments. The `GetAssignments` query has already been updated to use the new loader.
In my next PR, I plan to update `OperatelyEmail.Emails.AssignmentsEmail` so that the emails and the Review page use the same data.
It's worth noting that the emails include due milestones, while the Review page does not. I've ensured that milestones won't break the page, but we might want to either display due milestones on the Review page or remove them from the emails to maintain consistency between the emails and the Review page.
=> chore: Add Operately.Assignments.Loader

assets/js/features/activities/GoalCheckIn/ConditionChanges.tsx, assets/js/features/goals/GoalCheckIn/TargetsSection.tsx, assets/js/features/goals/GoalCheckInForm/Form.tsx, assets/js/pages/GoalDiscussionsPage/index.tsx
Fixes https://github.com/operately/operately/issues/1716.
Now, long success conditions should no longer overflow the page. I've checked and handled the issue in following places: 
- Activities feed
- Goal discussions page
- Goal progress update page
- Goal progress update new page
As for the `undefined` comments count, solving it is complex as `Operately.Activities.Preloader` will have to be extended. @shiroyasha and I discussed the issue and decided that for now the comments count won't be displayed on the page. 
A new issue will be opened for extending the activities preloader and adding the comments count back to the page.
=> fix: Goal progress update no longer overflows the container

lib/operately/assignments/filter_late_assignments.ex, lib/operately/assignments/loader.ex, lib/operately_web/api/queries/get_assignments.ex, test/operately/assignments/filter_late_assignments_test.exs, test/operately/assignments/loader_test.exs, test/support/factory.ex, test/support/factory/companies.ex
Now, `Operately.Assignments.Loader` returns both a given person's assignments and the assignments of the people reporting to that person in the company hierarchy. Both lists use the new `Assignment` struct.
However, I’m not entirely sure if the criteria for filtering late and on-time assignments are correct. However, I’ve kept the filtering logic isolated, so if we need to update it, it should be easy and quick.
=> chore: Assignments.Loader includes reports' assignments

assets/js/app.tsx, assets/js/components/Forms/TextInput.tsx, assets/js/components/Modal/index.tsx
fixes https://github.com/operately/operately/issues/1963
---
I learned way too much details about autofocus today. 🙉 
TLDR: It is a completely broken feature in browsers, React decided to roll their 
own monkeypatch called autoFocus  which is different than autofocus.
Neither of them work out of the box, reliably, in modals.
---
In this PR I'm implementing a manual autofocus mechanism that triggers the first auto-focusable element in the modal.
=> fix: Autofocus in modals

assets/js/features/CommentSection/CommentSection.tsx
Fixes https://github.com/operately/operately/issues/1946:
=> fix: Align milestone comment and avatar

assets/js/features/activities/ResourceHubDocumentCreated/index.tsx
Fixes https://github.com/operately/operately/issues/1993.
=> fix: Created-document feed event is now aligned

assets/js/features/activities/ResourceHubLinkCreated/index.tsx
Fixes https://github.com/operately/operately/issues/1994.
=> fix: link-created event doesn't display link in the feed

assets/js/components/Tooltip/index.tsx, assets/js/features/spaces/PrivacyIndicator/index.tsx
Fixes https://github.com/operately/operately/issues/1962.
=> fix: Space privacy indicator tooltip is now above everything else

LICENSE, ee/LICENSE
The goal of the EE license is to protect our enterprise features, which includes our current SaaS-specific functionality and, in the future, any features that may not be available in the free-to-download self-hosted version.
The license is forward-looking - it defines what will be CE once we make that distinction. Until then, our current self-hosted version remains as is, while the EE license protects specific features in our `ee` folder that are part of our proprietary SaaS offering, whether user-facing or not.
The license is based on GitLab's, which is the gold standard for open core software companies.
Fixes #2026.
=> chore: Add EE License

assets/js/api/index.tsx, assets/js/pages/GoalCheckInNewPage/Form.tsx, lib/operately/activities/content/goal_check_in.ex, lib/operately/goals/timeframe.ex, lib/operately/operations/goal_check_in.ex, lib/operately_web/api/mutations/post_goal_progress_update.ex, test/operately/operations/goal_check_in_test.exs
I've updated the `Operately.Operations.GoalCheckIn` operation. Now, it also updates a Goal's timeframe if it detects changes.
The `:goal_check_in` activity includes the new and old timeframes only if there are changes. I chose this approach for several reasons:
- If timeframes were required and always present in the activity, we would likely need to write a migration to populate the timeframe fields in existing activities.
- The check-in operation and activity should remain compatible with both the old and new check-in forms since the new form is used only when this feature is enabled.
- Timeframe changes should be displayed in the feed only if changes exist. This way, if the timeframe is not present in the activity, it means there are no differences and it shouldn't be displayed.
=> chore: GoalCheckIn operation updates timeframe

assets/js/api/index.tsx, assets/js/features/activities/GoalCheckIn/index.tsx, assets/js/features/activities/GoalTimeframeEditing/TimeframeEdited.tsx, assets/js/features/activities/GoalTimeframeEditing/index.tsx, assets/js/models/goals/index.tsx, lib/operately_web/api/serializers/activity_content/goal_check_in.ex, lib/operately_web/api/types.ex
If a Goal check-in includes a timeframe change, it will now be displayed in the feed. 
The timeframe changes in the `GoalCheckIn` and `GoalTimeframeEditing` activities now share the same component:
=> feat: Display timeframe change in goal check-in feed event

assets/js/api/index.tsx, assets/js/features/goals/GoalCheckIn/Form.tsx, assets/js/features/goals/GoalCheckIn/index.tsx, assets/js/features/goals/GoalCheckIn/useForm.tsx, assets/js/pages/GoalCheckInNewPage/Form.tsx, assets/js/pages/GoalCheckInPage/Form.tsx, lib/operately/activities/content/goal_check_in_edit.ex, lib/operately/operations/goal_check_in_edit.ex, lib/operately_web/api/mutations/edit_goal_progress_update.ex
The `Operately.Operations.GoalCheckInEdit` operation now also updates the timeframe.
I noticed that there was a lot of repeated code in the check-in create and edit forms, so I've combined them into a single `Form` component and `useForm` hook.
=> chore: GoalCheckInEdit operation updates timeframe

assets/js/features/goals/GoalCheckIn/useForm.tsx
A Goal Timeframe is now displayed correctly regardless of the user's time zone.
It turned out that the dates were being saved correctly in the database. The problem was when they were parsed in the frontend.
=> fix: Goal timeframe dates are correct regardless of time zone

assets/js/components/Forms/Form.tsx, assets/js/features/goals/GoalCheckIn/Form.tsx
In the goal check-in form, when a target is updated by pressing "enter", it no longer submits the form.
=> fix: Check-in form is not submitted when target is edited

assets/js/pages/GoalPage/index.tsx, assets/js/pages/GoalV2Page/index.tsx, assets/js/pages/index.tsx, assets/js/routes/index.tsx, assets/js/routes/paths.tsx
I've added the `new_goal_page` feature flag. If this feature is enabled, when the user navigates to the Goal page, they are going to be redirected to the Goal V2 page. 
Once the Goal V2 page is ready, it will become the Goal page.
=> chore: Redirect to new Goal page if feature enabled

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/loader.tsx, assets/js/pages/GoalV2Page/useForm.tsx, assets/js/pages/GoalV2Page/utils.tsx
A Goal can now be edited from the new Goal Page.  However, the Goal's parent and targets are not edited yet:
- The Goal's parent is still not supported by the `GoalEditing` operation. 
- The Goal's targets section is not ready yet.
=> feat: Goal can be edited from new Goal Page

assets/js/pages/GoalV2Page/utils.tsx
On the new Goal Page, the time left to complete the Goal is displayed correctly. The timeframe message now also handles cases when the time has already expired.
=> fix: Timeframe is displayed correctly on new Goal Page

assets/js/components/Forms/TitleInput.tsx, assets/js/pages/GoalV2Page/Description.tsx, assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/Name.tsx, assets/js/pages/GoalV2Page/components.tsx, assets/js/pages/GoalV2Page/contributors.tsx
I've made several adjustments in the new Goal Page:
- No extra space is now displayed when the Goal doesn't have a description
- Titles are now bold
- The champion and reviewer names are now displayed with smaller font.
- "Next Check-in" section is now aligned with the Goal title.
=> fix: Several adjustments in new Goal Page

assets/js/components/Chronometer/index.tsx, assets/js/components/Forms/TimeframeField.tsx, assets/js/pages/GoalV2Page/Timeframe.tsx
On the new Goal Page, while on "view" mode, the Timeframe Chronometer is displayed in gray.
=> chore: Chronometer component can be displayed in gray

assets/js/features/goals/GoalPageHeader/index.tsx, assets/js/pages/GoalV2Page/page.tsx
When a Goal is closed or archived, a banner is displayed informing the user.
=> feat: Display banner when Goal is closed or archived

assets/js/features/ResourceHub/components/DocumentMenu.tsx, assets/js/utils/markdown.ts, package-lock.json, package.json
This pull request adds document export to markdown ⚡️
What's in this:
- Built with ProseMirror's serializer to match GitHub Flavored Markdown spec
- Can strip out embeds when exporting (super helpful for LLMs!)
- Supports all the usual markdown goodies (headings, lists, code blocks)
Closes #2038
=> feat: markdown export with embeds removal for documents

assets/js/components/Forms/GoalTargetsField.tsx, assets/js/components/charts/MiniPieChart.tsx, assets/js/features/goals/GoalCheckIn/Form.tsx, assets/js/pages/GoalV2Page/Form.tsx
The new Goal Page and the Goal Check-in Page now share the same Targets field. 
The borders which look nice in the Check-in Page didn't look good in the Goal Page:
I tried hiding the borders, but it became difficult to determine which values belonged to which targets:
Finally, I added some dots to connect targets and values:
In my opinion, the layout with the dots looks better than the others, though we can probably improve it further.
=> feat: Goal and CheckIn pages share the same Targets field

assets/js/models/goals/index.tsx
The `assertGoalStatusValidity` did not support the "concern" status.
=> fix: assertGoalStatusValidity supports concern status

lib/operately_web/api/queries/get_goal.ex
Now, when the `GetGoal` query includes targets, they are sorted by their index.
=> fix: Always sort targets by index

assets/js/features/goals/GoalCheckIn/Form.tsx, assets/js/features/goals/GoalTargetsV2/TargetValue.tsx
Previously, on the Goal Check-in page, when the `ValueEdit` component was focused, pressing the "enter" key would move the focus to the description field and unexpectedly enable the bold style for the description. Now, pressing "enter" simply removes the focus from `ValueEdit`.
=> fix: Handle blur event in target ValueEdit component

assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/TargetNameSection.tsx, assets/js/features/goals/GoalTargetsV2/index.tsx, assets/js/features/goals/GoalTargetsV2/utils.tsx, assets/js/pages/GoalV2Page/utils.tsx, assets/js/utils/numbers.tsx
On the new Goal Page, targets' `name`, `from`, `to` and `unit` can be now be edited.
=> feat: Target definition can be edited on the new Goal Page

assets/js/pages/GoalV2Page/Form.tsx, assets/js/pages/GoalV2Page/NextCheckIn.tsx
The "Next Check-in" button was moved to the bottom of the sidebar and changed to secondary.
=> fix: Check-in button changed to secondary

assets/js/pages/GoalV2Page/Messages.tsx
On the new Goal Page, in the conversations section, short date and name are displayed.
=> fix: Display short dates and names in Goal page conversations

assets/js/models/people/index.tsx
The `shortName` util didn't handle correctly cases where a person had only a first name. Previously, if the name was just "Adriano," `shortName` would return "Adriano A.".
Now, if no last name is present, `shortName` returns only the first name.
=> fix: shortName util handles person without last name

assets/js/features/goals/GoalTree/MinimalTree.tsx
On the new Goal Page, in the related work section, the resource's progress is rounded down and the container width is always the same.
=> fix: All progresses in related work have the same width

assets/js/components/Link/index.tsx, assets/js/features/goals/GoalTree/MinimalTree.tsx, assets/js/pages/GoalV2Page/Messages.tsx
On the new Goal Page, in the conversations and related work sections, links are now underlined on hover.
=> fix: Links are underlined on hover on Goal page

assets/js/pages/ResourceHubDocumentPage/Options.tsx
Added markdown export option to document page dropdown menu, making the export functionality accessible directly from the document view.
=> feat: add markdown export to document page menu

lib/operately/data/change_051_populate_goal_last_check_ins.ex, lib/operately/goals/goal.ex, lib/operately/operations/goal_check_in.ex, lib/operately_web/api/queries/get_goal.ex, lib/operately_web/api/queries/get_goals.ex, lib/operately_web/api/serializers/goal.ex, package-lock.json, package.json, priv/repo/migrations/20250325115924_add_last_check_in_id_to_goals.exs, priv/repo/migrations/20250325131944_populate_last_check_in_on_goals.exs, test/operately/data/change_051_populate_goal_last_check_ins_test.exs, test/operately/operations/goal_check_in_test.exs, test/operately_web/api/queries/get_goal_test.exs, test/operately_web/api/queries/get_goals_test.exs
Two reasons for doing this:
- Performance: Looking up the latest check-in is common, needs to be fast.
- Preparation for limiting update operations for goal check-ins. The logic will be "if update.id == goal.last_update_id" then you can update the values otherwise no.
=> feat: Keep a reference to the last check-in in the goal

assets/js/features/goals/GoalTree/MinimalTree.tsx
On the new Goal page, in the related work section, colors are now less bright in the dark mode.
=> fix: Related work colors adjusted for dark mode

assets/js/pages/GoalV2Page/useForm.tsx
After https://github.com/operately/operately/pull/2202, editing a Goal on the new Goal page stopped working because the payload didn't include the timeframe type.
=> fix: Include timeframe type in Goal editing payload

assets/js/features/goals/GoalTargetsV2/DefaultTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/EditTargetCard.tsx, assets/js/features/goals/GoalTargetsV2/components/ExpandIcon.tsx, assets/js/features/goals/GoalTargetsV2/components/index.tsx
The chevron icon for targets now changes based on whether the target is expanded or collapsed.
=> fix: Chevron icon changes when target is collapsed

lib/operately/activities/context_auto_assigner.ex, lib/operately/comments.ex, lib/operately/goals.ex, lib/operately/operations/goal_deleting.ex, lib/operately/projects.ex, lib/operately/updates.ex, priv/repo/migrations/20250331193957_add_cascade_delete_to_goal_targets.exs, priv/repo/migrations/20250331194510_add_cascade_delete_to_goal_access_contexts.exs, priv/repo/migrations/20250331194727_add_cascade_delete_to_access_bindings.exs, priv/repo/migrations/20250331195524_add_cascade_delete_to_context_activities.exs, priv/repo/migrations/20250331200245_add_cascade_delete_to_project_access_contexts.exs, priv/repo/migrations/20250331202813_add_cascade_delete_to_goal_check_ins.exs, priv/repo/migrations/20250401104505_add_cascade_delete_to_activity_notifications.exs, test/operately/goals_test.exs, test/support/factory.ex, test/support/factory/comments.ex, test/support/factory/goals.ex, test/support/fixtures/goals_fixtures.ex
I made changes and added tests to ensure that:
- If a Goal has a child Project or a child Goal, it cannot be deleted.
- When a Goal is deleted, its related resources are also deleted.
Some resources, such as Check-ins, Access Context and Access Bindings, have a direct relationship to the Goal at the database level. These resources are cascade deleted with the Goal.
Other resources, such as Goal Discussions and Comments, don't have a relationship to the Goal at the database level. These resources are deleted manually as part of the Goal deletion transaction.
=> chore: Deleting a goal automatically deletes its children

assets/js/features/projectCheckIns/DescriptionSection.tsx, assets/js/pages/ProjectCheckInPage/page.tsx
This PR resolves Issue #2206 by broadening the wording used in project check-ins, following the suggested guidelines
=> fix: Too wide text for project check-ins

assets/js/components/Forms/useForm.tsx, assets/js/pages/CompanyAdminAddPeoplePage/index.tsx, lib/operately/operations/company_member_adding.ex, lib/operately/people/person.ex, lib/operately_web/api/mutations/add_company_member.ex, priv/repo/migrations/20250403112800_add_unique_account_plus_company_constraint_to_people.exs, test/operately_web/api/mutations/add_company_member_test.exs
Fixes https://github.com/operately/operately/issues/2227:
- Each company can now have a person with a given email address, allowing the same email to be associated with different companies.
- A constraint was added at the database level to make sure two people never have both the same account and company.
- If there is an attempt to create two people with same email in the same company, an error message is displayed in the UI.
=> fix: Same email can be used to create one person per company

app/assets/js/api/index.tsx, app/assets/js/pages/CompanyAdminAddPeoplePage/index.tsx, app/lib/operately/activities/content/company_member_added.ex, app/lib/operately/operations/company_member_adding.ex, app/lib/operately/people.ex, app/lib/operately_web/api/mutations/add_company_member.ex, app/test/features/invite_member_test.exs, app/test/operately_web/api/mutations/add_company_member_test.exs, app/test/support/features/invite_member_steps.ex
Now, when an admin attempts to add a member to the company, if the new member doesn't yet have an Operately account, a link with a token is generated that they can use to log in for the first time. If the new member already has an Operately account, they are added to the company directly.
=> fix: Invitation token is created for new accounts only

Makefile
This PR resolves Issue #2061: ensures that the following environment variables are present in the .env file when running make dev.setup:
•	ALLOW_LOGIN_WITH_EMAIL=yes
•	ALLOW_SIGNUP_WITH_EMAIL=yes
These variables are required to enable email-based login and signup in development.
=> Ensure email login/signup flags are present in .env during setup

.semaphore/semaphore.yml, app/jest.config.json, app/package.json, app/tsconfig.json, turboui/tsconfig.json
Currently, because jest was not working with the new configuration, in the `semaphore.yml` file, we are skipping npm tests by using the command `make test.npm || true`.
In this PR, I'm fixing the npm tests and I'm changing the command to run the tests back to just `make test.npm`.
=> fix: Fix npm tests

app/lib/operately_web/account_auth.ex
This is another attempt at fixing https://github.com/operately/operately/issues/2015.
=> fix: User redirected to correct path after oauth login

turboui/src/Avatar/index.tsx
The `Avatar` component no longer shows error in the console when `person.fullName` is null.
=> fix: Avatar component handles null fullName

app/vite.config.mjs
fix found here: https://github.com/vitejs/vite/issues/19091
once this PR is merged we can remove the extra stuff in the vite config: https://github.com/vitejs/vite/pull/19092
fixes https://github.com/operately/operately/issues/2276
=> chore: Kill the vite dev server when the mix server shuts down

scripts/license_finder.yml
I've added the missing dependencies to `scripts/license_finder.yml`. 
`make test.license.check` should work after these changes.
=> fix: Add missing dependencies to scripts/license_finder.yml

turboui/src/WorkMap/TableRow/ActionButtons.tsx
The action button in the `WorkMap` component wasn't aligned and had an unintended shadow. Both issues were fixed.
=> fix: Remove shadow from action button in WorkMap

turboui/src/TimeframeSelector/index.tsx, turboui/src/WorkMap/TableRow/RowContainer.tsx, turboui/src/WorkMap/WorkMapTable/index.tsx
Now, the WorkMap rows and TimeframeSelector have the correct background color both by default and on hover.
=> fix: Display the correct background color in WorkMap rows and TimeframeSelector

.vscode/settings.json, .vscode/tasks.json
I've added some tasks for running unit directly from vscode. These tasks can be mapped to shortcuts.
=> chore: Add tasks for running tests on vscode

app/lib/operately/work_maps/work_map_item.ex, app/test/operately/work_maps/work_map_item_test.exs, app/test/support/factory.ex, app/test/support/factory/goals.ex, app/test/support/factory/projects.ex, app/test/support/fixtures/projects_fixtures.ex
The status of closed projects and goals was not being displayed correctly.
=> fix: Show correct status in Work Map when project or goal is closed

turboui/src/TimeframeSelector/index.tsx
Now, the Timeframe Seletor is highlighted both on hover and when a timeframe is selected.
=> fix: TimeframeSelector is highlighted when timeframe is selected

turboui/src/WorkMap/TableRow/DeadlineCell.tsx
I've changed the overdue color in the Work Map to text-content-error.
=> fix: Change overdue color to text-content-error

turboui/src/GoalPage/index.stories.tsx, turboui/src/GoalPage/index.tsx
Show a warning to the reader that the goal is outdated if the champion did not update the goal for more than a month.
=> chore: Neglected goal state

app/lib/operately/work_maps/work_map_item.ex, turboui/src/StatusBadge/index.tsx
Outdated items now have the "outdated" status in the Work Map.
=> fix: Show outdated items in Work Map

turboui/src/WorkMap/TableRow/DeadlineCell.tsx
In the Work Map, when item has no deadline, `N/A` is now displayed.
=> fix: Display N/A when item doesn't have deadline

app/lib/operately/operations/goal_reopening.ex, app/package-lock.json
If a Goal was closed and then reopened, it would remais in the "Completed" tab. Now, if a goal is reopened, it's correctly displayed in the "All Work" and "Goals" tabs.
=> fix: Reopening a goal now removes it from the Completed Tab

app/assets/js/pages/ResourceHubEditDocumentPage/form.tsx, app/test/features/resource_hub_document_test.exs, app/test/support/features/resource_hub_document_steps.ex
Fixes https://github.com/operately/operately/issues/2114.
=> fix: Add cancel button to document edit page

turboui/src/WorkMap/components/TableRow/index.tsx
I've removed the scale up effect in the StatusBadge which was causing performance issues.
=> fix: Remove StatusBadge scale up effect to fix Work Map performance issue

Makefile, app/lib/operately_web/controllers/page.html.heex, app/lib/operately_web/controllers/page_controller.ex
Fixes Wallaby feature tests that were failing with MIME type errors when loading JavaScript modules. The solution uses the Vite dev server for local tests while maintaining the production asset loading for CI environments.
=> fix: Use dev JS loading strategy for local tests to fix Wallaby failures

turboui/src/WorkMap/components/TableRow/ItemNameCell.tsx, turboui/src/WorkMap/components/TableRow/OwnerCell.tsx, turboui/src/WorkMap/components/TableRow/RowContainer.tsx, turboui/src/WorkMap/components/TableRow/SpaceCell.tsx
Previously, only clicking the item name would redirect the user to the item page. Now, clicking anywhere in the row, except for the Space and Owner names, redirects the user to the item page.
=> fix: Clicking anywhere in item row redirects to item page

app/lib/operately/work_maps/work_map.ex
In the Work Map, projects are now displayed before subgoals.
=> feat: Display projects before subgoals

turboui/src/Avatar/Avatar.stories.tsx, turboui/src/Avatar/AvatarWithName.tsx
In the `AvatarWithName` component, the text size is now also adjusted based on the `size` prop.
=> feat: Text size also adjusts in AvatarWithName

turboui/.storybook/preview.d.ts, turboui/.storybook/preview.tsx, turboui/src/WorkMap/hooks/useWorkMapFilter.ts, turboui/src/global.d.ts
In Storybook, the Work Map tabs were overwriting the Storybook URL. Now this problem is fixed.
=> fix: Work Map tabs now work in Storybook

turboui/src/WorkMap/components/WorkMapTable.tsx
The Space header and the Space names weren't correctly aligned.
=> fix: Align space th and td in Work Map

turboui/src/WorkMap/components/WorkMapTable.tsx
Sometimes, there was a line break in the headers and they would end up taking two lines. This problem is now fixed.
=> fix: Work Map headers always take only one line

app/priv/static/.vite/manifest.json, turboui/src/Modal/Modal.stories.tsx, turboui/src/Modal/index.tsx, turboui/src/TaskBoard/components/TaskCreationModal.tsx, turboui/src/TaskBoard/components/index.tsx, turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/stories/TaskCreationModal.stories.tsx
- Add generic `Modal` component to turboui
- Task creation works on general button and on clicking "+" within each milestone
- Can check "Create more" to keep the dialog open and add many tasks quickly
- The dialog features vanilla select boxes. We need to figure out for which ones if any we want to use special components.
=> feat: Task creation in task board

app/assets/js/models/workMap/index.tsx, app/assets/js/pages/SpaceWorkMapPage/loader.tsx, turboui/src/WorkMap/hooks/useWorkMapTab.ts
Now, paused projects are not included in the "All work" tab in the Work Map.
=> fix: Paused projects are not shown in the 'All work' tab

app/lib/operately/work_maps/get_work_map_query.ex, app/priv/repo/migrations/20250519132749_add_missing_indexes_for_goals_and_projects_and_other_resources.exs
I identified and fixed some problems in `GetWorkMapQuery` that were slowing it down significantly.
I also added several indexes that were missing.
These changes should improve page load time for the Work Map significantly: https://github.com/operately/operately/issues/2483.
=> chore: Improve GetWorkMapQuery and add missing indexes

app/lib/operately/work_maps/get_work_map_query.ex
Previously we were using join-based preloads for one-to-many relationships, which caused the main query to return many duplicated rows. 
Now, one-to-many associations are loaded in separate queries, which eliminates duplication and improves performance.
=> chore: Optimize GetWorkMap query

app/assets/js/layouts/CompanyLayout/index.tsx
If "work_map_page" feature is enabled, the "Goals" link in the navbar redirects to the Work Map page.
=> chore: Goals link redirects to Work Map if feature is enabled

app/assets/js/features/SpaceTools/GoalsAndProjects.tsx, app/assets/js/routes/redirectIfFeatureEnabled.tsx
If "space_work_map" feature is enabled, the "Goals & Projects" space tool redirects to the Space Work Map page.
=> chore: 'Goals & Projects' tool redirects to Work Map if feature is enabled

turboui/src/WorkMap/components/WorkMapNavigation.tsx
Display the "paused" tab before the "completed" tab in the Work Map.
=> chore: 'paused' tab is before 'completed' tab in Work Map

app/test/features/resource_hub_folder_test.exs, app/test/support/custom_formatter.ex, app/test/support/feature_steps.ex, app/test/support/features/resource_hub_folder_steps.ex, app/test/support/features/ui.ex
Example output when you put `@tag :trace` on top of your test.
```
Feature: folders create folders at the root of resource hub (test/features/resource_hub_folder_test.exs:19)
setup
->   1075 ms - visit
->    546 ms - assert_has
visit_resource_hub_page
->    824 ms - visit
create_folder
->    444 ms - click
->     75 ms - click
->    167 ms - fill
->     48 ms - click
->     94 ms - refute_text
assert_folder_created
->     20 ms - assert_text
->     41 ms - assert_text
->    228 ms - find
create_folder
->    161 ms - click
->    120 ms - click
->    279 ms - fill
->     45 ms - click
->     85 ms - refute_text
assert_folder_created
->      9 ms - assert_text
->      9 ms - assert_text
->     33 ms - find
```
=> chore: Trace feature test step durations

app/lib/operately/work_maps/work_map.ex, app/test/operately/work_maps/get_work_map_query_test.exs
Previously, when an item matched the Work Map filters, but its parents didn't, the item was included in the Work Map as a root item, without its parents.
Now, if an items matches the filters, the whole hierarchy is included.
=> fix: Work Map includes the whole parent hierarchy of items

app/assets/js/api/index.tsx, app/assets/js/models/people/index.tsx, app/assets/js/pages/ProfilePage/loader.tsx, app/assets/js/pages/ProfileV2Page/index.tsx, app/assets/js/pages/index.tsx, app/assets/js/routes/index.tsx, app/assets/js/routes/paths.tsx, app/lib/operately_web/api/serializers/person.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/queries/get_space_test.exs, app/test/operately_web/api/queries/search_project_contributor_candidates_test.exs, turboui/src/PersonCard/index.tsx, turboui/src/ProfilePage/components/Colleagues.tsx, turboui/src/ProfilePage/components/index.tsx, turboui/src/ProfilePage/index.tsx, turboui/src/index.tsx
I'm working on https://github.com/operately/operately/issues/2518. 
So far I added only the about and activity tabs. I'm going to add the Work Map tabs (Assigned and Reviewing) in the upcoming PRs. 
I'm calling it "ProfileV2Page", but we can change it to another name if the current name is not correct.
=> feat: Add Profile V2 page behind feature flag

app/assets/js/api/index.tsx, app/assets/js/models/workMap/index.tsx, app/assets/js/pages/ProfileV2Page/loader.tsx, app/lib/operately/work_maps/get_work_map_query.ex, app/lib/operately/work_maps/work_map.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/queries/get_flat_work_map.ex, app/test/operately/work_maps/get_work_map_query_test.exs, app/test/operately_web/api/queries/get_flat_work_map_test.exs, turboui/src/ProfilePage/index.tsx
I've added a new query which filters Work Map items without including their parents. This new query is necessary to get the required result for the "My Work" page (https://github.com/operately/operately/issues/2518).
=> fix: Query flat Work Map without including items' parents

turboui/src/Tabs/index.tsx
Before these changes, the tab icon sometimes got squished in small screens and, if the text had more than 1 word, the line would break.
=> fix: TabItem no longer gets squished and line doesn't break

turboui/src/Tabs/index.tsx
Now, tabs on the new profile page don't overflow the page in small screens.
=> fix: Profile tabs no longer overflows the page in small screen

turboui/src/Tabs/index.tsx
Now, the border-b in the Tabs component looks good in both the light and dark themes.
=> fix: Tabs border-b looks good in both light and  dark theme

app/assets/js/pages/GoalV3Page/index.tsx
e.g. if you click on "see parent goal", it will close the popup window from the previous page
=> fix: Reset page state when navigating away

app/lib/operately/work_maps/work_map.ex, app/test/operately/work_maps/get_work_map_query_test.exs
When you included contributor in the Work Map query, project reviewers were being treated as contributors. This PR fixes this issue.
=> fix: Don't include reviewer as contributor in Work Map query

app/test/support/feature_case.ex, docker-compose.yml, docker/dev/Dockerfile.dev
The key was: `shm_size: 1g`. After that change I had no problems with invalid session id.
fixes https://github.com/operately/operately/issues/2720
=> chore: Fix invalid session problems

app/assets/js/features/ResourceHub/components/FolderMenu.tsx, app/test/features/resource_hub_folder_test.exs, app/test/support/features/resource_hub/deletion.ex, app/test/support/features/resource_hub_steps.ex
I'm working on https://github.com/operately/operately/issues/2647.
Now, before deleting a folder, the user has to confirm the deletion.
=> feat: Add confirmation modal for folder deletion in Resource Hub

app/assets/js/pages/ResourceHubNewLinkPage/form.tsx, app/test/features/resource_hub_link_test.exs, app/test/support/features/resource_hub_link_steps.ex
Fixes https://github.com/operately/operately/issues/2752.
=> fix: Links can now be created without a description

app/assets/js/features/ResourceHub/components/LinkMenu.tsx, app/assets/js/pages/ResourceHubLinkPage/Options.tsx, app/assets/js/pages/ResourceHubLinkPage/page.tsx, app/test/features/resource_hub_link_test.exs
I'm working on https://github.com/operately/operately/issues/2647.
Now both on the Resource Hub and the Link pages, before deleting a link, the user has to confirm the deletion.
=> feat: Add confirmation modal for link deletion in Resource Hub

app/lib/operately/data/change_058_update_projects_last_check_in_status.ex, app/test/operately/data/change_058_update_projects_last_check_in_status_test.exs
I'm extending the project check-in migration to also handle the `at_risk` status.
=> fix: Handle at_risk status in project check-in migration

app/assets/custom-vite-plugins.mjs, app/vite.config.mjs
We were using this module to track down that Vite slowness comes from excessive Tabler icon compilation. I'm adding it permanently to out setup.
Example output:
```
=== MODULE ANALYSIS ===
app-source                                                    848 modules
node_modules/date-fns                                         626 modules
node_modules/@tabler/icons-react                              145 modules
node_modules/@popperjs/core                                   114 modules
node_modules/react-spinners                                    54 modules
node_modules/markdown-it                                       53 modules
node_modules/axios                                             50 modules
node_modules/@babel/runtime                                    48 modules …
```
=> chore: Bootstrap module analyzer

app/assets/js/api/index.tsx, app/assets/js/features/ProjectRetrospective/Form.tsx, app/assets/js/pages/ProjectCheckInPage/page.tsx, app/assets/js/pages/ProjectRetrospectiveEditPage/page.tsx, app/assets/js/pages/ProjectRetrospectivePage/page.tsx, app/lib/operately/operations/project_retrospective_editing.ex, app/lib/operately_web/api/mutations/close_project.ex, app/lib/operately_web/api/mutations/edit_project_retrospective.ex, app/lib/operately_web/api/serializers/project.ex, app/lib/operately_web/api/types.ex, app/test/features/project_retrospective_test.exs, app/test/operately/operations/project_retrospective_editing_test.exs, app/test/operately_web/api/mutations/edit_project_retrospective_test.exs, app/test/support/features/project_retrospective_steps.ex
This work is part of https://github.com/operately/operately/issues/2709.
Now, project retrospectives can be edited.
=> feat: New Project Retrospective can be edited

app/assets/js/features/activities/GoalCheckIn/index.tsx
Now, the new statuses are handled in the GoalCheckIn feed item.
=> fix: Handle new statuses in GoalCheckIn feed item

app/assets/css/global.css, app/assets/css/prosemirror.css, app/assets/css/reactdatepicker-custom.css, app/assets/js/components/Badges/AccessLevelBadges.tsx, app/assets/js/components/Callouts/index.tsx, app/assets/js/features/ResourceHub/FileDragAndDropArea.tsx, app/assets/js/features/projects/AccessLevel.tsx, app/assets/js/features/spaces/AccessLevel/index.tsx, app/assets/js/pages/ReviewPage/page.tsx, app/assets/tailwind.config.js, turboui/src/Button/index.tsx, turboui/src/Callouts/index.tsx, turboui/src/Colors/Colors.stories.tsx, turboui/src/GoalPage/Sidebar.tsx, turboui/src/PersonCard/index.tsx, turboui/src/ProgressBar/index.tsx, turboui/src/ProjectPage/MilestoneItem.tsx, turboui/src/RichEditor/Blob/BlobView.tsx, turboui/src/RichEditor/extensions/MentionPeople/MentionList.tsx, turboui/src/StatusBadge/index.tsx, turboui/src/TaskPage/Sidebar.tsx, turboui/src/Toasts/index.tsx, turboui/tailwind.config.js
Removed 3 `callout-*` colors. Related to #2817. Next steps will be to remove `accent-*` and `success`.
Also realized that `emerald` greens in Tailwind are closer to what we previously had as main custom green than pure `green`.
=> chore: Remove 3 colors from the system

app/lib/operately/projects/project.ex, app/test/operately/work_maps/work_map_item_test.exs
Now, the statuses "Achieved" and "Missed" are shown for projects in the Work Map completed tab.
=> chore: Update status of closed projects in Work Map

app/lib/operately/goals/goal.ex, app/lib/operately/projects/project.ex, app/test/operately/goals/goal_test.exs, app/test/operately/work_maps/work_map_item_test.exs
Previously, quick adding a project or goal would create an item with the `pending` status, but after reloading the page, the newly created item would have the `on_track` status.
Now, new items have the `pending` status until there is a check-in/update or until the status is changed to `outdated`.
=> fix: Handle pending status for new projects and goals

app/assets/js/components/status/Status.tsx
The status placeholder was invisible on the Project Check-in page.
=> fix: Project Check-in status placeholder is now visible

turboui/src/DatePicker/components/MonthSelector.tsx, turboui/src/DatePicker/components/QuarterSelector.tsx, turboui/src/DatePicker/components/YearSelector.tsx
Now, the current year is always within view when the date type tab changes.
=> feat: Date Picker scrolls to current year when tab changes

app/assets/js/api/index.tsx, app/lib/operately/contextual_dates/contextual_date.ex, app/lib/operately_web/api/types.ex, turboui/src/DatePicker/DatePicker.stories.tsx, turboui/src/DatePicker/components/InlineCalendar.tsx, turboui/src/DatePicker/index.tsx, turboui/src/DatePicker/types.ts
I ran into some problems while integrating the DatePicker component with the backend resources because there types weren't exactly the same. These changes address this issue.
=> chore: Adjust Contextual Dates date types

app/lib/operately/contextual_dates/contextual_date.ex, app/lib/operately/data/change_065_timeframe_contextual_date_backfill.ex, app/priv/repo/migrations/20250716095720_populate_existing_goals_timeframe_with_contextual_date.exs, app/test/operately/contextual_dates/contextual_date_test.exs, app/test/operately/data/change_065_timeframe_contextual_date_backfill_test.exs
I've added a migration to populate the existing Goals timeframe with contextual dates.
=> chore: Add migration for populating Goals timeframe with contextual date

app/assets/js/api/index.tsx, app/assets/js/models/contextualDates/index.tsx, app/assets/js/pages/GoalPage/index.tsx, app/lib/operately/contextual_dates/contextual_date.ex, app/lib/operately_web/api/goals.ex, app/test/features/goal_test.exs, app/test/operately/contextual_dates/contextual_date_test.exs, app/test/operately_web/api/goals_test.exs, turboui/src/DatePicker/index.tsx, turboui/src/GoalPage/Sidebar.tsx, turboui/src/GoalPage/index.stories.tsx, turboui/src/GoalPage/index.tsx, turboui/src/index.tsx
Now, we can set a Goal's due date as a contextual date using the new Date Picker component.
=> feat: Add DatePicker component to Goal page

turboui/src/DatePicker/DatePicker.stories.tsx, turboui/src/DatePicker/index.tsx
Now we can choose between an `inline` and `form-field` DatePicker variant.
=> feat: Add inline and form-field variants to DatePicker

turboui/src/DatePicker/components/MonthSelector.tsx, turboui/src/DatePicker/components/QuarterSelector.tsx, turboui/src/DatePicker/components/YearSelector.tsx, turboui/src/DatePicker/index.tsx, turboui/src/DatePicker/utils.ts
The DatePicker component can now be used to set contextual dates which use the beginning of a period of time instead of the end. For example, when the users sets year "2026", instead of the value being "2026-12-31", it will be "2026-01-01". This feature will enable the component to be used for setting the start date of Goals and Projects.
=> chore: Add useStartOfPeriod flag to DatePicker component

app/assets/js/features/Subscriptions/useSubscriptions.tsx, app/assets/js/pages/ProjectDiscussionNewPage/index.tsx, app/lib/operately/projects/project.ex
tldr: the subscription mechanism was copied from the check-in page where you can't deselect the reviewer. This makes sense in the context of the check-in, but not for project discussions.
fixes https://github.com/operately/operately/issues/2957
=> fix: Don't assume that reviewers can't be deselected for project discussions

app/assets/js/api/index.tsx, app/assets/js/features/activities/ProjectDueDateUpdating/index.tsx, app/assets/js/features/activities/ProjectStartDateUpdating/index.tsx, app/assets/js/features/activities/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately/activities/content/project_due_date_updating.ex, app/lib/operately/activities/content/project_start_date_updating.ex, app/lib/operately/activities/context_auto_assigner.ex, app/lib/operately/activities/notifications/project_due_date_updating.ex, app/lib/operately/activities/notifications/project_start_date_updating.ex, app/lib/operately_web/api.ex, app/lib/operately_web/api/projects.ex, app/lib/operately_web/api/serializers/activity_content/project_due_date_updating.ex, app/lib/operately_web/api/serializers/activity_content/project_start_date_updating.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/projects_test.exs
A Project's start and due dates can now be edited on the Project V2 page.
=> feat: start and due dates can be updated on Project V2 page

app/assets/js/components/Editor/Blob/PasteHtmlImagesPlugin.tsx, app/assets/js/components/Editor/Blob/index.tsx
When some content that contains images is pasted into a document, the images are removed from the content. This prevents TipTap from breaking.
=> fix: TipTap doesn't break when documents are pasted with images

app/assets/js/api/index.tsx, app/assets/js/pages/ProjectV2Page/index.tsx, app/lib/operately_web/api/types.ex
Now, clicking on contributor on the new Project page redirects to the contributor's profile page.
=> fix: Clicking on contributor redirects to profile page

turboui/src/ProjectPage/OverviewSidebar.tsx
The Project's parent Goal now doesn't overflow the new Project page.
=> fix: Prevent parent Goal from overflowing Project V2 page

app/assets/js/api/index.tsx, app/lib/operately/data/change_072_populate_project_id_in_tasks.ex, app/lib/operately/operations/task_adding.ex, app/lib/operately/projects/project.ex, app/lib/operately/tasks/task.ex, app/lib/operately_web/api/mutations/create_task.ex, app/lib/operately_web/api/projects.ex, app/priv/repo/migrations/20250813170624_add_project_id_to_tasks_schema.exs, app/priv/repo/migrations/20250813171118_populate_project_id_in_tasks_schema.exs, app/test/operately/access/activity_context_assigner_test.exs, app/test/operately/data/change_013_create_activities_access_context_test.exs, app/test/operately/data/change_072_populate_project_id_in_tasks_test.exs, app/test/operately/operations/task_description_change_test.exs, app/test/operately/operations/task_status_change_test.exs, app/test/operately/operations/task_update_test.exs, app/test/operately/tasks_test.exs, app/test/operately_web/api/mutations/change_task_description_test.exs, app/test/operately_web/api/mutations/update_task_status_test.exs, app/test/operately_web/api/mutations/update_task_test.exs, app/test/operately_web/api/queries/get_task_test.exs, app/test/operately_web/api/queries/get_tasks_test.exs, app/test/support/factory/projects.ex, turboui/src/TaskBoard/types.ts
I've added a `project_id` field to Tasks. This will be necessary for us to be able to create Tasks which don't belong to any milestone.
=> chore: Add project_id to Tasks

turboui/src/TaskBoard/components/MilestoneCard.tsx
Clicking on Milestone title in the MilestoneCard component no longer redirects to inexistent page.
=> fix: MilestoneCard redirects to Milestone page correctly

turboui/src/TaskBoard/components/StatusSelector.tsx
The `done` status was displayed in green in turboui, but in black in the main app. Now, it's green in both.
=> fix: Show green color instead of black in Task status

app/assets/js/pages/TaskPage/loader.tsx, app/assets/js/pages/TaskV2Page/index.tsx, app/assets/js/routes/paths.tsx
We can now use the `task_v2` feature flag to enable the new Task page.
=> chore: Add task_v2 ff to enable new Task page

app/assets/js/pages/TaskV2Page/index.tsx, app/lib/operately_web/api/queries/get_task.ex
The Task page no longer shows 404 if the Task doesn't have a milestone.
=> fix: Task without milestone doesn't return 404

app/assets/js/api/index.tsx, app/lib/operately_web/api/queries/get_activities.ex, app/lib/operately_web/api/types.ex, app/test/operately_web/api/queries/get_activities_test.exs
We can now use `OperatelyWeb.Api.Queries.GetActivities` to get the `Task` activities.
=> chore: Add task scope to get_activities query

app/assets/js/pages/TaskV2Page/index.tsx, turboui/src/TaskPage/InProjectContextStory.tsx, turboui/src/TaskPage/index.stories.tsx, turboui/src/TaskPage/index.tsx
The Project status was using the Task status prop on the new Task page, so the project status was not shown correctly. That's now fixed.
=> fix: Use separate prop for Project status on new Task page

app/assets/js/api/index.tsx, app/assets/js/models/activities/tasks.tsx, app/lib/operately/activities/content/task_description_change.ex, app/lib/operately/data/change_078_enhance_task_description_change_activities.ex, app/lib/operately/operations/task_description_change.ex, app/lib/operately/tasks.ex, app/lib/operately/tasks/description.ex, app/lib/operately_web/api/mutations/change_task_description.ex, app/lib/operately_web/api/project_tasks.ex, app/lib/operately_web/api/serializers/activity_content/task_description_change.ex, app/lib/operately_web/api/types.ex, app/priv/repo/migrations/20250822164615_add_has_description_field_to_task_description_change_activity.exs, app/test/operately/access/activity_context_assigner_test.exs, app/test/operately/data/change_078_enhance_task_description_change_activities_test.exs
I've added the had_description field to the `task_description_change` activity which is necessary for the new feed.
=> chore: Add has_description field to task_description_change activity

turboui/src/TaskBoard/stories/TaskBoard.stories.tsx, turboui/src/TaskBoard/tests/mockData.ts
Partially solves the problem described in https://github.com/operately/operately/issues/3418:
1) The task within Mininal Milestone no longer disappears.
2) Changing a task status to done or canceled now hides the task.
=> fix: Reordering minimal Task works in storybook

app/assets/js/pages/GoalPage/index.tsx, app/assets/js/pages/ProjectCheckInsPage/CheckInButton.tsx, app/assets/js/pages/ProjectPage/index.tsx, turboui/src/GoalPage/CheckIns.tsx, turboui/src/GoalPage/Sidebar.tsx, turboui/src/GoalPage/index.stories.tsx, turboui/src/GoalPage/index.tsx, turboui/src/ProjectPage/CheckIns.tsx, turboui/src/ProjectPage/OverviewSidebar.tsx, turboui/src/ProjectPage/index.stories.tsx, turboui/src/ProjectPage/index.tsx, turboui/src/TaskBoard/components/index.tsx
- Replace 'Check-In Now' with simpler 'Check in' (plus we capitalize only first character in buttons now)
- Rename subsection header from 'Check-ins' to 'Last update' to avoid repeating the term and reflect presence of only the last one
- Being always present and providing zero-state microcopy will help educate new users about this core feature
Resolves #3170.
=> feat: Always show 'Last update' section with 'Check in' button in Goal and Project sidebars

turboui/src/PageDescription/index.tsx
The area around the page description where the user can click to edit it is now bigger.
=> feat: Make page description easier to click

app/assets/js/features/activities/TaskDueDateUpdating/index.tsx, app/test/features/project_tasks_test.exs, app/test/support/factory/projects.ex, app/test/support/features/project_tasks_steps.ex
The project name was not displayed correctly in the TaskDueDateChanged feed item:
That's now fixed. I've also added some tests to check this feed item.
=> fix: Fix project name in TaskDueDateChanged feed item

app/assets/js/routes/PageCache.tsx, app/test/features/project_tasks_test.exs, app/test/support/features/project_tasks_steps.ex, turboui/src/TaskPage/Sidebar.tsx
`PageCache` was triggering the loader when a page unmounts, which was causing unnecesary requests to be fired. 
Also, when a Task was deleted, we were getting a 404 error in the console. The user wasn't being affected by this error, but feature tests for deleting a Task wouldn't work because of this error.
=> fix: Don't throw 404 error when Task is deleted

app/lib/operately/assignments/loader_v2.ex, app/test/operately_web/api/queries/get_assignments_v2_test.exs
Fixes https://github.com/operately/operately/issues/3593.
=> fix: Exclude pending Tasks and Milestone from assignments if Project is closed
